Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2018-12, with the labels that each got.

#585 fix(annotations): merge CSV and pod template annotations when installing deployments
  pkg/controller/install/deployment.go
  pkg/controller/install/deployment_test.go
  scripts/run_e2e_local.sh
Labels: approved, size/M

#593 test(csv): use mock-ext-server for owned apiservice e2e test
  go.mod
  go.sum
  pkg/controller/operators/olm/apiservices.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, size/L

#596 Fix a typo in documentation
  Documentation/design/architecture.md
Labels: size/XS

#599 fix(e2e): fix CSV tests
  cmd/olm/main.go
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm, size/M

#602 feat(ci): remove e2e tests from gitlab
  .gitlab-ci.jsonnet
  .gitlab-ci.yml
  .gitlab-ci/base_jobs.libsonnet
  scripts/wait_in_queue.sh
Labels: approved, lgtm, size/L

#603 fix(e2e): make operator group test more robust
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/L

#611 Regen manifests
  deploy/ocp/manifests/0.8.0/0000_30_00-namespace.yaml
  deploy/ocp/manifests/0.8.0/0000_30_01-olm-operator.serviceaccount.yaml
  deploy/ocp/manifests/0.8.0/0000_30_02-clusterserviceversion.crd.yaml
  deploy/ocp/manifests/0.8.0/0000_30_03-installplan.crd.yaml
  deploy/ocp/manifests/0.8.0/0000_30_04-subscription.crd.yaml
  deploy/ocp/manifests/0.8.0/0000_30_05-catalogsource.crd.yaml
  deploy/ocp/manifests/0.8.0/0000_30_06-rh-operators.configmap.yaml
  deploy/ocp/manifests/0.8.0/0000_30_07-certified-operators.configmap.yaml
  deploy/ocp/manifests/0.8.0/0000_30_08-certified-operators.catalogsource.yaml
  deploy/ocp/manifests/0.8.0/0000_30_09-rh-operators.catalogsource.yaml
  deploy/ocp/manifests/0.8.0/0000_30_10-olm-operator.deployment.yaml
  deploy/ocp/manifests/0.8.0/0000_30_11-catalog-operator.deployment.yaml
  deploy/ocp/manifests/0.8.0/0000_30_12-aggregated.clusterrole.yaml
  deploy/ocp/manifests/0.8.0/0000_30_13-packageserver.csv.yaml
  deploy/ocp/manifests/0.8.0/0000_30_14-operatorgroup.crd.yaml
  deploy/ocp/manifests/0.8.0/0000_30_15-operatorgroup-default.yaml
  deploy/ocp/manifests/0.8.0/image-references
Labels: approved, lgtm, size/L

#608 use quay.io vs registry.reg-aws.openshift.com
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#562 Service Catalog CSV: update resource limitations
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#573 docs(arch): add operator groups
  Documentation/design/architecture.md
Labels: approved, lgtm, size/S

#574 chore(docs): fix markdown lint warnings
  Documentation/design/architecture.md
Labels: approved, size/M

#575 Make use a valid clusterPermissions rule verb
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
  deploy/ocp/manifests/0.8.0/0000_30_02-clusterserviceversion.crd.yaml
  deploy/okd/manifests/0.8.0/0000_30_02-clusterserviceversion.crd.yaml
  deploy/upstream/manifests/0.8.0/0000_30_02-clusterserviceversion.crd.yaml
  manifests/0000_30_02-clusterserviceversion.crd.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#615 add rbac for servicebindings/finalizers
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#587 Adding description to package manifest object
  pkg/package-server/apis/openapi/zz_generated.openapi.go
  pkg/package-server/apis/packagemanifest/v1alpha1/packagemanifest.go
  pkg/package-server/apis/packagemanifest/v1alpha1/packagemanifest_types.go
Labels: approved, lgtm, size/S

#589 Don't process CSVs without operatorgroup
  Makefile
  cmd/catalog/main.go
  cmd/olm/main.go
  deploy/chart/templates/0000_30_00-namespace.yaml
  deploy/chart/templates/0000_30_10-olm-operator.deployment.yaml
  deploy/chart/templates/0000_30_11-catalog-operator.deployment.yaml
  deploy/chart/templates/0000_30_16-operatorgroup-default.yaml
  go.mod
  go.sum
  manifests/0000_30_16-operatorgroup-default.yaml
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/controller/install/deployment_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/lib/ownerutil/util.go
  scripts/install_local.sh
  test/e2e/e2e-values.yaml
  test/e2e/operator_groups_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#617 Require pluralname for APIServiceDefinitions in CSVs
  cmd/validator/main.go
  deploy/chart/catalog_resources/certified-operators/couchbase-enterprise.package.yaml
  deploy/chart/catalog_resources/certified-operators/couchbase.1.0.0.clusterserviceversion.yaml
  deploy/chart/catalog_resources/certified-operators/dynatrace-monitoring.0.2.0.clusterserviceversion.yaml
  deploy/chart/catalog_resources/certified-operators/dynatrace-monitoring.package.yaml
  deploy/chart/catalog_resources/certified-operators/mongodb-enterprise.package.yaml
  deploy/chart/catalog_resources/certified-operators/mongodb-enterprise.v0.3.2.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/amq-streams.package.yaml
  deploy/chart/catalog_resources/rh-operators/amq-streams.v1.0.0.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/descheduler.v0.0.1.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/etcd.package.yaml
  deploy/chart/catalog_resources/rh-operators/etcdoperator.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/etcdoperator.v0.9.0.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/etcdoperator.v0.9.2.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/federationv2.v0.0.2.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/prometheus.package.yaml
  deploy/chart/catalog_resources/rh-operators/prometheusoperator.0.14.0.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/prometheusoperator.0.15.0.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/prometheusoperator.0.22.2.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/svcat.package.yaml
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
  deploy/ocp/manifests/0.7.1/0000_30_06-rh-operators.configmap.yaml
  deploy/ocp/manifests/0.7.2/0000_30_06-rh-operators.configmap.yaml
  deploy/ocp/manifests/0.7.4/0000_30_06-rh-operators.configmap.yaml
  deploy/ocp/manifests/0.8.0/0000_30_06-rh-operators.configmap.yaml
  deploy/okd/manifests/0.7.0/08-rh-operators.configmap.yaml
  deploy/okd/manifests/0.7.1/0000_30_06-rh-operators.configmap.yaml
  deploy/okd/manifests/0.7.2/0000_30_06-rh-operators.configmap.yaml
  deploy/okd/manifests/0.7.4/0000_30_06-rh-operators.configmap.yaml
  deploy/okd/manifests/0.8.0/0000_30_06-rh-operators.configmap.yaml
  deploy/upstream/manifests/0.4.0/08-tectonicocs.configmap.yaml
  deploy/upstream/manifests/0.4.0/09-tectoniccomponents.configmap.yaml
  deploy/upstream/manifests/0.4.0/18-upstreamcomponents.configmap.yaml
  deploy/upstream/manifests/0.5.0/08-tectonicocs.configmap.yaml
  deploy/upstream/manifests/0.5.0/09-tectoniccomponents.configmap.yaml
  deploy/upstream/manifests/0.5.0/18-upstreamcomponents.configmap.yaml
  deploy/upstream/manifests/0.6.0/08-ocs.configmap.yaml
  deploy/upstream/manifests/0.7.0/08-rh-operators.configmap.yaml
  deploy/upstream/manifests/0.7.1/0000_30_06-rh-operators.configmap.yaml
  deploy/upstream/manifests/0.7.2/0000_30_06-rh-operators.configmap.yaml
  deploy/upstream/manifests/0.7.4/0000_30_06-rh-operators.configmap.yaml
  deploy/upstream/manifests/0.8.0/0000_30_06-rh-operators.configmap.yaml
  manifests/0000_30_06-rh-operators.configmap.yaml
  pkg/lib/schema/schema.go
Labels: approved, lgtm, size/L

#570 Creating csv, crd, and packages for clusterlogging and elasticsearch …
  deploy/chart/catalog_resources/rh-operators/clusterlogging.package.yaml
  deploy/chart/catalog_resources/rh-operators/clusterlogging.v0.0.1.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/clusterloggings.crd.yaml
  deploy/chart/catalog_resources/rh-operators/elasticsearches.crd.yaml
  pkg/controller/registry/directory_loader_test.go
Labels: approved, lgtm, size/XL

#621 Updated CSV marketplace manifests
  deploy/chart/catalog_resources/rh-operators/marketplace-catalogsourceconfig.crd.yaml
  deploy/chart/catalog_resources/rh-operators/marketplace-operatorsource.crd.yaml
  deploy/chart/catalog_resources/rh-operators/marketplace.package.yaml
  deploy/chart/catalog_resources/rh-operators/marketplace.v0.0.1.clusterserviceversion.yaml
  pkg/controller/registry/directory_loader_test.go
Labels: approved, lgtm, size/L

#618 Add view permissions for CRDs on provided APIs
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/steps.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/S

#616 fix(olm): don't annotate target namespace on copied CSVs
  pkg/api/apis/operators/v1alpha2/operatorgroup_types.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/L

#556 Create registry pods for ConfigMap CatalogSources
  .gitignore
  Makefile
  cmd/catalog/main.go
  deploy/chart/templates/0000_30_05-catalogsource.crd.yaml
  go.mod
  go.sum
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler.go
  pkg/controller/registry/reconciler_test.go
  pkg/lib/operatorlister/configmap.go
  pkg/lib/operatorlister/lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_core_v1lister.go
  pkg/lib/operatorlister/pod.go
  pkg/lib/operatorlister/service.go
  scripts/build_bare.sh
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/ocs_e2e_test.go
  test/e2e/setup_bare_test.go
  test/e2e/setup_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
  vendor/github.com/operator-framework/operator-registry/LICENSE
  vendor/github.com/operator-framework/operator-registry/pkg/api/conversion.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/health.pb.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/health.proto
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.pb.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.proto
  vendor/github.com/operator-framework/operator-registry/pkg/client/client.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/bundle.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/types.go
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/internal/gcimporter/bexport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/internal/gcimporter/isAlias18.go
  vendor/golang.org/x/tools/go/internal/gcimporter/isAlias19.go
  vendor/golang.org/x/tools/go/types/typeutil/callee.go
  vendor/golang.org/x/tools/imports/fix.go
  vendor/golang.org/x/tools/imports/imports.go
  vendor/golang.org/x/tools/imports/mkstdlib.go
  vendor/golang.org/x/tools/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_namlen_bsd.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_namlen_linux.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_unix.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/semver/semver.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#629 increase memory limits on all service catalog pods
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#634 fix(charts): add operator_namespace to run-local values
  Documentation/install/local-values.yaml
Labels: approved, lgtm, size/XS

#633 Requeue subscriptions on catalogsource change
  deploy/chart/templates/0000_30_17-packageserver.subscription.yaml
  manifests/0000_30_17-packageserver.subscription.yaml
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions.go
Labels: approved, lgtm, size/S

#614 Verify CRD's condition to ensure it's registered with k8s API (rebased)
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
Labels: approved, lgtm, size/L

#636 fix(crds): remove category all from CRDs
  Documentation/design/architecture.md
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
  deploy/chart/templates/0000_30_03-installplan.crd.yaml
  deploy/chart/templates/0000_30_04-subscription.crd.yaml
  deploy/chart/templates/0000_30_05-catalogsource.crd.yaml
  deploy/chart/templates/0000_30_10-olm-operator.deployment.yaml
  deploy/chart/templates/0000_30_11-catalog-operator.deployment.yaml
  deploy/chart/templates/0000_30_13-operatorgroup.crd.yaml
  manifests/0000_30_00-namespace.yaml
  manifests/0000_30_01-olm-operator.serviceaccount.yaml
  manifests/0000_30_02-clusterserviceversion.crd.yaml
  manifests/0000_30_03-installplan.crd.yaml
  manifests/0000_30_04-subscription.crd.yaml
  manifests/0000_30_05-catalogsource.crd.yaml
  manifests/0000_30_06-rh-operators.configmap.yaml
  manifests/0000_30_07-certified-operators.configmap.yaml
  manifests/0000_30_08-certified-operators.catalogsource.yaml
  manifests/0000_30_09-rh-operators.catalogsource.yaml
  manifests/0000_30_10-olm-operator.deployment.yaml
  manifests/0000_30_11-catalog-operator.deployment.yaml
  manifests/0000_30_12-aggregated.clusterrole.yaml
  manifests/0000_30_13-operatorgroup.crd.yaml
  manifests/0000_30_14-olm-operators.configmap.yaml
  manifests/0000_30_15-olm-operators.catalogsource.yaml
  manifests/0000_30_16-operatorgroup-default.yaml
  manifests/0000_30_17-packageserver.subscription.yaml
  manifests/image-references
Labels: approved, lgtm, size/XXL

#643 test(catalog): add an e2e test verifying that the rh-operators catalog starts
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm, size/S

#641 Updated MongoDB Operator to 0.6
  deploy/chart/catalog_resources/certified-operators/mongodb-enterprise.v0.3.2.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/XS
