Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2018-11, with the labels that each got.

#541 Verify Native APIs Present for ClusterServiceVersion
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/requirements.go
  test/e2e/csv_e2e_test.go
Labels: size/M

#550 fix(olm): set lister up for deployments
  pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, size/XS

#549 Fix olm pod name so log to be written correctly to olm.log
  scripts/run_e2e_local.sh
Labels: approved, lgtm, size/XS

#517 fix(build): add cleanup for package release files
  Makefile
Labels: approved, lgtm, size/XS

#548 Add test case for supporting multi-version CRD
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, size/L

#516 feat(build): allow skipping minikube during local builds
  scripts/build_local.sh
Labels: approved, lgtm, size/XS

#537 Fix template values for 'olm' parameters
  Documentation/install/install.md
  Documentation/install/local-values-shift.yaml
Labels: approved, lgtm, size/XS

#547 Update AMQ logo to new brand standard
  deploy/chart/catalog_resources/rh-operators/amq-streams.v1.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#545 use OpenShift's ServiceCatalog build, update rbac + more
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
Labels: approved, size/L

#536 feat(csv): detect req and dep change in succeeded/failed phases
  Documentation/design/architecture.md
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/controller/certs/certs.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  pkg/lib/operatorlister/clusterserviceversion.go
  pkg/lib/operatorlister/deployment.go
  pkg/lib/operatorlister/lister.go
  pkg/lib/operatorlister/operatorgroup.go
  pkg/lib/operatorlister/role.go
  pkg/lib/operatorlister/rolebinding.go
  pkg/lib/operatorlister/secret.go
  pkg/lib/operatorlister/service.go
  pkg/lib/operatorlister/serviceaccount.go
  pkg/lib/queueinformer/queueinformer.go
  pkg/lib/queueinformer/queueinformer_operator.go
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, size/XXL

#561 Fix Go Modules
  go.mod
  go.sum
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/modules.txt
Labels: approved, lgtm

#563 Remove ns annotator
  cmd/olm/main.go
  pkg/controller/annotator/annotator.go
  pkg/controller/annotator/annotator_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, lgtm, size/XL

#569 feat(olm): use cache listers in olm-operator
  Makefile
  go.sum
  pkg/api/wrappers/deployment_install_client.go
  pkg/api/wrappers/deployment_install_client_test.go
  pkg/controller/install/resolver.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  pkg/fakes/client-go/listers/fake_v1_service_account_lister.go
  pkg/fakes/client-go/listers/fake_v1_service_account_namespace_lister.go
  pkg/fakes/fake_strategy_resolver.go
  pkg/lib/operatorlister/customresourcedefinition.go
  pkg/lib/operatorlister/lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_apiextensions_v1beta1lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_apiregistration_v1lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_apps_v1lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_core_v1lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_operator_lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_operators_v1alpha1lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_operators_v1alpha2lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_rbac_v1lister.go
  pkg/metrics/metrics.go
  scripts/generate_mocks.sh
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#568 Operator group follow ups
  deploy/chart/templates/0000_30_14-operatorgroup.crd.yaml
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/requirements.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/L

#572 fix(csv-requeue): requeue on namespace all if all namespaces are watched
  pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, size/S

#576 Propagate Labels from `CatalogSource` to `PackageManifests`
  pkg/package-server/provider/inmem.go
Labels: approved, lgtm, size/S

#592 Fix `client-go` Dependency
  go.mod
  go.sum
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
