Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2018-10, with the labels that each got.

#496 Dropping label for origin releasepayload
  Dockerfile
Labels: approved, lgtm, size/XS

#497 Add missing binary to fix run-local-shift
  e2e-local-shift.Dockerfile
Labels: approved, lgtm, size/XS

#498 Fix for Federation CSV
  deploy/chart/catalog_resources/rh-operators/federationv2.v0.0.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#500 fix 30_14-imagestream.yaml formatting
  deploy/ocp/manifests/0.7.1/30_14-imagestream.yaml
  manifests/30_14-imagestream.yaml
Labels: approved, lgtm, size/XS

#494 Always Return Global `PackageManifests`
  cmd/package-server/main.go
  deploy/chart/templates/30_13-packageserver.yaml
  pkg/package-server/provider/inmem.go
  pkg/package-server/provider/inmem_test.go
  pkg/package-server/provider/interfaces.go
  pkg/package-server/provider/provider_fake.go
  pkg/package-server/server/server.go
  pkg/package-server/storage/packagemanifest/reststorage.go
  pkg/package-server/storage/packagemanifest/watcher.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, lgtm, size/L

#499 Make use a valid clusterPermissions rule verb
  manifests/30_02-clusterserviceversion.crd.yaml
Labels: approved, lgtm, size/XS

#501 add example and additional info about optional CSV metadata (replace…
  Documentation/design/building-your-csv.md
Labels: approved, lgtm, size/M

#492 feat(csv): install owned APIServices
  Documentation/design/building-your-csv.md
  Gopkg.lock
  Makefile
  deploy/chart/catalog_resources/rh-operators/svcat.package.yaml
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/controller/certs/certs.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/registry/directory_loader_test.go
  pkg/lib/operatorclient/apiservice.go
  pkg/lib/operatorclient/client.go
  pkg/lib/operatorclient/mock_client.go
  pkg/lib/operatorclient/secret.go
  pkg/lib/operatorclient/service.go
  scripts/run_e2e_local.sh
  test/e2e/csv_e2e_test.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/apiregistration/v1beta1/interface.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/kube-aggregator/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1/expansion_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/listers/apiregistration/v1beta1/expansion_generated.go
Labels: approved, lgtm, size/XXL

#503 chore(deploy): use runlevel label on namespace
  deploy/ocp/manifests/0.7.1/0000_30_00-namespace.yaml
  deploy/ocp/manifests/0.7.1/30_00-namespace.yaml
  deploy/okd/manifests/0.7.1/0000_30_00-namespace.yaml
  deploy/okd/manifests/0.7.1/30_00-namespace.yaml
  manifests/0000_30_00-namespace.yaml
Labels: approved, lgtm, size/S

#504 fix(ci): use deployment namespace for catalog_namespace
  .gitlab-ci.jsonnet
  .gitlab-ci.yml
  .gitlab-ci/base_jobs.libsonnet
Labels: approved, lgtm, size/S

#509 chore(deploy): put all binaries in the same image
  .gitlab-ci.jsonnet
  .gitlab-ci.yml
  .gitlab-ci/base_jobs.libsonnet
  .gitlab-ci/utils.libsonnet
  .gitlab-ci/vars.libsonnet
  Dockerfile
  Documentation/install/local-values.yaml
  deploy/chart/templates/0000_30_10-olm-operator.deployment.yaml
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  deploy/okd/values.yaml
  deploy/upstream/values.yaml
  e2e.Dockerfile
  scripts/build_local.sh
  test/e2e/e2e-values-shift.yaml
  test/e2e/e2e-values.yaml
  upstream.Dockerfile
Labels: approved, lgtm, size/L

#511 Add possible nonResourceURL verbs to validation
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
Labels: approved, lgtm, size/XS

#512 bump 0.7.3
  OLM_VERSION
  ci-base.Dockerfile
  ci-manifests.Dockerfile
  ci-out.Dockerfile
Labels: approved, lgtm, size/M

#513 Rewrite Namespace when Fetching Global PackageManifests
  pkg/package-server/provider/inmem.go
  pkg/package-server/provider/inmem_test.go
Labels: approved, lgtm, size/XS

#514 fix(requirements): add support for non resource url rules
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
  pkg/controller/install/attributes_util.go
  pkg/controller/install/attributes_util_test.go
  pkg/controller/install/rule_checker.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, size/L

#519 Update OKD install instructions
  Documentation/install/install.md
Labels: approved, lgtm, size/XS

#520 More Descriptors for Couchbase Operator
  deploy/chart/catalog_resources/certified-operators/couchbase.1.0.0.clusterserviceversion.yaml
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
Labels: approved, lgtm, size/M

#521 Pass Annotations to PackageManifests
  pkg/package-server/apis/packagemanifest/v1alpha1/packagemanifest.go
  pkg/package-server/apis/packagemanifest/v1alpha1/packagemanifest_types.go
  pkg/package-server/apis/packagemanifest/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#524 fix(package-server): make secure port configurable and default to 5443
  deploy/chart/templates/0000_30_13-packageserver.yaml
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  deploy/okd/values.yaml
  deploy/upstream/values.yaml
Labels: approved, lgtm, size/S

#527 fix(e2e): switch to port 5443 for owned apiservice test
  Dockerfile
  Documentation/install/local-values.yaml
  e2e.Dockerfile
  test/e2e/csv_e2e_test.go
  upstream.Dockerfile
Labels: approved, lgtm, size/S

#526 chore(package-server): enable auth by default
  pkg/package-server/server/server.go
Labels: approved, lgtm, size/XS

#533 chore(release): bump version number to 0.7.4
  OLM_VERSION
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#528 [Doc] Add note about helm binary requirement
  Documentation/install/install.md
Labels: approved, lgtm, size/XS

#535 Add `ConfigMap` as an Owned Resource for Prometheus
  deploy/chart/catalog_resources/rh-operators/prometheusoperator.0.22.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#531 Add `assign` verb to csv crd
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
Labels: approved, lgtm, size/XS

#522 More Descriptors for Dynatrace Operator
  deploy/chart/catalog_resources/certified-operators/dynatrace-monitoring.0.2.0.clusterserviceversion.yaml
  deploy/chart/catalog_resources/certified-operators/mongodb-enterprise.v0.3.2.clusterserviceversion.yaml
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
Labels: approved, lgtm, size/M

#525 feat(csv): add cert rotation for owned APIServices
  .gitlab-ci.yml
  .gitlab-ci/base_jobs.libsonnet
  deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/certs/certs.go
  pkg/controller/install/rule_checker.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/requirements.go
  pkg/lib/operatorclient/apiservice.go
  pkg/lib/operatorlister/apiservice.go
  pkg/lib/operatorlister/clusterrole.go
  pkg/lib/operatorlister/clusterrolebinding.go
  pkg/lib/operatorlister/deployment.go
  pkg/lib/operatorlister/lister.go
  pkg/lib/operatorlister/namespace.go
  pkg/lib/operatorlister/role.go
  pkg/lib/operatorlister/rolebinding.go
  pkg/lib/operatorlister/secret.go
  pkg/lib/operatorlister/service.go
  pkg/lib/operatorlister/serviceaccount.go
  pkg/lib/ownerutil/util.go
  pkg/lib/queueinformer/queueinformer_operator.go
  pkg/package-server/generated/openapi/zz_generated.openapi.go
  scripts/build_local.sh
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, size/XXL
