Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2018-09, with the labels that each got.

#465 All Namespaces Support for PackageManifest API
  pkg/package-server/provider/inmem.go
  pkg/package-server/provider/inmem_test.go
  pkg/package-server/server/server.go
Labels: approved, lgtm, size/L

#466 Documentation: Change to full path
  Documentation/install/install.md
Labels: approved, lgtm, size/XS

#457 [WIP] feat(catalog): add RBAC step resolution
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/api/apis/operators/v1alpha1/register.go
  pkg/controller/install/deployment.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/lib/operatorclient/client.go
  pkg/lib/operatorclient/mock_client.go
  pkg/lib/operatorclient/role.go
  pkg/lib/operatorclient/rolebinding.go
  pkg/lib/ownerutil/util.go
  test/e2e/catalog_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, lgtm, size/XXL

#459 feat(olm): support depending on APIservices
  Gopkg.lock
  Gopkg.toml
  deploy/chart/templates/03-clusterserviceversion.crd.yaml
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/errors/errors.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/lib/operatorclient/client.go
  pkg/lib/operatorclient/mock_client.go
  pkg/package-server/generated/openapi/zz_generated.openapi.go
  test/e2e/csv_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/subscription_e2e_test.go
  vendor/k8s.io/kube-aggregator/LICENSE
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/helpers.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/clientset.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/register.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/fake/fake_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/generated_expansion.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiregistration_client.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiservice.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/generated_expansion.go
Labels: approved, lgtm, size/XXL

#470 Issue #469 update the service catalog instruction for minishift.
  scripts/build_local_shift.sh
Labels: approved, lgtm, size/XS

#472 0.7.0 packages api
  Makefile
  deploy/okd/manifests/0.7.0/22-packageserver.yaml
  deploy/okd/values.yaml
  deploy/upstream/manifests/0.7.0/22-packageserver.yaml
  deploy/upstream/values.yaml
Labels: approved, lgtm, size/M

#474 feat(ci): push tags to quay
  .gitlab-ci.jsonnet
  .gitlab-ci.yml
  .gitlab-ci/vars.libsonnet
Labels: approved, lgtm, size/M

#477 Allow resolving ClusterRoles
  deploy/chart/templates/30_02-clusterserviceversion.crd.yaml
  deploy/ocp/manifests/0.7.1/30_13-packageserver.yaml
  deploy/okd/manifests/0.7.1/30_13-packageserver.yaml
  deploy/upstream/manifests/0.7.1/30_00-namespace.yaml
  deploy/upstream/manifests/0.7.1/30_01-olm-operator.serviceaccount.yaml
  deploy/upstream/manifests/0.7.1/30_06-rh-operators.configmap.yaml
  deploy/upstream/manifests/0.7.1/30_09-rh-operators.catalogsource.yaml
  deploy/upstream/manifests/0.7.1/30_10-olm-operator.deployment.yaml
  deploy/upstream/manifests/0.7.1/30_11-catalog-operator.deployment.yaml
  deploy/upstream/manifests/0.7.1/30_13-packageserver.yaml
  deploy/upstream/values.yaml
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/api/apis/operators/v1alpha1/register.go
  pkg/api/wrappers/deployment_install_client.go
  pkg/api/wrappers/wrappersfakes/fake_install_strategy_deployment_interface.go
  pkg/controller/install/deployment.go
  pkg/controller/install/deployment_test.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/steps.go
  pkg/fakes/fake_deployment_install_client.go
  pkg/lib/operatorclient/client.go
  pkg/lib/operatorclient/clusterrolebinding.go
  pkg/lib/operatorclient/mock_client.go
  pkg/lib/ownerutil/util.go
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, lgtm, size/XXL

#478 certified-operators: rectify form of business for Dynatrace
  deploy/chart/catalog_resources/certified-operators/dynatrace-monitoring.0.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#486 fix(deploy): yaml error in imagereferences
  deploy/chart/templates/image-references
  deploy/ocp/manifests/0.7.1/image-references
  manifests/image-references
Labels: approved, lgtm, size/S

#487 Revert "fix(deploy): remove package-server until ci-operator is outpu…
  deploy/chart/templates/image-references
  deploy/ocp/manifests/0.7.1/image-references
  manifests/image-references
Labels: approved, lgtm, size/S

#482 refine cluster-admin OLM workflow
  Documentation/design/access-control.md
Labels: approved, lgtm, size/S

#489 change go build to use 1.10
  Dockerfile
Labels: approved, lgtm, size/XS

#490 fix(build): don't vendor
  upstream.Dockerfile
Labels: approved, lgtm, size/XS

#476 Implement Watch for `PackageManifest` API
  deploy/chart/templates/30_13-packageserver.yaml
  pkg/package-server/generated/openapi/zz_generated.openapi.go
  pkg/package-server/provider/inmem.go
  pkg/package-server/provider/inmem_test.go
  pkg/package-server/provider/interfaces.go
  pkg/package-server/provider/provider_fake.go
  pkg/package-server/server/server.go
  pkg/package-server/storage/packagemanifest/reststorage.go
  pkg/package-server/storage/packagemanifest/watcher.go
  pkg/package-server/storage/packagemanifest/watcher_test.go
Labels: approved, lgtm, size/XL
