Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2018-08, with the labels that each got.

#420 Set Status on Subscription with Invalid Catalog Source
  pkg/api/apis/operators/v1alpha1/subscription_types.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions.go
Labels: internal/tracked

#426 Action Descriptors
  deploy/chart/templates/03-clusterserviceversion.crd.yaml
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement

#425 updated prometheus csv according to the integration into openshift
  deploy/chart/catalog_resources/ocs/prometheusoperator.0.22.2.clusterserviceversion.yaml
Labels: ok-to-test

#431 Instructions for Running OLM UI
  README.md
  scripts/run_console_local.sh
Labels: enhancement, internal/tracked
