Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-08, with the labels that each got.

#971 Bug 1727032 Report `Upgradeable` in ClusterOperator status
  pkg/lib/operatorstatus/status.go
Labels: approved, lgtm, size/S

#968 (doc) update new release doc
  Documentation/design/release.md
Labels: approved, lgtm, size/M

#969 (doc) add doc for scoped operator install
  Documentation/design/scoped-operator-install.md
Labels: approved, lgtm, size/L

#960 Bug 1717636: Add relatedObjects to cluster operator status
  cmd/catalog/main.go
  cmd/olm/main.go
  pkg/lib/operatorstatus/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#987 fix(deploy): change local deploy to use olm namespace
  Documentation/install/install.md
  Documentation/install/local-values.yaml
  Makefile
  README.md
  pkg/controller/install/attributes_util_test.go
Labels: approved, lgtm, size/M

#974 Bug 1737081: catsrc status should show error
  Makefile
  cmd/olm/cleanup.go
  pkg/api/apis/operators/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/api/apis/operators/zz_generated.deepcopy.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/grpc/source.go
  pkg/controller/registry/grpc/source_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_address.go
  pkg/fakes/fake_registry_store.go
  pkg/lib/queueinformer/queueinformer_operator.go
  scripts/build_local.sh
  scripts/run_e2e_bare.sh
  scripts/run_e2e_local.sh
  test/e2e/catalog_e2e_test.go
  test/e2e/chart/templates/job.yaml
  test/e2e/csv_e2e_test.go
  test/e2e/hang.Dockerfile
  test/e2e/installplan_e2e_test.go
  test/e2e/setup_bare_test.go
  test/e2e/setup_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
  test/e2e/wait/main.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#985 Proposal for PackageManifest Icon Subresource
  Documentation/contributors/design-proposals/operator-logos.md
Labels: approved, lgtm, size/M

#964 Bug 1732214: Fix panic when binding already exists
  pkg/controller/operators/catalog/operator.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#990 Bug 1727800: Icon Subresource for PackageManifest
  Documentation/contributors/design-proposals/operator-logos.md
  pkg/package-server/apis/operators/packagemanifest.go
  pkg/package-server/apiserver/generic/storage.go
  pkg/package-server/provider/interfaces.go
  pkg/package-server/storage/subresources.go
  pkg/package-server/storage/subresources_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#977 Bug 1740174: fix(catalog): re-install resources in existing installplan
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#1001 Bug 1744245: fix e2e failure
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#924 Operator validation library project proposal
  Documentation/contributors/design-proposals/operator-validation-library.md
Labels: approved, lgtm, proposal, size/L

#939 (proposal) improved csv status reporting
  Documentation/contributors/design-proposals/csv-status.md
Labels: lgtm, proposal, size/L

#970 Bug 1743345: clean up service account, cluster roles, and cluster role bindings after CSV deletion
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/rbac.go
  pkg/lib/queueinformer/config.go
  pkg/lib/queueinformer/queueinformer.go
  pkg/lib/queueinformer/queueinformer_operator.go
  pkg/lib/queueinformer/resourcequeue.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#973 Bug 1732914: Operator upgrades fail when versions field is not set
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  test/e2e/installplan_e2e_test.go
Labels: CRD Versioning, approved, bugzilla/valid-bug, lgtm, size/L

#980 Bug 1702552: Two "NAME" fields by command "oc get catalogsource"
  deploy/chart/templates/0000_50_olm_06-catalogsource.crd.yaml
  manifests/0000_50_olm_06-catalogsource.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#998 Bug 1741475: test(e2e): Update permissions during operator upgrade
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1002 Bug 1727800: Remove Icon from `PackageManifest` Resource
  pkg/package-server/storage/reststorage.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1005 Bug 1744490: Add RBAC for PackageManifest Icon Subresource
  deploy/chart/templates/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#976 Bug 1737156: feat(metrics): record sync count for Subscriptions, labeled with name and installedCSV
  Makefile
  pkg/controller/operators/catalog/operator.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1006 Bug 1740332: OLM should resume operator install
  pkg/api/apis/operators/installplan_types.go
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/api/apis/operators/zz_generated.deepcopy.go
  pkg/controller/operators/catalog/installplan_sync.go
  pkg/controller/operators/catalog/operator.go
  pkg/lib/scoped/attenuator.go
  test/e2e/user_defined_sa_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1008 Bug 1745626: Update GRPC libs
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/lib/time/shared.go
  pkg/lib/time/shared_test.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.proto
  vendor/google.golang.org/grpc/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/flowcontrol.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/reflection/README.md
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.proto
  vendor/google.golang.org/grpc/reflection/serverreflection.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#978 Bug 1737057: Sub CRD does not validate config
  deploy/chart/templates/0000_50_olm_05-subscription.crd.yaml
  manifests/0000_50_olm_05-subscription.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#989 Bug 1727042: feat(operatorstatus): report packageserver as upgradeable
  pkg/lib/operatorstatus/builder.go
  pkg/lib/operatorstatus/builder_test.go
  pkg/lib/operatorstatus/csv_reporter.go
  pkg/lib/operatorstatus/csv_reporter_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1012 Bug 1717638 fix(olm): report name and group for related objects
  pkg/lib/operatorstatus/status.go
Labels: approved, lgtm, size/XS

#1014 [CatalogSource] Set Global Catalog NS with EnvVar
  Documentation/install/install.md
  cmd/catalog/main.go
Labels: approved, lgtm, size/S

#1011 Stop relying on pgrep -q
  scripts/build_local.sh
Labels: approved, lgtm, size/XS
