Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-04, with the labels that each got.

#741 docs(subscriptions): add improved sub status proposal
  Documentation/contributors/design-proposals/subscription-status.md
Labels: approved, docs, lgtm, proposal, size/XL

#801 Bump OLM Release Version to 0.9.0
  OLM_VERSION
Labels: approved, lgtm, size/XS

#810 docs(changelog): regenerate changelog for 0.9.0
  CHANGELOG.md
  Documentation/design/release.md
Labels: approved, size/M

#794 fix(olm): generate aggregated clusterroles for ownnamespace operatorgroups correctly
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  scripts/build_local.sh
  test/e2e/catalog_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, size/L

#809 add logging and separate muxer for metrics
  cmd/catalog/main.go
  cmd/olm/main.go
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  test/e2e/metrics_e2e_test.go
Labels: approved, lgtm, size/M

#759 fix(deployment): Clean up orphaned deployments
  Makefile
  pkg/api/wrappers/deployment_install_client.go
  pkg/api/wrappers/wrappersfakes/fake_install_strategy_deployment_interface.go
  pkg/controller/install/deployment.go
  pkg/controller/install/deployment_test.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, kind/bug, lgtm, size/XL

#811 chore(cvo): report progressing=true if the version has updated
  pkg/lib/operatorstatus/status.go
Labels: approved, lgtm, size/S

#812 feat(rbac): restrict permissions for namespace admins
  deploy/chart/templates/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
Labels: approved, lgtm, size/S

#820 Subscription Status InstallPlan References
  pkg/api/apis/operators/reference.go
  pkg/api/apis/operators/reference_test.go
  pkg/api/apis/operators/register.go
  pkg/api/apis/operators/v1/operatorgroup_types.go
  pkg/api/apis/operators/v1/register.go
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/api/apis/operators/v1alpha1/register.go
  pkg/api/apis/operators/v1alpha1/subscription_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/api/client/clientset/versioned/fake/decorator.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/lib/queueinformer/queueinformer_operator.go
Labels: approved, lgtm, size/XL

#823 chore(cvo): update openshift/api so that OperatorFailing is changed to OperatorDegraded
  go.mod
  go.sum
  pkg/lib/operatorstatus/status.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#817 Add priorityClassName
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_11-olm-operators.configmap.yaml
  manifests/0000_50_olm_16-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_17-packageserver.deployment.yaml
Labels: approved, lgtm, size/M

#826 chore(cvo): remove ClusterOperator from manifests
  deploy/chart/templates/0000_50_olm_15-operatorstatus.yaml
  manifests/0000_50_olm_15-operatorstatus.yaml
Labels: approved, size/M

#824 Add node-selector annotation to namespace
  deploy/chart/templates/0000_50_olm_00-namespace.yaml
  deploy/ocp/manifests/0.7.1/0000_30_00-namespace.yaml
  deploy/ocp/manifests/0.7.2/0000_30_00-namespace.yaml
  deploy/ocp/manifests/0.7.4/0000_30_00-namespace.yaml
  deploy/ocp/manifests/0.8.1/0000_50_olm_00-namespace.yaml
  deploy/ocp/manifests/0.9.0/0000_50_olm_00-namespace.yaml
  deploy/okd/manifests/0.7.2/0000_30_00-namespace.yaml
  deploy/okd/manifests/0.8.0/0000_30_00-namespace.yaml
  deploy/okd/manifests/0.9.0/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-namespace.yaml
Labels: approved, lgtm, size/M

#828 Revert "chore(cvo): remove ClusterOperator from manifests"
  deploy/chart/templates/0000_50_olm_15-operatorstatus.yaml
  manifests/0000_50_olm_15-operatorstatus.yaml
Labels: approved, size/M

#830 Always set LastTransitionTime in OperatorStatusCondition
  pkg/lib/operatorstatus/status.go
Labels: approved, lgtm, size/XS
