Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-12, with the labels that each got.

#1123 Bug 1769030: Replacing operator creates duplicate secrets
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step_ensurer.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1151 bug 1771811: make certificate updates live upon update
  cmd/catalog/main.go
  cmd/olm/main.go
  go.mod
  go.sum
  pkg/lib/filemonitor/cert_updater.go
  pkg/lib/filemonitor/cert_updater_test.go
  pkg/lib/filemonitor/testdata/ca.crt
  pkg/lib/filemonitor/testdata/cert-config/Makefile
  pkg/lib/filemonitor/testdata/cert-config/csr-new.conf
  pkg/lib/filemonitor/testdata/cert-config/csr-old.conf
  pkg/lib/filemonitor/testdata/cert-config/gen-certs.sh
  pkg/lib/filemonitor/testdata/server-new.crt
  pkg/lib/filemonitor/testdata/server-new.key
  pkg/lib/filemonitor/testdata/server-old.crt
  pkg/lib/filemonitor/testdata/server-old.key
  pkg/lib/filemonitor/watcher.go
  vendor/github.com/fsnotify/fsnotify/.editorconfig
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#1125 Bug 1779313: Enable multiple namespaces sync if catsrc is updated in global ns
  pkg/controller/operators/catalog/operator.go
  pkg/lib/index/catalog.go
  test/e2e/catalog_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1175 BUG: Fix CI Unit tests.
  Makefile
Labels: approved, lgtm, size/XS

#1150 Bug 1779990: fix(packageserver): cache packagemanifests
  .gitignore
  cmd/package-server/apiserver.local.config/certificates/apiserver.crt
  cmd/package-server/apiserver.local.config/certificates/apiserver.key
  cmd/package-server/main.go
  go.mod
  go.sum
  pkg/lib/event/event.go
  pkg/lib/operatorclient/apiservice.go
  pkg/lib/operatorclient/clusterrole.go
  pkg/lib/operatorclient/clusterrolebinding.go
  pkg/lib/operatorclient/customresources.go
  pkg/lib/operatorclient/deployment.go
  pkg/lib/operatorclient/role.go
  pkg/lib/operatorclient/rolebinding.go
  pkg/lib/operatorclient/secret.go
  pkg/lib/operatorclient/service.go
  pkg/lib/operatorclient/serviceaccount.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
  pkg/package-server/provider/testdata/manifests/etcd/0.6.1/etcdcluster.crd.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.6.1/etcdoperator.clusterserviceversion.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.9.0/etcdbackup.crd.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.9.0/etcdcluster.crd.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.9.0/etcdoperator.v0.9.0.clusterserviceversion.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.9.0/etcdrestore.crd.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.9.2/etcdbackup.crd.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.9.2/etcdcluster.crd.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml
  pkg/package-server/provider/testdata/manifests/etcd/0.9.2/etcdrestore.crd.yaml
  pkg/package-server/provider/testdata/manifests/etcd/etcd.package.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.14.0/alertmanager.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.14.0/prometheus.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.14.0/prometheusoperator.0.14.0.clusterserviceversion.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.14.0/prometheusrule.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.14.0/servicemonitor.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.15.0/alertmanager.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.15.0/prometheus.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.15.0/prometheusoperator.0.15.0.clusterserviceversion.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.15.0/prometheusrule.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.15.0/servicemonitor.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.22.2/alertmanager.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.22.2/prometheus.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.22.2/prometheusrule.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/0.22.2/servicemonitor.crd.yaml
  pkg/package-server/provider/testdata/manifests/prometheus/prometheus.package.yaml
  pkg/package-server/server/server.go
  test/e2e/setup_test.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#1187 Dep is not required.
  DEVELOPMENT.md
Labels: kind/documentation, needs-ok-to-test, size/XS

#1183 Bug 1668853: update 21-aggregated-view.clusterrole.yaml
  deploy/upstream/manifests/0.6.0/21-aggregated-view.clusterrole.yaml
Labels: lgtm, size/XS

#1176 docs - add a mention of bundles to the README to help users find bundle info…
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1163 Added `keywords` in operator metadata.
  doc/design/building-your-csv.md
Labels: approved, kind/documentation, lgtm, needs-ok-to-test, size/S

#1192 Corrected etcd CRD URL.
  README.md
Labels: approved, kind/documentation, lgtm, needs-ok-to-test, size/XS

#1194 Bug 1781366: feat(resolver): fallback to csv parsing if grcp api does not contain info
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/operators_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1152 Add general design goals doc
  doc/design/design-goals.md
Labels: approved, kind/documentation, lgtm, size/S

#1169 [release-4.2] Bug 1749031: Enable multiple namespaces sync if catsrc is updated in global ns
  pkg/controller/operators/catalog/operator.go
  pkg/lib/index/catalog.go
  test/e2e/catalog_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#1207 fix(deploy): remove resource limits
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#1185 Add note for version field
  doc/design/dependency-resolution.md
Labels: lgtm, needs-ok-to-test, size/S

#1105 Use the grpc response as the source of truth for update graph data
  go.mod
  go.sum
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/operators_test.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.pb.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.proto
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/bundlereader.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/command.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/bundle.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/types.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/directory.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/image.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/000_init.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/001_related_images.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/002_bundle_path.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/003_required_apis.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/004_cascade_delete.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/005_version_skiprange.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrations/migrations.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/migrator.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/remove.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1154 fix: make run_console_local.sh working on WSLv1
  scripts/run_console_local.sh
Labels: approved, lgtm, ok-to-test, size/M

#1173 fix: add err check before further operation
  pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, ok-to-test, size/XS
