Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-01, with the labels that each got.

#647 Add Metering Operator to catalog
  deploy/chart/catalog_resources/rh-operators/metering-operator.v0.12.0.clusterserviceversion.yaml
  deploy/chart/catalog_resources/rh-operators/metering.crd.yaml
  deploy/chart/catalog_resources/rh-operators/metering.package.yaml
  deploy/chart/catalog_resources/rh-operators/prestotable.crd.yaml
  deploy/chart/catalog_resources/rh-operators/report.crd.yaml
  deploy/chart/catalog_resources/rh-operators/reportdatasource.crd.yaml
  deploy/chart/catalog_resources/rh-operators/reportgenerationquery.crd.yaml
  deploy/chart/catalog_resources/rh-operators/reportprometheusquery.crd.yaml
  deploy/chart/catalog_resources/rh-operators/storagelocation.crd.yaml
  manifests/0000_30_06-rh-operators.configmap.yaml
Labels: approved, lgtm, size/XL

#649 update Service Catalog memory & cpu limits
  deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
  manifests/0000_30_06-rh-operators.configmap.yaml
Labels: approved, lgtm, size/S

#651 Remove operatorsource installation
  deploy/chart/catalog_resources/rh-operators/marketplace-catalogsourceconfig.crd.yaml
  deploy/chart/catalog_resources/rh-operators/marketplace-operatorsource.crd.yaml
  deploy/chart/catalog_resources/rh-operators/marketplace.package.yaml
  deploy/chart/catalog_resources/rh-operators/marketplace.v0.0.1.clusterserviceversion.yaml
  deploy/chart/templates/0000_30_18-operatorsource.crd.yaml
  deploy/chart/templates/0000_30_19-operatorsource-default.yaml
  deploy/ocp/manifests/0.8.0/0000_30_18-operatorsource.crd.yaml
  deploy/ocp/manifests/0.8.0/0000_30_19-operatorsource-default.yaml
  deploy/okd/manifests/0.8.0/0000_30_18-operatorsource.crd.yaml
  deploy/okd/manifests/0.8.0/0000_30_19-operatorsource-default.yaml
  deploy/upstream/manifests/0.8.0/0000_30_18-operatorsource.crd.yaml
  deploy/upstream/manifests/0.8.0/0000_30_19-operatorsource-default.yaml
  manifests/0000_30_18-operatorsource.crd.yaml
  manifests/0000_30_19-operatorsource-default.yaml
  pkg/controller/registry/directory_loader_test.go
Labels: approved, lgtm, size/XL

#654 chore(ci): remove ci checks for PRs
  .gitlab-ci.jsonnet
  .gitlab-ci.yml
  .gitlab-ci/base_jobs.libsonnet
Labels: approved, lgtm, size/L

#657 Watch all namespaces in local setup by removing watchedNamespaces in local-values
  Documentation/install/local-values.yaml
Labels: approved, lgtm, size/XS

#658 Update metering InstallModes to support SingleNamespace
  deploy/chart/catalog_resources/rh-operators/metering-operator.v0.12.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#665 fix(operatorgroups): use copied csv for update status
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/S

#653 fix(deploy): add linux nodeselector
  deploy/chart/templates/_packageserver.clusterserviceversion.yaml
  deploy/chart/values.yaml
  manifests/0000_30_00-namespace.yaml
  manifests/0000_30_01-olm-operator.serviceaccount.yaml
  manifests/0000_30_02-clusterserviceversion.crd.yaml
  manifests/0000_30_03-installplan.crd.yaml
  manifests/0000_30_04-subscription.crd.yaml
  manifests/0000_30_05-catalogsource.crd.yaml
  manifests/0000_30_06-rh-operators.configmap.yaml
  manifests/0000_30_07-certified-operators.configmap.yaml
  manifests/0000_30_08-certified-operators.catalogsource.yaml
  manifests/0000_30_09-rh-operators.catalogsource.yaml
  manifests/0000_30_10-olm-operator.deployment.yaml
  manifests/0000_30_11-catalog-operator.deployment.yaml
  manifests/0000_30_12-aggregated.clusterrole.yaml
  manifests/0000_30_13-operatorgroup.crd.yaml
  manifests/0000_30_14-olm-operators.configmap.yaml
  manifests/0000_30_15-olm-operators.catalogsource.yaml
  manifests/0000_30_16-operatorgroup-default.yaml
  manifests/0000_30_17-packageserver.subscription.yaml
  manifests/image-references
Labels: approved, size/L

#637 fix(metrics): remove resources that aren't updated
  cmd/catalog/main.go
  cmd/olm/main.go
  go.mod
  go.sum
  pkg/metrics/metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#667 fix(packageserver): don't error out when listing
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
Labels: approved, lgtm, size/L

#672 test(validation): add test to verify OLM can use bundles with CRDs with min/max fields
  go.mod
  go.sum
  test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/bundle.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#670 test(catalog): add e2e test to verify configmap changes are detected
  Makefile
  deploy/chart/templates/0000_30_05-catalogsource.crd.yaml
  e2e.Dockerfile
  go.mod
  go.sum
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/configmap_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/resolver/querier.go
  pkg/fakes/fake_reconciler.go
  pkg/fakes/fake_reconciler_reconciler.go
  pkg/lib/queueinformer/resourcequeue.go
  scripts/build_local.sh
  scripts/run_e2e_docker.sh
  scripts/run_e2e_local.sh
  test/e2e/catalog_e2e_test.go
  test/e2e/chart/templates/job.yaml
  test/e2e/e2e-values-shift.yaml
  test/e2e/e2e-values.yaml
  test/e2e/util_test.go
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/k8s.io/api/extensions/v1beta1/generated.proto
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/api/extensions/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#679 fix(installplan): fix bug where too many installplans can be created
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/resolver/resolver.go
  pkg/lib/operatorlister/installplan.go
  pkg/lib/operatorlister/lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_operators_v1alpha1lister.go
  pkg/lib/queueinformer/loop_id.go
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm, size/XL

#681 Ensure Owner References on ConfigMaps for CatalogSources
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/lib/ownerutil/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#685 Correct URL for Package Server CSV Link
  deploy/chart/templates/_packageserver.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#689 fix(subscriptions): fix race between subscription sync and cache
  Makefile
  go.mod
  go.sum
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/lib/operatorclient/mock_client.go
  test/e2e/installplan_e2e_test.go
  test/e2e/util_test.go
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#688 fix(reconciler): set command in pod spec of registry images
  README.md
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/registry/reconciler/configmap.go
  vendor/k8s.io/client-go/pkg/version/base.go
Labels: approved, lgtm, size/L

#676 fix(subscriptions): respect startingCSV
  Makefile
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
  pkg/controller/registry/resolver/fakes/fake_registry_client.go
  pkg/controller/registry/resolver/generation.go
  pkg/controller/registry/resolver/generation_test.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/operators_test.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/util_test.go
  pkg/package-server/client/fakes/fake_registry_client.go
  pkg/package-server/provider/registry_test.go
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.pb.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/registry.proto
  vendor/github.com/operator-framework/operator-registry/pkg/client/client.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/server/server.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#695 Fix README.md links for CRDs, Descriptor, and Package
  README.md
Labels: approved, lgtm, ok-to-test

#691 chore(modules): update operator-registry module to v1.0.6
  go.mod
  go.sum
  vendor/github.com/coreos/etcd/version/version.go
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/procfs/MAINTAINERS.md
  vendor/github.com/ugorji/go/LICENSE
  vendor/github.com/ugorji/go/codec/0doc.go
  vendor/github.com/ugorji/go/codec/README.md
  vendor/github.com/ugorji/go/codec/binc.go
  vendor/github.com/ugorji/go/codec/build.sh
  vendor/github.com/ugorji/go/codec/cbor.go
  vendor/github.com/ugorji/go/codec/codecgen.go
  vendor/github.com/ugorji/go/codec/decode.go
  vendor/github.com/ugorji/go/codec/encode.go
  vendor/github.com/ugorji/go/codec/fast-path.generated.go
  vendor/github.com/ugorji/go/codec/fast-path.go.tmpl
  vendor/github.com/ugorji/go/codec/gen-helper.generated.go
  vendor/github.com/ugorji/go/codec/gen-helper.go.tmpl
  vendor/github.com/ugorji/go/codec/gen.go
  vendor/github.com/ugorji/go/codec/go.mod
  vendor/github.com/ugorji/go/codec/helper.go
  vendor/github.com/ugorji/go/codec/helper_not_unsafe.go
  vendor/github.com/ugorji/go/codec/helper_unsafe.go
  vendor/github.com/ugorji/go/codec/json.go
  vendor/github.com/ugorji/go/codec/msgpack.go
  vendor/github.com/ugorji/go/codec/rpc.go
  vendor/github.com/ugorji/go/codec/simple.go
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
