Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-10, with the labels that each got.

#1049 [release-4.1] Bug 1755646: Cleanup leftover cross-namespace OwnerReferences
  Makefile
  cmd/olm/cleanup.go
  cmd/olm/cleanup_test.go
  cmd/olm/main.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/util_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#1052 Bump openshift/client-go version
  go.mod
  go.sum
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1056 Bug: Fix olm chart
  deploy/chart/templates/e2e-local-01-openshift-config-proxy-crd.yaml
Labels: approved, lgtm, size/XS

#1055 feat(metrics) record CSV failures
  pkg/controller/operators/olm/operator.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
Labels: approved, lgtm, size/M

#1062 bug(install) Fix packageserver name in install.sh
  deploy/upstream/quickstart/install.sh
  scripts/install.sh
Labels: approved, lgtm, size/XS

#1065 Fix links to console repo for moved packages
  doc/design/building-your-csv.md
Labels: lgtm, size/XS

#1067 Add `apk upgrade` to upstream builder
  upstream.Dockerfile
Labels: approved, lgtm, size/XS

#1058 feat(subscription) Config Volume and VolumeMounts
  deploy/chart/templates/0000_50_olm_05-subscription.crd.yaml
  deploy/ocp/manifests/0.12.0/0000_50_olm_05-subscription.crd.yaml
  deploy/upstream/manifests/0.12.0/0000_50_olm_05-subscription.crd.yaml
  deploy/upstream/quickstart/crds.yaml
  doc/design/subscription-config.md
  manifests/0000_50_olm_05-subscription.crd.yaml
  pkg/api/apis/operators/subscription_types.go
  pkg/api/apis/operators/v1alpha1/subscription_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/api/apis/operators/zz_generated.deepcopy.go
  pkg/controller/install/deployment.go
  pkg/controller/install/resolver.go
  pkg/controller/operators/olm/envvar/inject.go
  pkg/controller/operators/olm/envvar/inject_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/overrides/config.go
  pkg/controller/operators/olm/overrides/initializer.go
  pkg/controller/operators/olm/overrides/inject.go
  pkg/controller/operators/olm/overrides/inject_test.go
  pkg/package-server/provider/manifests/prometheus/0.14.0/alertmanager.crd.yaml
  pkg/package-server/provider/manifests/prometheus/0.14.0/prometheus.crd.yaml
  pkg/package-server/provider/manifests/prometheus/0.15.0/alertmanager.crd.yaml
  pkg/package-server/provider/manifests/prometheus/0.15.0/prometheus.crd.yaml
  pkg/package-server/provider/manifests/prometheus/0.22.2/alertmanager.crd.yaml
  pkg/package-server/provider/manifests/prometheus/0.22.2/prometheus.crd.yaml
  test/e2e/subscription_e2e_test.go
  vendor/k8s.io/code-generator/generate_internal_groups.sh
  vendor/k8s.io/code-generator/hack/boilerplate.go.txt
Labels: approved, lgtm, size/XXL

#1059 Bug 1758008: Manual approval strategy ignored for subsequent releases
  pkg/controller/operators/catalog/operator.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1069 Proposal: RelatedImages
  doc/contributors/design-proposals/related-images.md
Labels: approved, size/L

#1079 Update Owners
  OWNERS
Labels: approved, lgtm, size/XS

#1043 Bug 1740857: Backport grpc sourcemanager to 4.1
  Makefile
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/registry/grpc/source.go
  pkg/controller/registry/grpc/source_test.go
  pkg/fakes/fake_registry_store.go
  pkg/lib/time/shared.go
  pkg/lib/time/shared_test.go
  scripts/build_local.sh
  scripts/run_e2e_bare.sh
  scripts/run_e2e_local.sh
  test/e2e/chart/templates/job.yaml
  test/e2e/csv_e2e_test.go
  test/e2e/hang.Dockerfile
  test/e2e/installplan_e2e_test.go
  test/e2e/setup_bare_test.go
  test/e2e/setup_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/wait/main.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#1054 [WIP] (proposal) Make bundle accessible to a cluster
  doc/contributors/design-proposals/pull-bundle-on-a-cluster.md
Labels: do-not-merge/work-in-progress, lgtm, size/L

#1071 bugfix: assignment to nil map will cause panic
  pkg/lib/operatorlister/deployment.go
Labels: approved, lgtm, ok-to-test, size/XS

#1078 Bug 1761924: Update PackageManifest table handler
  pkg/package-server/storage/printer.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1080 Bug 1762769: Prioritize APIs from same CatSrc
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/user_defined_sa_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1086 fix: fix particular typo in clusterserviceversion_types.go
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
Labels: approved, lgtm, size/XS

#1085 Fix log message in resolver
  pkg/controller/registry/resolver/resolver.go
Labels: approved, lgtm, size/XS

#1092 fix: refresh architecture and philosophy docs for clarity purposes
  doc/design/architecture.md
  doc/design/philosophy.md
Labels: approved, lgtm, size/S

#1089 Updated values.yaml location.
  doc/install/install.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#1094 fix(olm): No longer report status if minKubeVersion not specified
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
Labels: approved, lgtm, size/L

#1095 docs: Corrected CSV upgrade version.
  doc/design/how-to-update-operators.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#1099 feat(metrics) Limit Cardinality of CSV metrics
  pkg/controller/operators/olm/operator.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
Labels: approved, lgtm, size/M
