Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-05, with the labels that each got.

#833 test(e2e): wait for deployment to exist in csv replacement test
  deploy/chart/templates/0000_50_olm_09-aggregated.clusterrole.yaml
  pkg/controller/operators/olm/operator.go
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, size/M

#827 fix(olm): Fix the issue with missing events due to rate limit
  pkg/controller/operators/olm/operator.go
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, size/L

#766 fix the labels.provider of packagemanifest issue
  pkg/package-server/provider/registry.go
Labels: approved, kind/bug, lgtm, size/XS

#834 Support semver ranges of versions to skip in the head of a channel
  Makefile
  go.mod
  go.sum
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/generation.go
  pkg/controller/registry/resolver/generation_test.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/operators_test.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/util_test.go
  pkg/lib/version/version.go
  pkg/lib/version/version_test.go
  pkg/package-server/apis/apps/v1alpha1/packagemanifest_types.go
  pkg/package-server/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/package-server/apis/openapi/zz_generated.openapi.go
  pkg/package-server/apis/operators/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/zz_generated.deepcopy.go
  pkg/package-server/apis/operators/zz_generated.deepcopy.go
  pkg/version/version.go
  test/e2e/catalog_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/subscription_e2e_test.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/k8s.io/code-generator/generate_groups.sh
  vendor/k8s.io/code-generator/generate_internal_groups.sh
  vendor/k8s.io/code-generator/hack/boilerplate.go.txt
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#836 Set limit on length of Status.Conditions of a csv
  pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_test.go
Labels: approved, lgtm, size/L

#838 fix(resolver): fixes a bug where resolved dependent subscriptions don't
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/operators_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/steps.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm, size/XL

#816 Update catalog if image changes
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/requirements.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm, size/XL

#843 Fix tolerations
  Documentation/install/local-values.yaml
  deploy/ocp/values.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_16-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_17-packageserver.deployment.yaml
Labels: approved, lgtm, size/M

#845 fix(deploy): add missing descriptions
  deploy/chart/templates/0000_50_olm_03-clusterserviceversion.crd.yaml
  deploy/chart/templates/0000_50_olm_04-installplan.crd.yaml
  deploy/chart/templates/0000_50_olm_05-subscription.crd.yaml
  deploy/chart/templates/0000_50_olm_06-catalogsource.crd.yaml
  deploy/chart/templates/0000_50_olm_10-operatorgroup.crd.yaml
Labels: approved, lgtm, size/XS

#844 Add Termination Message to Failing OLM Pods
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_16-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_17-packageserver.deployment.yaml
Labels: approved, lgtm, size/XS

#847 fix(catalog): fix issue where subscriptions sometimes get "stuck"
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/e2e-values.yaml
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm, size/M

#850 Bug 1705649: fix olm-operators tolerations
  manifests/0000_50_olm_11-olm-operators.configmap.yaml
Labels: approved, lgtm, size/S

#848 fix(deploy): add missing descriptions to manifests
  manifests/0000_50_olm_03-clusterserviceversion.crd.yaml
  manifests/0000_50_olm_04-installplan.crd.yaml
  manifests/0000_50_olm_05-subscription.crd.yaml
  manifests/0000_50_olm_06-catalogsource.crd.yaml
  manifests/0000_50_olm_10-operatorgroup.crd.yaml
Labels: approved, lgtm, size/XS

#787 Fixing indentation for spec field
  Documentation/design/operatorgroups.md
Labels: approved, lgtm, size/S

#768 Add support for Windows WSL in run_console_local.sh
  scripts/run_console_local.sh
Labels: approved, kind/feature, lgtm, ok-to-test, size/XS

#751 Fix small typo.
  Documentation/design/dependency-resolution.md
Labels: approved, lgtm, ok-to-test, size/XS

#806 documentation: Fix a few typos.
  Documentation/design/building-your-csv.md
  Documentation/design/debugging.md
  Documentation/design/operatorgroups.md
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#855 fix(unit): TestUpdate no longer flakes
  pkg/controller/operators/olm/operator_test.go
Labels: approved, lgtm, size/M

#821 Add validation details for `spec.maturity` field
  Documentation/design/building-your-csv.md
Labels: approved, lgtm, size/XS

#858 fix(run_console_loca): Fix command and improve output message
  Makefile
  README.md
  scripts/run_console_local.sh
Labels: approved, lgtm, ok-to-test, size/M

#839 fix(catalog): Fix subscriptions without a sourceNamespace hang forever
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/registry/resolver/resolver.go
Labels: approved, lgtm, size/L

#852 chore(deploy): fix release scripts
  Dockerfile
  Makefile
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_11-olm-operators.configmap.yaml
  deploy/chart/templates/_packageserver.clusterserviceversion.yaml
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  deploy/ocp/manifests/0.9.0/0000_50_olm_00-namespace.yaml
  deploy/ocp/manifests/0.9.0/0000_50_olm_03-clusterserviceversion.crd.yaml
  deploy/ocp/manifests/0.9.0/0000_50_olm_04-installplan.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_11-olm-operators.configmap.yaml
  manifests/0000_50_olm_16-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_17-packageserver.deployment.yaml
Labels: approved, lgtm, size/L

#851 fix(operatorgroup): No targetNamespaces matched namespace selector
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm, size/M

#859 fix(unit): Remove leftover println causing excessive log in unit test
  pkg/controller/registry/resolver/util_test.go
Labels: approved, lgtm, size/XS

#795 Garbage Collection for OperatorGroup RBAC
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/M

#856 test(olm): test role aggregation for aggregate apiservices
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/M

#837 Refactor to avoid cache races
  Makefile
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm, size/L

#750 fix(olm): add deletion monitoring for api services
  pkg/controller/operators/olm/operator.go
  test/e2e/csv_e2e_test.go
Labels: approved, kind/feature, lgtm, size/L

#860 (refactor) Move csv set and replace to a package
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/lib/csv/csvset.go
  pkg/lib/csv/replace_finder.go
Labels: approved, lgtm, size/L

#754 Add Provided APIs to PackageManifest
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/package-server/apis/apps/v1alpha1/packagemanifest_types.go
  pkg/package-server/apis/apps/v1alpha1/zz_generated.conversion.go
  pkg/package-server/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/package-server/apis/openapi/zz_generated.openapi.go
  pkg/package-server/apis/operators/packagemanifest.go
  pkg/package-server/apis/operators/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/packagemanifest.go
  pkg/package-server/apis/operators/v1/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/zz_generated.conversion.go
  pkg/package-server/apis/operators/v1/zz_generated.deepcopy.go
  pkg/package-server/apis/operators/zz_generated.deepcopy.go
  pkg/package-server/client/informers/externalversions/apis/interface.go
  pkg/package-server/client/informers/externalversions/apis/operators/interface.go
  pkg/package-server/client/informers/externalversions/apis/operators/packagemanifest.go
  pkg/package-server/client/listers/apis/operators/expansion_generated.go
  pkg/package-server/client/listers/apis/operators/packagemanifest.go
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm, size/XL

#865 bump version to 0.10.0
  OLM_VERSION
Labels: approved, lgtm, size/XS

#861 fix(catalog): close grpc connections before deleting them
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/fakes/fake_registry_client.go
  pkg/fakes/fake_resolver.go
  test/e2e/setup_bare_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/client/client.go
  vendor/github.com/operator-framework/operator-registry/pkg/client/errors.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/directory.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/k8s.io/code-generator/generate_groups.sh
  vendor/k8s.io/code-generator/generate_internal_groups.sh
  vendor/k8s.io/code-generator/hack/boilerplate.go.txt
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#867 docs(release): add basic steps for making release
  Documentation/design/release.md
Labels: approved, lgtm, size/S

#869 fix(operatorgroup): Remove namespaces requirement for opgroup status
  deploy/chart/templates/0000_50_olm_10-operatorgroup.crd.yaml
  deploy/upstream/quickstart/olm.yaml
  manifests/0000_50_olm_10-operatorgroup.crd.yaml
Labels: approved, lgtm, size/XS
