Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-03, with the labels that each got.

#671 add view rbac to 'admin' and 'edit' default roles
  deploy/chart/templates/0000_50_olm_08-aggregated.clusterrole.yaml
  deploy/ocp/manifests/0.7.2/0000_30_12-aggregated.clusterrole.yaml
  deploy/ocp/manifests/0.7.4/0000_30_12-aggregated.clusterrole.yaml
  deploy/ocp/manifests/0.8.1/0000_50_olm_08-aggregated.clusterrole.yaml
  deploy/okd/manifests/0.8.1/0000_50_olm_08-aggregated.clusterrole.yaml
  deploy/upstream/manifests/0.8.1/0000_50_olm_08-aggregated.clusterrole.yaml
  manifests/0000_50_olm_08-aggregated.clusterrole.yaml
Labels: approved, lgtm, ok-to-test, size/S

#716 Fix API Validation for `OperatorGroup` Spec
  deploy/chart/templates/0000_50_olm_09-operatorgroup.crd.yaml
Labels: approved, lgtm, size/M

#738 fix(packageserver): set packageserver to IfNotPresent
  deploy/ocp/manifests/0.8.1/0000_50_olm_10-olm-operators.configmap.yaml
  deploy/ocp/values.yaml
  manifests/0000_50_olm_10-olm-operators.configmap.yaml
Labels: approved, lgtm, size/XS

#733 fix(installmodes): update support logic to match expected behavior
  go.sum
  pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_test.go
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
  vendor/k8s.io/client-go/pkg/version/base.go
Labels: approved, lgtm, size/XL

#744 chore(manifests): regenerate manifests to include new anyOf validation
  deploy/ocp/manifests/0.8.1/0000_50_olm_09-operatorgroup.crd.yaml
  deploy/ocp/values.yaml
  deploy/okd/manifests/0.8.1/0000_50_olm_09-operatorgroup.crd.yaml
  deploy/upstream/manifests/0.8.1/0000_50_olm_09-operatorgroup.crd.yaml
  deploy/upstream/values.yaml
  manifests/0000_50_olm_09-operatorgroup.crd.yaml
  pkg/api/apis/operators/v1alpha2/operatorgroup_types.go
  pkg/api/apis/operators/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/L

#739 Add minKubeVersion validation to templates
  deploy/chart/templates/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/ocp/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/okd/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/upstream/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  manifests/0000_50_olm_02-clusterserviceversion.crd.yaml
Labels: approved, lgtm, size/XS

#690 fix(olm): Fix CSVs api-servers battle for ownership of APIServices
  pkg/controller/errors/errors.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/lib/ownerutil/util.go
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, size/XL

#745 feat(test): adds CSV phase reporting for package server
  scripts/install_local.sh
  scripts/run_e2e_local.sh
  test/e2e/util_test.go
Labels: approved, lgtm, size/M

#713 docs: update CSV link
  Documentation/design/building-your-csv.md
Labels: approved, lgtm, size/XS

#704 remove minishift support
  Documentation/install/install.md
  Documentation/install/local-values-shift.yaml
  Makefile
  e2e-local-shift.Dockerfile
  scripts/build_local_shift.sh
Labels: approved, lgtm, ok-to-test, size/M

#736 OperatorGroup expansion/contraction
  Makefile
  go.mod
  go.sum
  pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  pkg/api/apis/operators/v1alpha2/operatorgroup_types.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/groups.go
  pkg/controller/registry/resolver/groups_test.go
  pkg/lib/ownerutil/util.go
  pkg/lib/queueinformer/queueindexer.go
  pkg/lib/queueinformer/queueinformer_operator.go
  pkg/lib/queueinformer/resourcequeue.go
  scripts/run_e2e_local.sh
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/setup_bare_test.go
  test/e2e/util_test.go
  vendor/k8s.io/kubernetes/pkg/util/labels/.readonly
  vendor/k8s.io/kubernetes/pkg/util/labels/BUILD
  vendor/k8s.io/kubernetes/pkg/util/labels/doc.go
  vendor/k8s.io/kubernetes/pkg/util/labels/labels.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#749 Emit `InstallSucceeded` Event for CSV
  go.mod
  go.sum
  pkg/controller/operators/olm/operator.go
  test/e2e/csv_e2e_test.go
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/any.go
  vendor/github.com/json-iterator/go/iter_float.go
  vendor/github.com/json-iterator/go/iter_skip_strict.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_marshaler.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#758 fix(csv): properly detect apiservice and crd conflicts
  go.sum
  pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/registry/resolver/operators.go
  pkg/lib/notify/notify.go
  pkg/lib/ownerutil/util.go
Labels: approved, lgtm, size/L

#748 clusteroperator: Report when OLM reaches "level" and check syncs
  cmd/catalog/main.go
  cmd/olm/main.go
  cmd/package-server/apiserver.local.config/certificates/apiserver.crt
  cmd/package-server/apiserver.local.config/certificates/apiserver.key
  manifests/0000_50_olm_06-olm-operator.deployment.yaml
  manifests/0000_50_olm_14-operatorstatus.yaml
  pkg/lib/queueinformer/queueinformer_operator.go
  pkg/package-server/server/server.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm, size/L

#752 refactor(images): use operator-framework namespace for all olm images
  Documentation/design/developing.md
  Documentation/install/install.md
  Documentation/install/local-values.yaml
  Makefile
  deploy/chart/values.yaml
  go.mod
  go.sum
  scripts/build_local.sh
  scripts/package-quickstart.sh
  scripts/package_quickstart.sh
  scripts/package_release.sh
  scripts/run_e2e_docker.sh
  scripts/run_e2e_local.sh
  test/e2e/e2e-bare-values.yaml
  test/e2e/e2e-values.yaml
  upstream.Dockerfile
  vendor/github.com/coreos/etcd/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#761 Subscription steps through multiple upgrades
  Makefile
  go.sum
  pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  pkg/controller/install/deployment.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/operators_test.go
  pkg/controller/registry/resolver/rbac.go
  pkg/controller/registry/resolver/resolver.go
  pkg/lib/ownerutil/util.go
  pkg/lib/queueinformer/queueindexer.go
  pkg/lib/queueinformer/queueinformer_operator.go
  scripts/build_local.sh
  scripts/run_e2e_local.sh
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, size/XL

#722 fix(ocp): add csv and deployment for package server
  deploy/chart/templates/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  deploy/chart/templates/0000_50_olm_16-packageserver.deployment.yaml
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  deploy/ocp/values.yaml
  deploy/okd/values.yaml
  deploy/upstream/values.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_16-packageserver.deployment.yaml
Labels: approved, lgtm, size/L

#760 Fix typo - k8s version format
  Documentation/design/building-your-csv.md
Labels: approved, lgtm, size/XS

#762 Add upstream catalog
  deploy/chart/templates/0000_50_olm_06-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_14-operatorstatus.yaml
  deploy/chart/templates/0000_50_olm_17-upstream-operators.catalogsource.yaml
Labels: approved, lgtm, size/S

#763 feat(csv): requeue csvs on change to CRDs
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/requirements_test.go
  pkg/controller/registry/resolver/labeler.go
  pkg/controller/registry/resolver/labeler_test.go
  pkg/controller/registry/resolver/operators.go
  pkg/lib/index/label.go
  pkg/lib/labeler/labeler.go
  pkg/lib/notify/notify.go
  pkg/lib/queueinformer/queueindexer.go
  pkg/lib/queueinformer/resourcequeue.go
Labels: approved, lgtm, size/XL

#764 Grant namespace list to global operators
  Makefile
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  scripts/build_local.sh
  test/e2e/operator_groups_e2e_test.go
Labels: approved, enhancement, lgtm, size/M

#765 docs(git): add changelog
  CHANGELOG.md
Labels: approved, docs, size/L

#777 chore(build): build binaries locally and load them into containers
  Makefile
  local.Dockerfile
  scripts/build_local.sh
Labels: approved, lgtm, size/S

#776 chore(catalog): add ClusterOperator status for catalog operator
  cmd/catalog/main.go
  cmd/olm/main.go
  deploy/chart/templates/0000_50_olm_07-catalog-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_14-operatorstatus.yaml
  deploy/ocp/values.yaml
  go.mod
  go.sum
  pkg/lib/operatorstatus/status.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/doc.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduling.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/core_getters.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/fake_informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#682 fix(metrics): add service monitor config
  cmd/catalog/main.go
  cmd/olm/main.go
  deploy/chart/templates/0000_50_olm_00-namespace.yaml
  deploy/chart/templates/0000_50_olm_02-services.yaml
  deploy/chart/templates/0000_50_olm_03-clusterserviceversion.crd.yaml
  deploy/chart/templates/0000_50_olm_04-installplan.crd.yaml
  deploy/chart/templates/0000_50_olm_05-subscription.crd.yaml
  deploy/chart/templates/0000_50_olm_06-catalogsource.crd.yaml
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_09-aggregated.clusterrole.yaml
  deploy/chart/templates/0000_50_olm_10-operatorgroup.crd.yaml
  deploy/chart/templates/0000_50_olm_11-olm-operators.configmap.yaml
  deploy/chart/templates/0000_50_olm_12-olm-operators.catalogsource.yaml
  deploy/chart/templates/0000_50_olm_13-operatorgroup-default.yaml
  deploy/chart/templates/0000_50_olm_14-packageserver.subscription.yaml
  deploy/chart/templates/0000_50_olm_15-operatorstatus.yaml
  deploy/chart/templates/0000_50_olm_16-packageserver.clusterserviceversion.yaml
  deploy/chart/templates/0000_50_olm_17-packageserver.deployment.yaml
  deploy/chart/templates/0000_50_olm_18-upstream-operators.catalogsource.yaml
  deploy/chart/templates/0000_50_olm_19-service-monitor.yaml
  deploy/ocp/values.yaml
Labels: approved, enhancement, lgtm, size/L

#791 fix(packageserver): add struct tags to PackageManifestList
  pkg/package-server/apis/openapi/zz_generated.openapi.go
  pkg/package-server/apis/operators/v1/packagemanifest_types.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, lgtm, size/M

#792 fix(annotation): don't annotate deployments that aren't owned by a CSV
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, bug, lgtm, size/L

#775 chore(deploy): set priorityclass on olm pods
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_11-olm-operators.configmap.yaml
  manifests/0000_50_olm_16-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_17-packageserver.deployment.yaml
Labels: approved, lgtm, size/S
