Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-11, with the labels that each got.

#1100 feat(metrics) Report subscription channel
  pkg/controller/operators/catalog/subscription/syncer.go
  pkg/metrics/metrics.go
Labels: approved, lgtm, size/S

#1104 Alerts for failing OLM operators
  deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
Labels: approved, lgtm, size/M

#1091 Bug 1763749: Prioritize APIs from same CatSrc
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/user_defined_sa_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#1111 Fix several flaky e2e test cases
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, size/XS

#1096 fix: t.Fatal should be used in main goroutine
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1115 Fixing doc typo
  doc/design/subscription-config.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#1112 [release-4.2] Bug 1767848: Manual approval strategy ignored for subsequent release
  pkg/controller/operators/catalog/operator.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#1107 [Release 4.1] Bug 1767846: Manual approval strategy ignored for subsequent releases
  pkg/controller/operators/catalog/operator.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#1110 Bug 1763750: Prioritize APIs from same CatSrc
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#1131 [docs] - update release docs
  doc/design/release.md
Labels: approved, kind/documentation, lgtm, size/S

#1130 [release] - version bump
  OLM_VERSION
Labels: approved, lgtm, size/XS

#1114 Bug 1767004: defer provided api update in operator groups
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1135 Generate release changelog
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1132 Bug 1773661: schedule catalogsource pods to linux nodes only
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1137 [docs] update changelog command
  doc/design/release.md
Labels: approved, lgtm, size/XS

#1116 Bug 1774720: catalogsource context cancel function leak
  pkg/controller/registry/grpc/source.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1142 Bug 1760608: add resource limits to all OLM pods and the 0.13.0 release for OCP
  deploy/ocp/values.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1147 fix(unit): Fix minor unit test bug and update local cluster to k8s 1.16
  pkg/controller/operators/catalog/operator_test.go
  scripts/build_local.sh
Labels: approved, lgtm, size/XS
