Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-02, with the labels that each got.

#702 fix(deploy): Add a component prefix to manifests
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-clusterserviceversion.crd.yaml
  manifests/0000_50_olm_03-installplan.crd.yaml
  manifests/0000_50_olm_04-subscription.crd.yaml
  manifests/0000_50_olm_05-catalogsource.crd.yaml
  manifests/0000_50_olm_10-olm-operator.deployment.yaml
  manifests/0000_50_olm_11-catalog-operator.deployment.yaml
  manifests/0000_50_olm_12-aggregated.clusterrole.yaml
  manifests/0000_50_olm_13-operatorgroup.crd.yaml
  manifests/0000_50_olm_14-olm-operators.configmap.yaml
  manifests/0000_50_olm_15-olm-operators.catalogsource.yaml
  manifests/0000_50_olm_16-operatorgroup-default.yaml
  manifests/0000_50_olm_17-packageserver.subscription.yaml
  manifests/0000_50_olm_18-operatorstatus.yaml
Labels: approved, lgtm, size/XS

#703 Make e2e more robust
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm, size/M

#699 fix(olm): Remove the "v" prefix in minKubeVersion if presents
  Documentation/design/building-your-csv.md
  pkg/controller/operators/olm/requirements.go
Labels: approved, lgtm, size/XS

#697 fix(packagemanifest): Add InstallModes info from CSV to PackageManifest
  Makefile
  go.mod
  go.sum
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/package-server/apis/openapi/zz_generated.openapi.go
  pkg/package-server/apis/packagemanifest/v1alpha1/packagemanifest.go
  pkg/package-server/apis/packagemanifest/v1alpha1/packagemanifest_types.go
  pkg/package-server/apis/packagemanifest/v1alpha1/zz_generated.deepcopy.go
  pkg/package-server/provider/registry_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#683 Add godoc for InstallModeTypes
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
Labels: approved, lgtm, size/S

#711 Add Graceful Shutdown to PackageManifest Server
  deploy/chart/templates/_packageserver.clusterserviceversion.yaml
  deploy/chart/values.yaml
  deploy/ocp/manifests/0.8.1/0000_50_olm_10-olm-operators.configmap.yaml
  deploy/ocp/values.yaml
  deploy/okd/manifests/0.8.1/0000_50_olm_10-olm-operators.configmap.yaml
  deploy/okd/values.yaml
  deploy/upstream/manifests/0.8.1/0000_50_olm_10-olm-operators.configmap.yaml
  deploy/upstream/values.yaml
  go.sum
  manifests/0000_50_olm_10-olm-operators.configmap.yaml
  pkg/package-server/server/server.go
Labels: approved, lgtm, size/M

#708 fix(registry-pods): add everything toleration to registry pods
  go.mod
  go.sum
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/grpc.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#710 fix(olm): properly detect cluster operator API
  cmd/olm/main.go
Labels: approved, lgtm, size/L

#717 feat(csv): allow use verb in permissions
  deploy/chart/templates/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/ocp/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/okd/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/upstream/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  manifests/0000_50_olm_02-clusterserviceversion.crd.yaml
  manifests/0000_50_olm_09-operatorgroup.crd.yaml
Labels: approved, lgtm, size/L

#723 fix(csv): remove regex on base64 image data
  deploy/chart/templates/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/ocp/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/okd/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  deploy/upstream/manifests/0.8.1/0000_50_olm_02-clusterserviceversion.crd.yaml
  go.sum
  manifests/0000_50_olm_02-clusterserviceversion.crd.yaml
Labels: approved, lgtm, size/M

#720 add all-in-one yaml and helper script
  deploy/upstream/quickstart/olm.yaml
  deploy/upstream/values.yaml
  scripts/package-quickstart.sh
Labels: approved, lgtm, ok-to-test, size/XXL

#729 fix(owners): remove cross-namespace and cluster->namespace ownerrefs
  go.mod
  go.sum
  pkg/api/wrappers/deployment_install_client_test.go
  pkg/controller/install/deployment.go
  pkg/controller/install/deployment_test.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/rbac.go
  pkg/lib/ownerutil/util.go
  vendor/k8s.io/apimachinery/pkg/api/errors/errors.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#731 fix(packagesever): add missing name field to api definition
  deploy/chart/templates/_packageserver.clusterserviceversion.yaml
  deploy/ocp/manifests/0.8.1/0000_50_olm_10-olm-operators.configmap.yaml
  deploy/okd/manifests/0.8.1/0000_50_olm_10-olm-operators.configmap.yaml
  deploy/upstream/manifests/0.8.1/0000_50_olm_10-olm-operators.configmap.yaml
  manifests/0000_50_olm_10-olm-operators.configmap.yaml
Labels: approved, lgtm, size/XS

#721 docs(operatorgroups): add more extensive docs
  Documentation/design/architecture.md
  Documentation/design/building-your-csv.md
  Documentation/design/operatorgroups.md
  README.md
Labels: approved, lgtm, size/L

#673 Add view role verbs to admin/edit role aggregation.
  pkg/api/apis/operators/v1alpha1/installplan_types.go
Labels: lgtm, ok-to-test, size/XS
