Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-06, with the labels that each got.

#876 Documentation: Fix a few typos
  Documentation/design/building-your-csv.md
  Documentation/design/developing.md
  Documentation/design/operatorgroups.md
  Documentation/design/philosophy.md
Labels: approved, lgtm, ok-to-test, size/S

#871 Change Global Catalog Namespace for OpenShift
  deploy/ocp/values.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_16-packageserver.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#887 Bump release version to 0.10.1
  OLM_VERSION
Labels: approved, lgtm, size/XS

#885 repair run_console_run.sh script
  scripts/run_console_local.sh
Labels: approved, lgtm, size/M

#890 Change Package Server Global Namespace
  deploy/chart/templates/0000_50_olm_11-olm-operators.configmap.yaml
  deploy/chart/templates/0000_50_olm_12-olm-operators.catalogsource.yaml
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  manifests/0000_50_olm_17-packageserver.deployment.yaml
Labels: approved, lgtm, size/XS

#880 (proposal) Add user defined service account
  Documentation/contributors/design-proposals/user-defined-service-account.md
Labels: approved, lgtm, size/M

#904 Fix PackageManifest Server Crashes
  pkg/package-server/provider/registry.go
Labels: approved, lgtm, size/S

#907 add -l option to $POD_MANAGER attach
  scripts/run_console_local.sh
Labels: approved, lgtm, size/XS

#909 allow KUBECONFIG to be set from env in run_e2e_bare.sh
  scripts/run_e2e_bare.sh
Labels: approved, lgtm, size/XS

#881 Subscription CatalogSource Status
  cmd/catalog/main.go
  cmd/olm/main.go
  cmd/package-server/main.go
  pkg/api/apis/operators/clusterserviceversion_types.go
  pkg/api/apis/operators/install/install.go
  pkg/api/apis/operators/reference/reference_test.go
  pkg/api/apis/operators/register.go
  pkg/api/apis/operators/subscription_types.go
  pkg/api/apis/operators/v1alpha1/subscription_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/api/apis/operators/zz_generated.deepcopy.go
  pkg/api/client/client.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscription/config.go
  pkg/controller/operators/catalog/subscription/reconciler.go
  pkg/controller/operators/catalog/subscription/reconciler_test.go
  pkg/controller/operators/catalog/subscription/state.go
  pkg/controller/operators/catalog/subscription/state_test.go
  pkg/controller/operators/catalog/subscription/syncer.go
  pkg/controller/operators/catalog/subscription/syncer_test.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/config.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/configmap_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_address.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/lib/kubestate/kubestate.go
  pkg/lib/operatorstatus/status.go
  pkg/lib/queueinformer/config.go
  pkg/lib/queueinformer/config_test.go
  pkg/lib/queueinformer/queueindexer.go
  pkg/lib/queueinformer/queueinformer.go
  pkg/lib/queueinformer/queueinformer_operator.go
  pkg/lib/queueinformer/resourcequeue.go
  pkg/lib/signals/signals.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
  pkg/package-server/server/server.go
  test/e2e/setup_bare_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, size/XXL

#911 Add config options to QueueInformer constructors
  cmd/catalog/main.go
  cmd/olm/main.go
  pkg/api/apis/operators/register.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/requirements.go
  pkg/lib/queueinformer/config.go
  pkg/lib/queueinformer/queueinformer_operator.go
  pkg/package-server/provider/registry_test.go
  pkg/package-server/server/server.go
Labels: approved, lgtm, size/L

#910 fix(chart): add missing descriptions to operator group
  deploy/chart/templates/0000_50_olm_10-operatorgroup.crd.yaml
  deploy/upstream/quickstart/crds.yaml
  manifests/0000_50_olm_10-operatorgroup.crd.yaml
Labels: approved, lgtm, size/S

#900 bug:1691546 fix(catalog): do not add owner references to clusterroles or crbs
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/rbac.go
Labels: approved, lgtm, size/M

#912 fix(build): don't use helm in src image
  Dockerfile
  Makefile
Labels: approved, lgtm, size/S

#914 Switch to go 1.12 in the root Dockerfile
  Dockerfile
Labels: approved, lgtm, size/S

#918 fix(build): set GO111MODULE=on
  Makefile
Labels: approved, lgtm, size/XS

#916 docs(release): add additional clarifying details
  Documentation/design/release.md
Labels: approved, lgtm, size/XS

#917 Update CHANGELOG to include changelogs from 0.10.0 and 0.10.1
  CHANGELOG.md
Labels: approved, lgtm, size/M

#878 Enable OLM to update CRD when there is only one owner of that CRD
  pkg/controller/operators/catalog/operator.go
  pkg/lib/index/api.go
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm, size/L

#920 fix(test): fixup bare test imports and vars
  test/e2e/setup_bare_test.go
Labels: approved, lgtm, size/XS

#863 Package API server monitoring
  cmd/olm/main.go
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  deploy/chart/templates/0000_50_olm_16-packageserver.deployment.yaml
  deploy/chart/templates/0000_50_olm_17-upstream-operators.catalogsource.yaml
  deploy/chart/templates/0000_50_olm_18-service-monitor.yaml
  deploy/chart/templates/0000_50_olm_99-operatorstatus.yaml
  deploy/chart/templates/_packageserver.clusterserviceversion.yaml
  deploy/ocp/values.yaml
  deploy/upstream/values.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_11-olm-operators.configmap.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_16-packageserver.deployment.yaml
  manifests/0000_50_olm_18-service-monitor.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  pkg/controller/operators/olm/operator.go
  pkg/lib/csv/csvset.go
  pkg/lib/csv/notification.go
  pkg/lib/csv/replace_finder.go
  pkg/lib/operatorstatus/builder.go
  pkg/lib/operatorstatus/builder_test.go
  pkg/lib/operatorstatus/clusteroperatorwriter.go
  pkg/lib/operatorstatus/csv_handler.go
  pkg/lib/operatorstatus/csv_reporter.go
  pkg/lib/operatorstatus/csv_reporter_test.go
  pkg/lib/operatorstatus/monitor.go
  pkg/lib/operatorstatus/monitor_test.go
Labels: approved, lgtm, size/XXL

#923 Add Subscription InstallPlan Status
  go.mod
  go.sum
  pkg/api/apis/operators/installplan_types.go
  pkg/api/apis/operators/subscription_types.go
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/api/apis/operators/v1alpha1/subscription_types.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscription/config.go
  pkg/controller/operators/catalog/subscription/reconciler.go
  pkg/controller/operators/catalog/subscription/reconciler_test.go
  pkg/controller/operators/catalog/subscription/state.go
  pkg/controller/operators/catalog/subscription/state_test.go
  pkg/controller/operators/catalog/subscription/syncer.go
  pkg/lib/comparison/equal.go
  pkg/lib/comparison/equal_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/subscription_e2e_test.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/mitchellh/hashstructure/LICENSE
  vendor/github.com/mitchellh/hashstructure/README.md
  vendor/github.com/mitchellh/hashstructure/go.mod
  vendor/github.com/mitchellh/hashstructure/hashstructure.go
  vendor/github.com/mitchellh/hashstructure/include.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#928 manifests: move ServiceMonitor manifest to runlevel 90
  manifests/0000_90_olm_00-service-monitor.yaml
Labels: approved, lgtm, size/XS

#915 Bug 1723851: fix(catalog): do not add owner references to clusterroles or crbs (4.1 cherrypick)
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/rbac.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#892 Add support for user defined ServiceAccount for OperatorGroup.
  cmd/olm/main.go
  pkg/api/apis/operators/operatorgroup_types.go
  pkg/api/apis/operators/v1/operatorgroup_types.go
  pkg/api/apis/operators/v1/zz_generated.conversion.go
  pkg/api/apis/operators/v1/zz_generated.deepcopy.go
  pkg/api/apis/operators/zz_generated.deepcopy.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step_ensurer.go
  pkg/controller/operators/olm/config.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/lib/operatorclient/client.go
  pkg/lib/scoped/attenuator.go
  pkg/lib/scoped/querier.go
  pkg/lib/scoped/syncer.go
  pkg/lib/scoped/token_retriever.go
  pkg/lib/scoped/util.go
  pkg/lib/scopedclient/clientfactory.go
  test/e2e/installplan_e2e_test.go
  test/e2e/scoped_client_test.go
  test/e2e/user_defined_sa_test.go
Labels: approved, lgtm, size/XXL

#925 Bug 1723818: CSV name change should not cause upgrade to fail
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#937 1723818: package server 4.1 to 4.2 upgrade should not fail
  manifests/0000_50_olm_11-olm-operators.configmap.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: approved, lgtm, size/L
