Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-07, with the labels that each got.

#913 Add webhook proposal
  Documentation/contributors/design-proposals/webhooks.md
Labels: approved, lgtm, size/L

#938 test(e2e): remove extra resource comparison
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, size/S

#929 Add optional profiling
  Documentation/design/profiling.md
  cmd/catalog/main.go
  cmd/olm/main.go
  pkg/lib/profile/profile.go
Labels: approved, lgtm, size/L

#931 feat(csv): detect changes to a deployment and persist them
  pkg/controller/install/deployment.go
  pkg/controller/install/errors.go
  pkg/controller/operators/olm/operator.go
  pkg/lib/ownerutil/util.go
  scripts/build_local.sh
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, size/L

#941 proposal(operator-config): initial proposal for persisting configuration
  Documentation/contributors/design-proposals/operator-config.md
Labels: approved, lgtm, size/L

#945 Minor fixes
  pkg/api/wrappers/deployment_install_client.go
  test/e2e/setup_bare_test.go
Labels: approved, lgtm, size/S

#943 Add simple benchmark for namespaced subscription resolution
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/operators/olm/operator_test.go
  pkg/lib/clientfake/client_options.go
Labels: approved, lgtm, size/L

#902 Allow CRD updates with multiple owners
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/operator.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm, size/L

#942 Remove package server subscription
  cmd/olm/cleanup.go
  cmd/olm/main.go
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_11-olm-operators.configmap.yaml
  deploy/chart/templates/0000_50_olm_12-olm-operators.catalogsource.yaml
  deploy/chart/templates/0000_50_olm_14-packageserver.subscription.yaml
  deploy/chart/templates/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  deploy/chart/templates/0000_50_olm_16-packageserver.deployment.yaml
  deploy/chart/templates/0000_90_olm_00-service-monitor.yaml
  deploy/chart/templates/_packageserver.clusterserviceversion.yaml
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_11-olm-operators.configmap.yaml
  manifests/0000_50_olm_12-olm-operators.catalogsource.yaml
  manifests/0000_50_olm_14-packageserver.subscription.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_16-packageserver.deployment.yaml
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/operator.go
  scripts/install_local.sh
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm, size/XL

#933 Validate existing Custom Resources against new schema prior updating
  Documentation/design/dependency-resolution.md
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/lib/operatorclient/customresources.go
  test/e2e/installplan_e2e_test.go
  test/e2e/util_test.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#957 fix(manifest): fix env var projection in command
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
Labels: approved, lgtm, size/XS

#955 feat(deploy): add resource requests to all pods
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/configmap_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm, size/L

#959 Bug 1732302: Fix panic when binding already exists
  pkg/controller/operators/catalog/step_ensurer.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#962 (release) cut a release for 0.11.0
  OLM_VERSION
Labels: approved, lgtm, ok-to-test

#958 Bug 1732613: Follow up for pod configuration
  pkg/controller/install/deployment.go
  pkg/controller/install/resolver.go
  pkg/controller/operators/olm/envvar/initializer.go
  pkg/controller/operators/olm/envvar/inject.go
  pkg/controller/operators/olm/operator.go
  pkg/lib/proxy/querier.go
  test/e2e/subscription_e2e_test.go
  test/e2e/user_defined_sa_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#961 Bug 1662263: include git sha in ART builds
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#967 (release) update changelog
  CHANGELOG.md
Labels: approved, lgtm, size/M

#965 Bug 1714140: fix(catalog): re-install resources in existing installplan
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscriptions_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
