Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2019-09, with the labels that each got.

#1025 Bug 1746159: Cleanup leftover cross-namespace OwnerReferences
  cmd/olm/cleanup.go
  cmd/olm/cleanup_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#1023 Bug 1744245: Subscription should not point to deleted ip
  pkg/controller/operators/catalog/operator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1018 Bug 1717636: Add proper name to related objects
  cmd/catalog/main.go
  cmd/olm/main.go
  pkg/lib/operatorstatus/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1026 Bug 1748771: Default Icon for PackageManifest Subresource
  pkg/package-server/storage/subresources.go
  pkg/package-server/storage/subresources_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1019 Bug 1748914: Drop the hard-coded DNS suffix
  pkg/api/apis/operators/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#993 Readme adjustments
  README.md
Labels: approved, lgtm, ok-to-test, size/M

#991 feat(github) : Add github files
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support-question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, ok-to-test, size/L

#992 fix name of dir - replace Documentation for doc
  doc/contributors/design-proposals/operator-config.md
  doc/contributors/design-proposals/operator-logos.md
  doc/contributors/design-proposals/subscription-status.md
  doc/contributors/design-proposals/user-defined-service-account.md
  doc/contributors/design-proposals/webhooks.md
  doc/design/access-control.md
  doc/design/architecture.md
  doc/design/building-your-csv.md
  doc/design/debugging.md
  doc/design/dependency-resolution.md
  doc/design/developing.md
  doc/design/operatorgroups.md
  doc/design/philosophy.md
  doc/design/profiling.md
  doc/design/release.md
  doc/design/scoped-operator-install.md
  doc/install/install.md
  doc/install/local-values.yaml
Labels: approved, ok-to-test, size/XS

#1029 Bug 1746811: Make packagemanifest list return all valid packages
  pkg/package-server/client/fakes/fake_list_packages_client.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#1031 Fix broken doc links
  Documentation/contributors/design-proposals/operator-validation-library.md
  Makefile
  README.md
  doc/design/developing.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1033 chore(docs): consolidate doc directories
  doc/contributors/design-proposals/csv-status.md
  doc/contributors/design-proposals/operator-validation-library.md
Labels: approved, kind/documentation, lgtm, size/XS

#984 (doc) Add deprecated CRD version procedure and note
  doc/design/dependency-resolution.md
Labels: CRD Versioning, approved, lgtm, size/M

#983 Bug 1746270: Remove deprecated CRD's stored versions to allow CRD update
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  test/e2e/installplan_e2e_test.go
Labels: CRD Versioning, approved, bugzilla/valid-bug, lgtm, size/L

#1027 Bug 1750980: feat(olm): don't calculate a patch when updating via a replacement chain
  pkg/api/wrappers/deployment_install_client.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#1038 Enable vendoring on Go 1.1x
  Makefile
Labels: approved, lgtm, size/XS

#1037 [release-4.1] Bug 1750867: Make packagemanifest list return all valid packages
  pkg/package-server/client/fakes/fake_list_packages_client.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#1004 Bug 1738203: Add relatedObjects to cluster operator status
  cmd/catalog/main.go
  cmd/olm/main.go
  pkg/lib/operatorstatus/status.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#988 (doc) How to update operators documentation
  doc/design/how-to-update-operators.md
  doc/design/images/catalogsource.png
  doc/design/images/channels.png
  doc/design/images/replaces.png
  doc/design/images/skipping-updates.png
  doc/design/images/z-stream.png
Labels: approved, kind/documentation, lgtm, size/L

#1047 (docs) Update release.md documentation
  doc/design/release.md
Labels: approved, kind/documentation, lgtm, size/S

#1046 (release) cut a release for 0.12.0
  OLM_VERSION
Labels: approved, lgtm, size/XS

#995 refactor(operatorstatus): make monitor constructor variadic
  cmd/olm/main.go
  pkg/lib/operatorstatus/monitor.go
Labels: approved, lgtm, size/S

#996 fix(subscriptionconfig): add missing merge struct tags
  pkg/api/apis/operators/v1alpha1/subscription_types.go
Labels: approved, lgtm, size/S

#994 feat(scripts): add shell lib with some common helper funcs
  scripts/install_local.sh
  scripts/lib/olm_util.sh
Labels: approved, lgtm, size/M
