Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-11, with the labels that each got.

#1848 Bug 1891995: Add spec hash to service's label to ensure service is correct
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/configmap_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1507 Replace assertions for csv-e2e to use Gomega's matcher library
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm

#1850 Generate changelog for v0.17.0.
  CHANGELOG.md
Labels: approved, lgtm

#1852 [release-4.6] Bug 1889745: fix(operators): prevent hotloop
  pkg/controller/operators/operator_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1844 fix the comment in package-server
  pkg/package-server/apiserver/config.go
Labels: approved, lgtm, ok-to-test

#1855 Bug 1819457: Services should not have duplicate ownerrefs
  pkg/controller/certs/certs.go
  pkg/controller/install/certresources.go
  pkg/controller/install/certresources_test.go
  pkg/fakes/client-go/listers/fake_rbac_v1_clusterrolebinding_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_role_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_role_namespace_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_rolebinding_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_rolebinding_namespace_lister.go
  pkg/fakes/client-go/listers/fake_v1_secret_lister.go
  pkg/fakes/client-go/listers/fake_v1_secret_namespace_lister.go
  pkg/fakes/client-go/listers/fake_v1_service_lister.go
  pkg/fakes/client-go/listers/fake_v1_service_namespace_lister.go
  pkg/lib/operatorlister/lister.go
  scripts/update_mockgen.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1616 Allow ConsoleYAMLSample resources from bundle manifests
  pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm, ok-to-test

#1843 Bug 1841175: Recreate pending installplan if deleted before approval
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscription/reconciler_test.go
  pkg/controller/operators/catalog/subscription/state.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1856 Bug 1896051: Services should not have duplicate ownerrefs
  pkg/controller/certs/certs.go
  pkg/controller/install/certresources.go
  pkg/controller/install/certresources_test.go
  pkg/fakes/client-go/listers/fake_rbac_v1_clusterrolebinding_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_role_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_role_namespace_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_rolebinding_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_rolebinding_namespace_lister.go
  pkg/fakes/client-go/listers/fake_v1_secret_lister.go
  pkg/fakes/client-go/listers/fake_v1_secret_namespace_lister.go
  pkg/fakes/client-go/listers/fake_v1_service_lister.go
  pkg/fakes/client-go/listers/fake_v1_service_namespace_lister.go
  pkg/lib/operatorlister/lister.go
  scripts/update_mockgen.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1865 [release-4.5] Bug 1892372: OLM should use valid CA certs if available
  pkg/controller/install/certresources.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  test/e2e/webhook_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1873 (chore): add default label to issues
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support-question.md
Labels: approved, lgtm

#1876 Bug 1899835: fix(catalog): be defensive about directly indexing catalog pods
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
Labels: approved, lgtm
