Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-08, with the labels that each got.

#1702 Remove spurious check for duplicate operators in resolver.
  pkg/controller/registry/resolver/resolver.go
Labels: approved, lgtm

#1696 chore(clean): Remove legacy resolver
  cmd/catalog/main.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
  pkg/controller/registry/resolver/generation.go
  pkg/controller/registry/resolver/generation_test.go
  pkg/controller/registry/resolver/legacy_resolver.go
  pkg/controller/registry/resolver/legacy_resolver_test.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
Labels: approved, lgtm

#1661 feat(operator): adopt referenced installplans
  pkg/controller/operators/adoption_controller.go
  pkg/controller/operators/adoption_controller_test.go
  pkg/controller/operators/decorators/operator.go
  pkg/controller/operators/suite_test.go
  pkg/controller/operators/testdata/fixtures/installplan.yaml
  test/e2e/operator_test.go
  test/e2e/user_defined_sa_test.go
Labels: approved, lgtm

#1687 feat(resolver): Add label dependency type to new resolver
  go.mod
  go.sum
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/resolver_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/bundle/generate.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/bundle/validate.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/interface.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/types.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/deprecate.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/query.go
  vendor/modules.txt
Labels: approved, area/dependency, lgtm

#1699 feat(resolver): filtering deprecated bundles in resolver
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/cache_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
Labels: approved, area/dependency, lgtm

#1706 Add Catalog Source priority for dependency resolution
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/cache_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/step_resolver.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
Labels: approved, area/dependency, lgtm

#1689 [release-4.5] Bug 1862407: fix(resolver): be smarter about the way downgrades are attempted
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1591 Bug 1850237: Delete subscription metric when an operator is uninstalled
  pkg/controller/operators/catalog/subscription/syncer.go
  pkg/controller/operators/catalog/subscription/syncer_test.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1713 Bug 1861605: Reduce length of explanation of status of Operator resource
  deploy/chart/crds/0000_50_olm_00-installplans.crd.yaml
  deploy/chart/crds/0000_50_olm_00-operators.crd.yaml
  deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  go.mod
  go.sum
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_installplans.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operators.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_subscriptions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operator_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1716 Bug 1860035: Fix SubscriptionConfig NodeSelector field
  doc/design/subscription-config.md
  pkg/controller/operators/olm/overrides/config.go
  pkg/controller/operators/olm/overrides/initializer.go
  pkg/controller/operators/olm/overrides/inject.go
  pkg/controller/operators/olm/overrides/inject_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1717 Add Total Test Number to report
  .github/workflows/e2e-tests.yml
  .github/workflows/flake-analyzer-periodics.yml
Labels: approved, lgtm

#1721 Bug 1861636: fix(operator): re-adopt manually disowned crds
  pkg/controller/operators/adoption_controller.go
  pkg/controller/operators/adoption_controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1715 Bug 1867169: Fix stale content in configmap due to stale bundle image in the node
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1613 add InstallplanApproval (automatic/manual) to OLM metrics
  pkg/metrics/metrics.go
  test/e2e/like_metric_matcher_test.go
  test/e2e/metrics_e2e_test.go
Labels: approved, lgtm, ok-to-test

#1728 Bug 1869523: Fix nodeSelector subscription config override
  pkg/controller/operators/olm/overrides/inject.go
  pkg/controller/operators/olm/overrides/inject_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1720 Bug 1861605: Update manifests to include the bug fix
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1725 Bug 1868497: Fix install plan creation for subscriptions that omit channel.
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1727 Update Owners file
  OWNERS
Labels: approved, bugzilla/valid-bug, kind/documentation, lgtm

#1624 Bug 1853601: Retry conflicting catalog source pod update after fetching latest pod spec
  cmd/catalog/main.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/lib/controller-runtime/client/fake_ssa.go
  pkg/lib/controller-runtime/client/ssa.go
  pkg/lib/controller-runtime/client/ssa_test.go
  test/e2e/ctx/ctx.go
  test/e2e/util_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1739 Update OWNERS
  OWNERS
Labels: approved, lgtm
