Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-07, with the labels that each got.

#1564 docs: add design docs for including additional objects in bundles
  doc/design/adding-pod-disruption-budgets.md
  doc/design/adding-priority-classes.md
  doc/design/adding-vertical-pod-autoscaler.md
Labels: approved, lgtm

#1617 test(e2e): patch installplans w/ server-side apply
  pkg/lib/testobj/runtime.go
  test/e2e/ctx/ctx.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm

#1577 feat: support priorityclass, poddisruptionbudget, and vpa objects
  pkg/controller/operators/catalog/operator.go
  test/e2e/bundle_e2e_test.go
Labels: approved, lgtm

#1618 Add workflow to save e2e test artifacts
  .github/workflows/e2e-tests.yml
Labels: approved, lgtm

#1590 [release-4.4] Bug 1850112: Resolve only default channels
  pkg/controller/registry/registry_client.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1619 Introduce preference order for solver.
  pkg/controller/registry/resolver/sat/dict.go
  pkg/controller/registry/resolver/sat/solve.go
  pkg/controller/registry/resolver/solver/bench_test.go
  pkg/controller/registry/resolver/solver/constraints.go
  pkg/controller/registry/resolver/solver/constraints_test.go
  pkg/controller/registry/resolver/solver/installable.go
  pkg/controller/registry/resolver/solver/lit_mapping.go
  pkg/controller/registry/resolver/solver/solve.go
  pkg/controller/registry/resolver/solver/solve_test.go
  pkg/controller/registry/resolver/solver/tracer.go
Labels: approved, lgtm

#1566 Bug 1827000: Pod Config Deployment Hash Error
  pkg/controller/install/errors.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1604 Retry update in flaky test of CSV w/owned API Service.
  test/e2e/csv_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm

#1632 Add an AtMost cardinality constraint to the solver package.
  pkg/controller/registry/resolver/solver/constraints.go
  pkg/controller/registry/resolver/solver/constraints_test.go
  pkg/controller/registry/resolver/solver/lit_mapping.go
  pkg/controller/registry/resolver/solver/solve_test.go
Labels: approved, lgtm

#1630 Documentation improvements - PR template and DEVELOPMENT.md
  .github/PULL_REQUEST_TEMPLATE.md
  DEVELOPMENT.md
Labels: approved, lgtm, ok-to-test

#1631 fix: check installplan status in bundle e2e test
  test/e2e/bundle_e2e_test.go
Labels: approved, lgtm

#1636 fix: add installplan status check after subscription status check for gc e2e tests
  test/e2e/gc_e2e_test.go
Labels: approved, lgtm

#1552 Bug 1821274: Add CSV Metadata to PackageManifests
  pkg/package-server/apis/operators/packagemanifest.go
  pkg/package-server/apis/operators/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/packagemanifest.go
  pkg/package-server/apis/operators/v1/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/zz_generated.conversion.go
  pkg/package-server/apis/operators/v1/zz_generated.deepcopy.go
  pkg/package-server/apis/operators/zz_generated.deepcopy.go
  pkg/package-server/client/openapi/zz_generated.openapi.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1640 test(e2e): skip bundle cr install test
  test/e2e/bundle_e2e_test.go
Labels: approved, lgtm

#1637 fix: install VPA CRD directly on clusterfor bundle e2e test
  test/e2e/bundle_e2e_test.go
  test/e2e/testdata/vpa/crd.yaml
  test/e2e/testdata/vpa/vpa_bindata.go
Labels: approved, lgtm

#1478 Changed address for readiness and liveness probes on registry-server
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm, ok-to-test

#1607 feat(operator): automatically adopt generated resources
  cmd/olm/manager.go
  pkg/controller/install/certresources.go
  pkg/controller/operators/adoption_controller.go
  pkg/controller/operators/adoption_controller_test.go
  pkg/controller/operators/catalog/step.go
  pkg/controller/operators/decorators/operator.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/operator_controller.go
  pkg/controller/operators/operator_controller_test.go
  pkg/controller/operators/suite_test.go
  pkg/controller/operators/testdata/fixtures/apiservice.yaml
  pkg/controller/operators/testdata/fixtures/clusterrole.yaml
  pkg/controller/operators/testdata/fixtures/configmap.yaml
  pkg/controller/operators/testdata/fixtures/crb.yaml
  pkg/controller/operators/testdata/fixtures/crd.yaml
  pkg/controller/operators/testdata/fixtures/deployment.yaml
  pkg/controller/operators/testdata/fixtures/ns.yaml
  pkg/controller/operators/testdata/fixtures/pod.yaml
  pkg/controller/operators/testdata/fixtures/rb.yaml
  pkg/controller/operators/testdata/fixtures/role.yaml
  pkg/controller/operators/testdata/fixtures/sa.yaml
  pkg/controller/operators/testdata/fixtures/secret.yaml
  pkg/controller/operators/testdata/fixtures/service.yaml
  pkg/lib/ownerutil/util.go
  pkg/lib/testobj/fixture.go
  pkg/lib/testobj/runtime.go
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/ctx/ctx.go
  test/e2e/ctx/installer_helm.go
  test/e2e/gc_e2e_test.go
  test/e2e/metrics_e2e_test.go
  test/e2e/operator_test.go
  test/e2e/scoped_client_test.go
  test/e2e/user_defined_sa_test.go
  test/e2e/util_test.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm

#1635 test(e2e): delete all subs, installplans, catalogs, and csvs in test teardown
  test/e2e/bundle_e2e_test.go
  test/e2e/catalog_e2e_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/ctx/ctx.go
  test/e2e/dynamic_resource_e2e_test.go
  test/e2e/e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/user_defined_sa_test.go
  test/e2e/util_test.go
Labels: approved, lgtm

#1623 Bug 1851213: Set Resource to plural in CSV RelatedObjects field
  pkg/lib/operatorstatus/builder_test.go
  pkg/lib/operatorstatus/csv_reporter.go
  pkg/lib/operatorstatus/csv_reporter_test.go
  pkg/lib/operatorstatus/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1639 fix(metrics): query cache for object count metrics
  pkg/controller/operators/catalog/operator.go
  pkg/metrics/metrics.go
Labels: approved, lgtm

#1643 fix: Use PR head commit in artifact naming instead of merge commit
  .github/workflows/e2e-tests.yml
Labels: approved, lgtm

#1647 fix: remove bundle e2e test skip
  test/e2e/bundle_e2e_test.go
Labels: approved, lgtm

#1629 Bug 1855088: generate unique (Cluster)RoleBinding names
  pkg/controller/registry/resolver/rbac.go
  pkg/controller/registry/resolver/rbac_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#1650 Refactor solver preference searching.
  pkg/controller/registry/resolver/solver/constraints.go
  pkg/controller/registry/resolver/solver/lit_mapping.go
  pkg/controller/registry/resolver/solver/search.go
  pkg/controller/registry/resolver/solver/search_test.go
  pkg/controller/registry/resolver/solver/solve.go
  pkg/controller/registry/resolver/solver/solve_test.go
  pkg/controller/registry/resolver/solver/zz_search_test.go
Labels: approved, lgtm

#1641 fix: use server-side apply in crd e2e test
  test/e2e/crd_e2e_test.go
Labels: approved, lgtm

#1654 Return an error when solver input contains duplicate identifiers.
  pkg/controller/registry/resolver/solver/lit_mapping.go
  pkg/controller/registry/resolver/solver/search_test.go
  pkg/controller/registry/resolver/solver/solve.go
  pkg/controller/registry/resolver/solver/solve_test.go
Labels: approved, lgtm

#1659 Fix validate CRD compatibility check and deprecated CRD test case
  pkg/controller/operators/catalog/operator.go
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm

#1655 Omit (hopefully) redundant yum update from downstream builder stage.
  Dockerfile
Labels: approved, lgtm

#1642 Bug 1857424: fix(resolver): Exclude all installed packages in dependency search
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1664 Bug 1859493: fix(resolver): Exclude all installed packages in dependency search
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1656 fix: explicitly delete collection of catalog source pods in grpc e2e test
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm

#1645 Add flake analyzer periodics
  .github/workflows/e2e-tests.yml
  .github/workflows/flake-analyzer-periodics.yml
Labels: approved, lgtm

#1669 Bug 1859178: fix(installplans): GC older installplans
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1666 Bug 1859594: fix(resolver): Exclude all installed packages in dependency search
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1674 Bug 1859753: fix(installplans): GC older installplans
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1662 Bug: Fix incorrect deployment annotations
  pkg/controller/install/deployment.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, lgtm

#1676 Bug 1859748: fix(resolver): Exclude all installed packages in dependency search
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1675 Bug 1859755: fix(installplans): GC older installplans
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1678 Rebuild busybox operator index image
  pkg/controller/operators/catalog/operator.go
  scripts/build_test_images.sh
  test/e2e/catalog_e2e_test.go
  test/images/busybox-index/busybox-dependency/1.0.0/dockerfile
  test/images/busybox-index/busybox-dependency/1.0.0/manifests/csv.yaml
  test/images/busybox-index/busybox-dependency/1.0.0/manifests/foo.crd.yaml
  test/images/busybox-index/busybox-dependency/1.0.0/metadata/annotations.yaml
  test/images/busybox-index/busybox-dependency/2.0.0/dockerfile
  test/images/busybox-index/busybox-dependency/2.0.0/manifests/csv.yaml
  test/images/busybox-index/busybox-dependency/2.0.0/manifests/foo.crd.yaml
  test/images/busybox-index/busybox-dependency/2.0.0/metadata/annotations.yaml
  test/images/busybox-index/busybox/1.0.0/dockerfile
  test/images/busybox-index/busybox/1.0.0/manifests/csv.yaml
  test/images/busybox-index/busybox/1.0.0/metadata/annotations.yaml
  test/images/busybox-index/busybox/2.0.0/dockerfile
  test/images/busybox-index/busybox/2.0.0/manifests/csv.yaml
  test/images/busybox-index/busybox/2.0.0/metadata/annotations.yaml
Labels: approved, lgtm

#1657 [metrics] Dependency resolution metrics
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/instrumented_resolver.go
  pkg/controller/registry/resolver/instrumented_resolver_test.go
  pkg/metrics/metrics.go
  test/e2e/like_metric_matcher_test.go
  test/e2e/metrics_e2e_test.go
Labels: approved, area/dependency, lgtm

#1684 Bug 1860185: fix(install): account for installplans when calculating generation
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1692 Remove unnecessary ENV directives from base.Dockerfile.
  Makefile
  base.Dockerfile
Labels: approved, lgtm

#1695 change default catalog to index image
  deploy/chart/templates/0000_50_olm_17-upstream-operators.catalogsource.yaml
Labels: approved, lgtm

#1680 Remove unneeded toleration from catalog source pod
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm, ok-to-test

#1649 Add Conversion Webhook support for OLM
  pkg/controller/install/webhook.go
  test/e2e/csv_e2e_test.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm
