Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-02, with the labels that each got.

#1274 Bug 1797675: Refactoring rh-operator test directory
  Makefile
  test/rh-operators/metric_test.go
  test/rh-operators/operator_util.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1276 fix: update existing robot credentials
  test/e2e/skopeo.go
Labels: lgtm, size/XS

#1268 Bug 1768819: Fix configmap registry server readiness probe timeouts
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#1277 Bug 1798135: Fix cases where an operator's ready channel may never close.
  pkg/lib/queueinformer/config.go
  pkg/lib/queueinformer/queueinformer_operator.go
  pkg/lib/queueinformer/queueinformer_operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1282 mention OLMs features in the introduction
  README.md
Labels: lgtm, size/S

#1257 Bug 1800625: fix: add internal registry for catalog polling e2e test
  pkg/package-server/client/client.go
  pkg/package-server/client/util.go
  test/e2e/catalog_e2e_test.go
  test/e2e/registry.go
  test/e2e/skopeo.Dockerfile
  test/e2e/skopeo.go
  test/e2e/util_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1278 Bump version to 0.14.2
  OLM_VERSION
Labels: approved, lgtm, size/XS

#1252 Bug 1798645: fix(bundles): execute opm from tooling container
  Dockerfile
  Makefile
  cmd/catalog/main.go
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  go.mod
  local.Dockerfile
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
  pkg/controller/operators/catalog/operator.go
  test/e2e/installplan_e2e_test.go
  upstream.Dockerfile
  util/cpb/main.go
  util/cpb/main_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1284 Bug 1786471: fix(packagemanifests): Fix index key func to avoid key collision
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1300 Bug 1798051: Reinstate v1alpha2 operatorgroup
  deploy/chart/templates/0000_50_olm_10-operatorgroup.crd.yaml
  manifests/0000_50_olm_10-operatorgroup.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1307 Add some examples for Subscription config feature
  doc/design/subscription-config.md
Labels: approved, lgtm, size/M

#1314 Update README to include OLM-Book
  README.md
Labels: approved, lgtm, size/XS

#1319 Add stale bot
  .github/stale.yml
Labels: approved, lgtm, size/S

#1324 Fix kind detection for local builds.
  scripts/build_local.sh
Labels: approved, lgtm, size/S

#1323 Bug 1807128: Don't block on ctx.Done() if startup fails.
  pkg/lib/queueinformer/queueinformer_operator.go
  pkg/lib/queueinformer/queueinformer_operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1322 Bug 1799463: Duplicate packages in packageserver APIService response
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1308 Bug 1805570: Remove run-level 1 from olm and openshift-operators namespaces
  deploy/chart/templates/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-namespace.yaml
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, size/S

#1301 Bug 1804812: fix(deployment): deployment spec hash
  Makefile
  pkg/controller/install/deployment.go
  pkg/controller/install/deployment_test.go
  pkg/controller/install/errors.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/registry/grpc/source_test.go
  pkg/lib/filemonitor/cert_updater_test.go
  pkg/package-server/provider/registry_test.go
  test/e2e/operator_groups_e2e_test.go
  vendor/k8s.io/kubernetes/pkg/util/hash/BUILD
  vendor/k8s.io/kubernetes/pkg/util/hash/hash.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1311 [release-4.4] Bug 1805572: Remove run-level 1 from olm and openshift-operators namespaces
  deploy/chart/templates/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-namespace.yaml
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1316 Bug 1784024: Use generations to prevent duplicate InstallPlans
  Makefile
  deploy/chart/templates/0000_50_olm_04-installplan.crd.yaml
  deploy/chart/templates/0000_50_olm_05-subscription.crd.yaml
  pkg/api/apis/operators/installplan_types.go
  pkg/api/apis/operators/subscription_types.go
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/api/apis/operators/v1alpha1/subscription_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/api/apis/operators/v1alpha2/doc.go
  pkg/api/apis/operators/v1alpha2/operatorgroup_types.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions_test.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#1332 Unbreak the minikube mode of build_local.sh.
  .github/workflows/test-scripts.yml
  .gitignore
  Makefile
  scripts/build_local.sh
Labels: approved, lgtm, size/M

#1337 fix(make): build cpb as prereq of e2e-local
  Makefile
Labels: approved, lgtm, size/XS
