Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-09, with the labels that each got.

#1749 Bump OLM Version
  OLM_VERSION
Labels: approved, lgtm

#1737 Bug 1869717: fix(install): account for installplans when calculating generation
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/lib/clientfake/client_options.go
  pkg/lib/clientfake/meta.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1751 Genereate 0.16.1 changelog
  CHANGELOG.md
Labels: approved, lgtm

#1723 Bug 1866444: remove duplicate catalog source pod when polling
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1745 Bug 1874938: Set RevisionHistoryLimit per Deployment
  pkg/controller/install/deployment.go
  pkg/controller/install/deployment_test.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1746 Bug 1851095: Delete subscription metric when an operator is uninstalled
  pkg/controller/operators/catalog/subscription/syncer.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1734 [release-4.5] Bug 1870782: Retry conflicting catalog source pod update after fetching latest pod spec
  cmd/catalog/main.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/lib/controller-runtime/client/fake_ssa.go
  pkg/lib/controller-runtime/client/ssa.go
  pkg/lib/controller-runtime/client/ssa_test.go
  test/e2e/ctx/ctx.go
  test/e2e/metrics_e2e_test.go
  test/e2e/util_test.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1731 Bug 1867802: shorten catalog sync interval if polling is enabled
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/reconciler/grpc_polling.go
  pkg/controller/registry/reconciler/grpc_polling_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1755 Bug 1877835: update catalog image pull policy
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1761 Bug 1868712: OLM should reuse existing CA if they have not expired
  pkg/controller/install/certresources.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  test/e2e/webhook_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1756 doc: default polling behavior
  doc/design/default-polling.md
Labels: approved, lgtm

#1729 Bug 1870453: Should not compare the digest if cannot the new update pod's imageID
  pkg/controller/registry/reconciler/grpc.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#1767 BUG 1872584: Fix conversion webhooks
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/ocp/manifests/0.16.1/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/upstream/manifests/0.16.1/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/upstream/quickstart/crds.yaml
  go.mod
  go.sum
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  pkg/controller/install/certresources.go
  pkg/controller/install/webhook.go
  pkg/controller/operators/olm/apiservices.go
  pkg/package-server/client/openapi/zz_generated.openapi.go
  test/e2e/webhook_e2e_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1766 Bug 1873030: Make a subscription without at least one candidate fail resolution.
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1773 Bug 1881584: fix check from previous polling implementation
  pkg/controller/operators/catalog/operator.go
  test/e2e/catalog_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1775 Bug 1882077: Bump k8s dependencies to v0.18.9
  go.mod
  go.sum
  pkg/lib/operatorclient/client.go
  pkg/lib/operatorlister/lister.go
  scripts/update_mockgen.sh
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/structuredmerge.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/k8s.io/apiserver/pkg/storage/errors.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/parser.go
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1764 [release-4.5] Bug 1878307: shorten catalog sync interval if polling is enabled
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/reconciler/grpc_polling.go
  pkg/controller/registry/reconciler/grpc_polling_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
