Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-10, with the labels that each got.

#1781 Bug 1881222: Annotate CSVs with the properties used during dependency resolution.
  deploy/chart/crds/0000_50_olm_00-installplans.crd.yaml
  go.mod
  go.sum
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/operators/catalog/manifests.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/projection/properties.go
  pkg/controller/registry/resolver/projection/properties_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/steps.go
  test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_installplans.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1791 Bug 1884641: Regenerate downstream InstallPlan CRD manifest.
  manifests/0000_50_olm_00-installplans.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1480 doc: add reporting bugs doc and small nit improvements in the README
  README.md
  doc/dev/reporting_bugs.md
Labels: approved, kind/documentation, lgtm

#1778 Bug 1880359: [release-4.5] Bump 1.18.9
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/structuredmerge.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
  vendor/k8s.io/apiserver/pkg/storage/errors.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/parser.go
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/k8s.io/kube-openapi/pkg/util/proto/validation/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1798 Bug 1880473: remove extraneous manifests in installplan
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/step.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1797 Bug 1885398: Retrieve CA from conversion webhooks for CA Hash
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1799 Updating operator-lifecycle-manager builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#1741 fix typo in the error message
  pkg/controller/operators/catalog/step.go
Labels: approved, lgtm, ok-to-test

#1803 Bug 1885403: Improve transitionCSVState error logs
  pkg/controller/operators/olm/operator.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1808 Bug 1879248: OLM mounts CA Certs where Kubebuilder expects
  pkg/controller/install/certresources.go
  pkg/controller/operators/olm/apiservices.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1748 Bug 1875247: Add package check for the channel head querying
  pkg/controller/registry/resolver/resolver.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#1809 [release-4.5] Bug 1887944: ensure installplan step resource manifests reference configmaps
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/step.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1807 fix typo
  doc/design/dependency-resolution.md
Labels: approved, lgtm, needs-ok-to-test

#1816 Bug 1888073: prevent no-op hotlooping on Operators
  pkg/controller/operators/operator_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#1823 Bug 1889838: fix race in Operator reconcilation
  pkg/controller/operators/operator_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#1782 [release-4.4] Bug 1870784: Retry conflicting catalog source pod update after fetching latest pod spec
  cmd/catalog/main.go
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/lib/controller-runtime/client/fake_ssa.go
  pkg/lib/controller-runtime/client/ssa.go
  pkg/lib/controller-runtime/client/ssa_test.go
  test/e2e/util_test.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1765 [release-4.5] Bug 1878297: remove duplicate catalog source pod when polling
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1780 [release-4.5] Bug 1882444: remove extra polling check
  pkg/controller/operators/catalog/operator.go
  test/e2e/catalog_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1835 Bug 1891898: Set default, min, and max values on Webhook ports
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  go.mod
  go.sum
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  vendor/github.com/operator-framework/api/LICENSE
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/manifests/bundle.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/validation/errors/error.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/object.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/github.com/operator-framework/api/pkg/validation/validation.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1502 Replace assertions in Catalog-e2e to use Gomega's Matcher library
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm

#1500 Convert scoped_client_test to ginkgo
  test/e2e/scoped_client_test.go
  test/e2e/user_defined_sa_test.go
Labels: approved, lgtm

#1842 Bump version to 0.17.0.
  OLM_VERSION
Labels: approved, lgtm
