Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-06, with the labels that each got.

#1379 Doc: Remove legacy webhook proposal
  doc/contributors/design-proposals/webhooks.md
Labels: approved, lgtm

#1563 feat(resolver): don't build new clauses for weights
  pkg/controller/registry/resolver/sat/dict.go
Labels: approved, lgtm

#1501 cleanup: delete duplicated import in olm
  cmd/olm/cleanup.go
Labels: approved, lgtm, ok-to-test

#1443 Convert metrics_e2e_test to ginkgo
  test/e2e/catalog_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/metrics_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm

#1558 Reduce install.sh flakiness.
  scripts/install.sh
Labels: approved, lgtm

#1465 Catch failed Ginkgo assertion in test goroutine.
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#1542 Fix duplicated CRDs in quickstart manifests.
  .github/workflows/quickstart.yml
  Makefile
  deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-installplans.crd.yaml
  deploy/chart/crds/0000_50_olm_00-operatorgroups.crd.yaml
  deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  deploy/ocp/manifests/0.15.1/0000_50_olm_00-catalogsources.crd.yaml
  deploy/ocp/manifests/0.15.1/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/ocp/manifests/0.15.1/0000_50_olm_00-installplans.crd.yaml
  deploy/ocp/manifests/0.15.1/0000_50_olm_00-operatorgroups.crd.yaml
  deploy/ocp/manifests/0.15.1/0000_50_olm_00-subscriptions.crd.yaml
  deploy/upstream/manifests/0.15.1/0000_50_olm_00-catalogsources.crd.yaml
  deploy/upstream/manifests/0.15.1/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/upstream/manifests/0.15.1/0000_50_olm_00-installplans.crd.yaml
  deploy/upstream/manifests/0.15.1/0000_50_olm_00-operatorgroups.crd.yaml
  deploy/upstream/manifests/0.15.1/0000_50_olm_00-subscriptions.crd.yaml
  deploy/upstream/quickstart/crds.yaml
  deploy/upstream/quickstart/olm.yaml
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  scripts/copy_crds.sh
  scripts/package_quickstart.sh
Labels: approved, lgtm

#1539 Changelog for 0.15.1
  CHANGELOG.md
Labels: approved, lgtm

#1438 feat: add uninstall makefile target
  Makefile
  doc/install/install.md
Labels: approved, lgtm

#1512 Update prow ci logging for e2e tests
  test/e2e/e2e_test.go
Labels: approved, lgtm

#1551 [release-4.4] Bug 1840887: fix(resolver): don't pick operator from same package when resolve requiredAPI
  pkg/controller/registry/grpc/source.go
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/fakes/fake_registry_client.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  pkg/controller/registry/resolver/fakes/fake_registry_interface.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1578 chore(modules): bump api dep to v0.3.7
  deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-installplans.crd.yaml
  deploy/chart/crds/0000_50_olm_00-operatorgroups.crd.yaml
  deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  go.mod
  go.sum
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_catalogsources.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_installplans.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operatorgroups.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operators.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_subscriptions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/manifests/bundle.go
  vendor/github.com/operator-framework/api/pkg/manifests/bundleloader.go
  vendor/github.com/operator-framework/api/pkg/manifests/bundlemeta.go
  vendor/github.com/operator-framework/api/pkg/manifests/directory.go
  vendor/github.com/operator-framework/api/pkg/manifests/packagemanifest.go
  vendor/github.com/operator-framework/api/pkg/manifests/packagemanifestloader.go
  vendor/github.com/operator-framework/api/pkg/validation/doc.go
  vendor/github.com/operator-framework/api/pkg/validation/errors/error.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/bundle.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/manifests.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/package_manifest.go
  vendor/github.com/operator-framework/api/pkg/validation/validation.go
  vendor/modules.txt
Labels: approved, lgtm

#1571 [release-4.3] Bug 1843694: fix(resolver): don't pick operator from same package when resolve requiredAPI
  pkg/controller/registry/grpc/source.go
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/fakes/fake_registry_client.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  pkg/controller/registry/resolver/fakes/fake_registry_interface.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1579 Bug 1843652: fix(package-server): get icons from default channel
  pkg/package-server/storage/subresources.go
  pkg/package-server/storage/subresources_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1556 Bug 1841171: Update PkgManifest upon catsrc update
  pkg/package-server/provider/registry.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1562 beta.kubernetes.io/os deprecated since v1.14, removed in v1.19
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  deploy/upstream/quickstart/olm.yaml
  doc/design/building-your-csv.md
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
  pkg/package-server/provider/registry_test.go
  pkg/package-server/provider/testdata/manifests/prometheus/0.22.2/prometheusoperator.0.22.2.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#1583 Bug 1847540: resolve only default channels
  pkg/controller/registry/registry_client.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1572 [release-4.2] Bug 1843767: fix(resolver): don't pick operator from same package when resolve requiredAPI
  pkg/controller/registry/grpc/source.go
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/fakes/fake_registry_client.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  pkg/controller/registry/resolver/fakes/fake_registry_interface.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1568 Bug 1843678: Deleting a CSV removes related CSV metrics
  pkg/controller/operators/olm/operator.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1554 [release-4.2] Bug 1836447: Generation bug
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/resolver_test.go
  test/e2e/catalog_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1519 Bug 1822396: Delete subscription metric when an operator is uninstalled
  pkg/controller/operators/catalog/subscription/syncer.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1589 Bug 1849164: don't store full manifests in installplan status (for bundle images)
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
  pkg/controller/operators/catalog/manifests.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step.go
  pkg/controller/registry/resolver/rbac.go
  pkg/controller/registry/resolver/rbac_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1601 bump olm version to 0.16.0
  OLM_VERSION
Labels: approved, lgtm

#1598 Disable parallel e2e-local runs by default.
  .github/workflows/e2e-tests.yml
  x.mk
Labels: approved, lgtm

#1596 Replace assertions within async assertions.
  test/e2e/crd_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, lgtm

#1595 [release-4.4] Bug 1850632: don't store full manifests in installplan status (for bundle images)
  Makefile
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
  pkg/controller/operators/catalog/manifests.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/rbac.go
  pkg/controller/registry/resolver/rbac_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1569 Bug 1843703: Deleting a CSV removes related CSV metrics
  pkg/controller/operators/olm/operator.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1592 Remove failfast from operator e2e test
  Makefile
Labels: approved, lgtm

#1600 Update ocp manifests with latest template
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: approved, lgtm

#1610 Add more precise matching to the metric end-to-end tests.
  go.mod
  test/e2e/like_metric_matcher_test.go
  test/e2e/metrics_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#1611 fix: update README to point to the OLM book website
  README.md
Labels: approved, lgtm

#1603 Bug 1822396: Update metric when Subscription is updated
  pkg/metrics/metrics.go
  test/e2e/like_metric_matcher_test.go
  test/e2e/metrics_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
