Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-05, with the labels that each got.

#1312 [release-4.1] Bug 1805576: Remove run-level 1 from olm and openshift-operators namespaces
  deploy/chart/templates/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-namespace.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1432 [release-4.3] Bug 1821318: feat(packagemanifest): add default os/arch labels if not present
  pkg/package-server/provider/labels.go
  pkg/package-server/provider/labels_test.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
  pkg/package-server/storage/reststorage.go
  pkg/package-server/storage/subresources_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1486 [release-4.3] Bug 1818851: Prevent nil pointer dereference
  pkg/controller/operators/catalog/subscription/reconciler.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1489 Bug 1826446: (fix) Admission Webhook names must be unique
  deploy/chart/crds/0000_50_olm_00-catalogsources.yaml
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.yaml
  deploy/chart/crds/0000_50_olm_00-installplans.yaml
  deploy/chart/crds/0000_50_olm_00-operatorgroups.yaml
  deploy/chart/crds/0000_50_olm_00-subscriptions.yaml
  go.mod
  go.sum
  manifests/0000_50_olm_00-catalogsources.yaml
  manifests/0000_50_olm_00-clusterserviceversions.yaml
  manifests/0000_50_olm_00-installplans.yaml
  manifests/0000_50_olm_00-operatorgroups.yaml
  manifests/0000_50_olm_00-subscriptions.yaml
  pkg/controller/install/certresources.go
  pkg/controller/install/webhook.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/package-server/client/openapi/zz_generated.openapi.go
  test/e2e/csv_e2e_test.go
  test/e2e/webhook_e2e_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/bundle.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/validation.go
  vendor/github.com/operator-framework/operator-registry/pkg/containertools/dockerfilegenerator.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/bundle/validate.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/validation/bundle.go
  vendor/github.com/operator-framework/operator-registry/pkg/lib/validation/validation.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/bundle.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/imageinput.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1503 Bump OLM version to 0.15.0
  OLM_VERSION
Labels: approved

#1508 Bug 1818851: feat(catalogs): add spec validation for sourcetypes
  deploy/chart/templates/0000_50_olm_06-catalogsource.crd.yaml
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscription/reconciler.go
  pkg/controller/operators/catalog/subscription/reconciler_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1484 Bug 1827821: Generation bug 4.4 Backport
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
  pkg/controller/registry/resolver/resolver_test.go
  test/e2e/catalog_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1509 Bug 1833419: Detect WebhookDescription changes in CSVs
  pkg/controller/install/webhook.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  test/e2e/webhook_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1429 Convert gc_e2e_test.go to ginkgo
  test/e2e/gc_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#1515 Bug 1833426: Update Webhook E2E Namespace Labels
  test/e2e/webhook_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1424 Modify dynamic_resource_e2e_test to ginkgo
  test/e2e/catalog_e2e_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/dynamic_resource_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/metrics_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/scoped_client_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/user_defined_sa_test.go
  test/e2e/util_test.go
  test/e2e/webhook_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#1485 Bug 1827822: Generation bug 4.3
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/resolver_test.go
  test/e2e/catalog_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1513 Bug 1834136: fix(queues): use a single gc queue
  pkg/controller/operators/olm/operator.go
  pkg/lib/queueinformer/resourcequeue.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1520 Bug 1812019: PackageManifests should include Keywords
  pkg/package-server/apis/operators/packagemanifest.go
  pkg/package-server/apis/operators/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/packagemanifest.go
  pkg/package-server/apis/operators/v1/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/zz_generated.conversion.go
  pkg/package-server/apis/operators/v1/zz_generated.deepcopy.go
  pkg/package-server/apis/operators/zz_generated.deepcopy.go
  pkg/package-server/client/openapi/zz_generated.openapi.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1439 Convert package manifest e2e to ginkgo test
  test/e2e/catalog_e2e_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/user_defined_sa_test.go
  test/e2e/util_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#1472 Bug 1826443: Pod Config Deployment Hash Error
  pkg/controller/install/errors.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1533 Changelog for 0.15.0
  CHANGELOG.md
Labels: approved

#1525 Bug 1819308: Deleting a CSV removes related CSV metrics
  pkg/controller/operators/olm/operator.go
  pkg/metrics/metrics.go
  test/e2e/metrics_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1537 Bump OLM to 0.15.1
  OLM_VERSION
Labels: approved

#1516 Bug 1833195: delete bundle objects after CSV gets deleted
  pkg/controller/operators/catalog/operator.go
  pkg/lib/ownerutil/util.go
  test/e2e/gc_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1540 Bug 1838705: fix(webhook): Wire ContainerPort to Webhook
  go.mod
  go.sum
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1521 Bug 1834936: fix(resolver): don't pick operator from same package when resolve requiredAPI
  pkg/controller/registry/grpc/source.go
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/fakes/fake_registry_client.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
  pkg/controller/registry/resolver/fakes/fake_registry_interface.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/querier_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1550 Bug 1822040: Fix delay when OLM applies label to Namespaces
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1528 Bug 1836905: fix(queues): use a single gc queue
  pkg/controller/operators/olm/operator.go
  pkg/lib/queueinformer/resourcequeue.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1482 Bug 1823714: Update PkgManifest upon catsrc update
  pkg/package-server/provider/registry.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1549 Bug 1838054: fix(catalog): no operatorgroups in a namespace should be an error when resolving
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/lib/scoped/querier.go
  pkg/lib/scoped/querier_test.go
  test/e2e/installplan_e2e_test.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1535 Bug 1828550: add check for storage version changes when installing CRDs
  pkg/controller/operators/catalog/step.go
  pkg/lib/crd/storage.go
  pkg/lib/crd/storage_test.go
  test/e2e/crd_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
