Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-01, with the labels that each got.

#1216 Enable CGO and CGO_DEBUG
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#1217 Use vendored transitive dependencies for "go run" of vendored yq.
  Makefile
Labels: approved, lgtm, size/XS

#1161 feat: catalog source polling for updated registry image
  deploy/chart/templates/0000_50_olm_06-catalogsource.crd.yaml
  doc/design/catalog-polling.md
  go.sum
  manifests/0000_50_olm_06-catalogsource.crd.yaml
  pkg/api/apis/operators/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/types_test.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/api/apis/operators/zz_generated.deepcopy.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
  test/e2e/catalog_e2e_test.go
  test/e2e/skopeo.go
  test/e2e/util_test.go
Labels: approved, lgtm, size/XL

#1225 Reconcile manifests with templates.
  deploy/chart/templates/0000_50_olm_03-clusterserviceversion.crd.yaml
  deploy/chart/templates/0000_50_olm_04-installplan.crd.yaml
  deploy/chart/templates/0000_50_olm_05-subscription.crd.yaml
  deploy/chart/templates/0000_50_olm_10-operatorgroup.crd.yaml
  manifests/0000_50_olm_04-installplan.crd.yaml
Labels: approved, lgtm, size/M

#1097 doc: add internal image proposal
  doc/contributors/design-proposals/internal-objects.md
Labels: approved, lgtm, size/M

#1226 fix: refactor catalog polling to use updateStrategy field
  deploy/chart/templates/0000_50_olm_06-catalogsource.crd.yaml
  doc/design/catalog-polling.md
  manifests/0000_50_olm_06-catalogsource.crd.yaml
  pkg/api/apis/operators/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/api/apis/operators/v1alpha1/types_test.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/api/apis/operators/zz_generated.deepcopy.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/reconciler.go
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm, size/L

#1220 feat(packageserver): support label queries and copy CSV labels onto the package
  pkg/package-server/provider/interfaces.go
  pkg/package-server/provider/labels.go
  pkg/package-server/provider/labels_test.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
  pkg/package-server/storage/reststorage.go
  pkg/package-server/storage/subresources_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, lgtm, size/L

#1232 fix: typo in catalog polling doc
  doc/design/catalog-polling.md
Labels: size/XS

#1229 Remove pyjq and yq from the release documentation prereqs.
  doc/design/release.md
Labels: approved, lgtm, size/XS

#1219 Only enable CGO for prod builds
  Dockerfile
  Makefile
Labels: approved, lgtm, size/S

#1235 Update internal objects proposal to use annotation on CSV instead of CRD
  doc/contributors/design-proposals/internal-objects.md
Labels: approved, lgtm, size/S

#1228 Update release script to require version 3 of helm.
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_03-clusterserviceversion.crd.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  manifests/image-references
  scripts/package_release.sh
Labels: approved, lgtm, size/L

#1231 Fix IPv6 incompatibility in TestGrpcAddressCatalogSource.
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm, size/XS

#1233 adding e2e test framework for rh-operator metrics
  Makefile
  test/e2e/rh-operators/metric_test.go
  test/e2e/rh-operators/operator_util.go
Labels: approved, lgtm, size/XL

#1248 Bump version to 0.14.0.
  OLM_VERSION
Labels: approved, lgtm, size/XS

#1250 Fix overly broad .gitignore pattern that was excluding a vendored pac…
  .gitignore
  vendor/helm.sh/helm/v3/pkg/release/hook.go
  vendor/helm.sh/helm/v3/pkg/release/info.go
  vendor/helm.sh/helm/v3/pkg/release/mock.go
  vendor/helm.sh/helm/v3/pkg/release/release.go
  vendor/helm.sh/helm/v3/pkg/release/responses.go
  vendor/helm.sh/helm/v3/pkg/release/status.go
Labels: approved, lgtm, size/L

#1264 Bump version to 0.14.1.
  OLM_VERSION
Labels: lgtm, size/XS

#1171 Bug 1777144: packageserver update fails to adopt APIService
  cmd/olm/cleanup.go
  cmd/olm/cleanup_test.go
  pkg/controller/operators/olm/apiservices.go
  pkg/lib/ownerutil/util.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1267 Bug 1789920: Fix bad opgroup annotations
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1266 Generate changelog for 0.14.0 and 0.14.1.
  CHANGELOG.md
Labels: approved, lgtm, size/L

#1261 chore(ci): update owners
  OWNERS
Labels: approved, size/S
