Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-03, with the labels that each got.

#1340 Bug 1809294: Update subscription_sync_count to include the package name
  pkg/controller/operators/catalog/subscription/syncer.go
  pkg/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#1341 Bug 1808113: Fix OwnerReferences for bundled CRs
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/testdata/prometheusrule.cr.yaml
  pkg/controller/operators/catalog/testdata/prometheusrule.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1353 Bug 1810698: feat(jitter): add jitter to controllers to smooth out our spiky resource
  cmd/olm/main.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/olm/config.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/lib/queueinformer/jitter.go
  pkg/lib/queueinformer/jitter_test.go
  scripts/build_local.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1292 [release-4.3] Bug 1803135: fix(packagemanifests): Fix index key func to avoid key collision
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#1310 [release-4.3] Bug 1805574: Remove run-level 1 from olm and openshift-operators namespaces
  deploy/chart/templates/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-namespace.yaml
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1348 Bug 1797747: Make provided API ClusterRoles be owned by the corresponding API.
  pkg/api/apis/operators/operatorgroup_types.go
  pkg/api/apis/operators/v1/operatorgroup_types.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/lib/ownerutil/util.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#1313 add link to olm-book definition of subscription
  doc/design/subscription-config.md
Labels: approved, lgtm

#1334 Tolerations & Resources Override using .Subscription.Config
  doc/design/subscription-config.md
  pkg/controller/operators/olm/overrides/config.go
  pkg/controller/operators/olm/overrides/initializer.go
  pkg/controller/operators/olm/overrides/inject.go
  pkg/controller/operators/olm/overrides/inject_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm, ok-to-test, size/L

#1371 manifests(prometheus): failing operators should be a warning
  deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
Labels: approved, lgtm

#1073 Lock down package server runtime environment
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  deploy/upstream/values.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/S

#1339 Bug 1805412: Support multiple APIServices on a single deployment
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#1390 Ignore differences in CSV .status.conditions in unit tests.
  pkg/controller/operators/olm/operator_test.go
Labels: approved, lgtm

#1381 Fix typo in subscription.crd template file
  deploy/chart/templates/0000_50_olm_05-subscription.crd.yaml
  manifests/0000_50_olm_05-subscription.crd.yaml
Labels: approved, lgtm

#1389 Bug 1814457: fix(catsrc): remove limits on catalogsource pods
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm

#1388 Add e2e test for multiple APIServices on a pod
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm

#1396 [release-4.4] Bug 1805414: Support multiple APIServices on a single deployment
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1398 Add OG label to namespaces in OperatorGroup
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, lgtm

#1401 Fix installplan error when installing from bundles
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_03-clusterserviceversion.crd.yaml
  manifests/0000_50_olm_04-installplan.crd.yaml
  manifests/0000_50_olm_05-subscription.crd.yaml
  manifests/0000_50_olm_06-catalogsource.crd.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_10-operatorgroup.crd.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/image-references
  pkg/api/apis/operators/installplan_types.go
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm

#1363 [release-4.3] Bug 1807631: Duplicate packages in packageserver APIService response
  pkg/package-server/provider/interfaces.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
  pkg/package-server/storage/reststorage.go
  pkg/package-server/storage/subresources_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#1224 Add alm-examples-metadata
  doc/design/building-your-csv.md
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#1373 [release-4.2] Bug 1797021: Fix bad opgroup annotations
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  test/e2e/operator_groups_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1411 Add tests for GC assumptions.
  test/e2e/convert_suite_test.go
  test/e2e/dsl/dsl.go
  test/e2e/gc_e2e_test.go
  vendor/github.com/onsi/gomega/go.mod
Labels: approved, lgtm

#1408 Reconcile Namespace OG Labels in Namespace Syncer
  pkg/api/apis/operators/v1/operatorgroup_types.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm

#1387 Add more CSV information to the PackageManifest
  pkg/package-server/apis/operators/packagemanifest.go
  pkg/package-server/apis/operators/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/packagemanifest.go
  pkg/package-server/apis/operators/v1/packagemanifest_types.go
  pkg/package-server/apis/operators/v1/zz_generated.conversion.go
  pkg/package-server/apis/operators/v1/zz_generated.deepcopy.go
  pkg/package-server/apis/operators/zz_generated.deepcopy.go
  pkg/package-server/client/openapi/zz_generated.openapi.go
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved, lgtm

#1414 Bug 1817833: Add spec validation and improved status for CatalogSources
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscription/reconciler.go
  pkg/controller/operators/catalog/subscription/reconciler_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, lgtm
