Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-12, with the labels that each got.

#1884 Bug 1898500: Support InstallPlan steps upgrading existing ClusterIP Services.
  pkg/lib/operatorclient/service.go
  pkg/lib/operatorclient/service_test.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1878 Add authentication for private index images
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/configmap_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
Labels: approved, lgtm

#1875 Create operatorcondition for operator
  cmd/olm/manager.go
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-operatorconditions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  deploy/upstream/quickstart/crds.yaml
  go.mod
  go.sum
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  pkg/api/client/clientset/versioned/typed/operators/v1/fake/fake_operatorcondition.go
  pkg/api/client/clientset/versioned/typed/operators/v1/fake/fake_operators_client.go
  pkg/api/client/clientset/versioned/typed/operators/v1/generated_expansion.go
  pkg/api/client/clientset/versioned/typed/operators/v1/operatorcondition.go
  pkg/api/client/clientset/versioned/typed/operators/v1/operators_client.go
  pkg/api/client/informers/externalversions/generic.go
  pkg/api/client/informers/externalversions/operators/v1/interface.go
  pkg/api/client/informers/externalversions/operators/v1/operatorcondition.go
  pkg/api/client/listers/operators/v1/expansion_generated.go
  pkg/api/client/listers/operators/v1/operatorcondition.go
  pkg/controller/operators/adoption_controller.go
  pkg/controller/operators/operator_controller.go
  pkg/controller/operators/operatorcondition_controller.go
  pkg/controller/operators/operatorcondition_controller_test.go
  pkg/controller/operators/operatorconditiongenerator_controller.go
  pkg/controller/operators/operatorconditiongenerator_controller_test.go
  pkg/controller/operators/suite_test.go
  pkg/lib/ownerutil/util.go
  vendor/github.com/operator-framework/api/crds/defs.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operatorconditions.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_subscriptions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/errors/error.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/modules.txt
Labels: approved, lgtm

#1881 Bug 1857877: check the service account owner in the requirement
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, ok-to-test

#1885 Add OLM support for the Upgradeable OperatorCondition and Admin overrides
  go.mod
  go.sum
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorconditions.go
  pkg/lib/operatorlister/lister.go
  pkg/lib/operatorlister/operatorcondition.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_operators_v1lister.go
  test/e2e/operator_condition_e2e_test.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/modules.txt
Labels: approved, lgtm

#1896 Bug 1905640: fix(e2e): Fix subscription manual approval flaky test
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1892 Bug 1905599: Preserve original .status.lastUpdateTime in copied CSVs.
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/operatorgroup_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1901 Bug 1903034: Reduce log noise from OLM
  cmd/olm/main.go
  cmd/olm/manager.go
  pkg/controller/operators/olm/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1902 Bug 1906416: Preserve original .status.lastUpdateTime in copied CSVs.
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/operatorgroup_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1899 Bug 1906134: Don't create OperatorConditions for copied CSVs
  pkg/controller/operators/operatorconditiongenerator_controller.go
  pkg/controller/operators/operatorconditiongenerator_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1904 Bug 1905299: fix(olm): Verify ServiceAccount ownership before installing deployment
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1890 Bug 1904583: Check sa owner 46
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1894 [release-4.5] Bug 1905137: Recreate pending installplan if deleted before approval
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscription/reconciler_test.go
  pkg/controller/operators/catalog/subscription/state.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1913 Bug 1907381: CSV Annotations override pod annotations
  pkg/controller/install/deployment.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1900 Bug 1910160: Create OperatorConditions for CSVs being installed
  pkg/controller/operators/operatorcondition_controller.go
  pkg/controller/operators/operatorcondition_controller_test.go
  test/e2e/operator_condition_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1911 Bug 1907792: Change the OperatorUpgradeable condition to Upgradeable
  go.mod
  go.sum
  pkg/controller/operators/olm/operatorconditions.go
  test/e2e/operator_condition_e2e_test.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorcondition_types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
