Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2020-04, with the labels that each got.

#1350 Clarify roles and adds info about Package Server
  doc/design/architecture.md
Labels: approved, lgtm, ok-to-test, size/M

#1367 Bug 1809661: Update subscription_sync_count to include the package name
  pkg/controller/operators/catalog/subscription/syncer.go
  pkg/controller/operators/catalog/subscription/syncer_test.go
  pkg/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1309 [release-4.2] Bug 1805575: Remove run-level 1 from olm and openshift-operators namespaces
  deploy/chart/templates/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-namespace.yaml
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1418 Create APIService after API server deployment
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
Labels: approved, lgtm

#1428 [release-4.4] Bug 1818850: Add spec validation and improved status for CatalogSources
  pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/subscription/reconciler.go
  pkg/controller/operators/catalog/subscription/reconciler_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1444 fix: use busybox csv for catalog polling e2e test
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm

#1434 feat: support configmap creation from the bundle
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step_ensurer.go
  pkg/lib/operatorclient/client.go
  pkg/lib/operatorclient/configmap.go
  pkg/lib/operatorclient/operatorclientmocks/mock_client.go
Labels: approved, lgtm

#1442 Add BugZilla component to OWNERS file
  OWNERS
Labels: approved, lgtm

#1446 chore(docker): add kubebuilder to base image
  base.Dockerfile
Labels: approved, lgtm

#1436 Admission webhoooks
  deploy/chart/crds/0000_50_olm_03-clusterserviceversion.crd.yaml
  deploy/chart/crds/0000_50_olm_04-installplan.crd.yaml
  deploy/chart/crds/0000_50_olm_06-catalogsource.crd.yaml
  manifests/0000_50_olm_03-clusterserviceversion.crd.yaml
  manifests/0000_50_olm_05-subscription.crd.yaml
  manifests/0000_50_olm_06-catalogsource.crd.yaml
  pkg/api/apis/operators/clusterserviceversion_types.go
  pkg/api/apis/operators/v1/operatorgroup_types.go
  pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/api/wrappers/deployment_install_client.go
  pkg/api/wrappers/wrappersfakes/fake_install_strategy_deployment_interface.go
  pkg/controller/install/apiservice.go
  pkg/controller/install/certresources.go
  pkg/controller/install/deployment.go
  pkg/controller/install/deployment_test.go
  pkg/controller/install/resolver.go
  pkg/controller/install/webhook.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/requirements.go
  pkg/fakes/fake_strategy_resolver.go
  pkg/package-server/client/openapi/zz_generated.openapi.go
  test/e2e/csv_e2e_test.go
Labels: approved

#1452 Fix upstream image build
  .github/workflows/test-scripts.yml
  upstream.Dockerfile
Labels: approved, lgtm

#1451 Added Github workflow for running e2e tests
  .github/workflows/e2e-tests.yml
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm

#1454 Regenerate the chart embedded in the test installer as needed.
  test/e2e/assets/chart/.gitignore
  test/e2e/assets/chart/zz_chart.go
Labels: approved, lgtm

#1416 feat: support v1 CRD objects in OLM
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  pkg/lib/crd/serialize.go
  pkg/lib/crd/version.go
  pkg/lib/index/api.go
  pkg/lib/operatorclient/client.go
  pkg/lib/operatorclient/operatorclientmocks/mock_client.go
  pkg/lib/operatorlister/customresourcedefinition.go
  pkg/lib/operatorlister/lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_apiextensions_v1lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_operator_lister.go
  test/e2e/crd_upgrade_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/user_defined_sa_test.go
  vendor/github.com/onsi/gomega/go.mod
Labels: approved, lgtm

#1455 fix: add empty go file to packge to fix make verify
  test/e2e/assets/chart/doc.go
Labels: approved

#1440 Add initial SAT solver package.
  go.mod
  go.sum
  pkg/controller/registry/resolver/sat/bench_test.go
  pkg/controller/registry/resolver/sat/constraints.go
  pkg/controller/registry/resolver/sat/constraints_test.go
  pkg/controller/registry/resolver/sat/dict.go
  pkg/controller/registry/resolver/sat/solve.go
  pkg/controller/registry/resolver/sat/solve_test.go
  vendor/github.com/irifrance/gini/.travis.yml
  vendor/github.com/irifrance/gini/LICENSE
  vendor/github.com/irifrance/gini/README.md
  vendor/github.com/irifrance/gini/dimacs/cfilt.go
  vendor/github.com/irifrance/gini/dimacs/cnf.go
  vendor/github.com/irifrance/gini/dimacs/doc.go
  vendor/github.com/irifrance/gini/dimacs/icnf.go
  vendor/github.com/irifrance/gini/dimacs/int.go
  vendor/github.com/irifrance/gini/dimacs/lit.go
  vendor/github.com/irifrance/gini/dimacs/solve.go
  vendor/github.com/irifrance/gini/dimacs/vis.go
  vendor/github.com/irifrance/gini/doc.go
  vendor/github.com/irifrance/gini/gini.go
  vendor/github.com/irifrance/gini/go.mod
  vendor/github.com/irifrance/gini/go.sum
  vendor/github.com/irifrance/gini/inter/doc.go
  vendor/github.com/irifrance/gini/inter/s.go
  vendor/github.com/irifrance/gini/inter/solve.go
  vendor/github.com/irifrance/gini/internal/xo/active.go
  vendor/github.com/irifrance/gini/internal/xo/cdat.go
  vendor/github.com/irifrance/gini/internal/xo/cdb.go
  vendor/github.com/irifrance/gini/internal/xo/cgc.go
  vendor/github.com/irifrance/gini/internal/xo/chd.go
  vendor/github.com/irifrance/gini/internal/xo/cloc.go
  vendor/github.com/irifrance/gini/internal/xo/ctl.go
  vendor/github.com/irifrance/gini/internal/xo/derive.go
  vendor/github.com/irifrance/gini/internal/xo/dimacs.go
  vendor/github.com/irifrance/gini/internal/xo/doc.go
  vendor/github.com/irifrance/gini/internal/xo/guess.go
  vendor/github.com/irifrance/gini/internal/xo/luby.go
  vendor/github.com/irifrance/gini/internal/xo/phases.go
  vendor/github.com/irifrance/gini/internal/xo/s.go
  vendor/github.com/irifrance/gini/internal/xo/stats.go
  vendor/github.com/irifrance/gini/internal/xo/tracer.go
  vendor/github.com/irifrance/gini/internal/xo/trail.go
  vendor/github.com/irifrance/gini/internal/xo/vars.go
  vendor/github.com/irifrance/gini/internal/xo/watch.go
  vendor/github.com/irifrance/gini/logic/c.go
  vendor/github.com/irifrance/gini/logic/card.go
  vendor/github.com/irifrance/gini/logic/doc.go
  vendor/github.com/irifrance/gini/logic/roll.go
  vendor/github.com/irifrance/gini/logic/s.go
  vendor/github.com/irifrance/gini/s.go
  vendor/github.com/irifrance/gini/sv.go
  vendor/github.com/irifrance/gini/z/c.go
  vendor/github.com/irifrance/gini/z/doc.go
  vendor/github.com/irifrance/gini/z/dv.go
  vendor/github.com/irifrance/gini/z/lit.go
  vendor/github.com/irifrance/gini/z/var.go
  vendor/modules.txt
Labels: approved

#1460 Fix failing E2E bundle unpacking test.
  e2e.Dockerfile
Labels: approved, lgtm

#1447 feat: support secrets from bundle
  pkg/api/apis/operators/installplan_types.go
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step_ensurer.go
  pkg/controller/registry/resolver/steps.go
Labels: approved, lgtm

#1458 Add an operator cache for use by the resolver.
  pkg/controller/registry/grpc/source.go
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/cache_test.go
Labels: approved, lgtm

#1473 BUG 1825349: Generation required bug
  deploy/chart/templates/0000_50_olm_04-installplan.crd.yaml
  manifests/0000_50_olm_04-installplan.crd.yaml
  pkg/api/apis/operators/v1alpha1/installplan_types.go
  test/e2e/catalog_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1483 Bug 1818788: Fix Operator Generation code
  pkg/controller/registry/resolver/evolver.go
  pkg/controller/registry/resolver/evolver_test.go
  pkg/controller/registry/resolver/resolver_test.go
  test/e2e/catalog_e2e_test.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#1470 Bug 1825330: support creating v1beta CRDs to avoid data loss
  cmd/olm/cleanup_test.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step.go
  pkg/lib/crd/serialize.go
  pkg/lib/crd/unmarshal.go
  pkg/lib/crd/version.go
  pkg/lib/index/api.go
  test/e2e/crd_e2e_test.go
  test/e2e/crd_upgrade_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/util_test.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm
