Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-09, with the labels that each got.

#2337 Reduce resolver dependencies on operator-registry and operator-lifecycle-manager.
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/cache/cache.go
  pkg/controller/registry/resolver/cache/cache_test.go
  pkg/controller/registry/resolver/cache/operators.go
  pkg/controller/registry/resolver/cache/operators_test.go
  pkg/controller/registry/resolver/cache/predicates.go
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/instrumented_resolver.go
  pkg/controller/registry/resolver/instrumented_resolver_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/source_registry.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/fakes/fake_resolver.go
Labels: approved, lgtm

#2338 Remove unneeded replace pin for sigs.k8s.io/structured-merge-diff
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#2216 Emit CSV metric on startup
  cmd/olm/main.go
  pkg/controller/operators/olm/operator.go
  test/e2e/metrics_e2e_test.go
Labels: ok-to-test, approved, lgtm

#2340 Remove hardcoded references to the registry gRPC API from the resolver packages.
  pkg/controller/operators/olm/labeler.go
  pkg/controller/operators/olm/labeler_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/cache/cache_test.go
  pkg/controller/registry/resolver/cache/operators.go
  pkg/controller/registry/resolver/cache/operators_test.go
  pkg/controller/registry/resolver/cache/predicates.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/source_registry.go
  pkg/controller/registry/resolver/source_registry_test.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
Labels: approved, lgtm

#2158 .github/workflows: Separate out the e2e jobs into workflows
  .github/workflows/build.yml
  .github/workflows/e2e-kind.yml
  .github/workflows/e2e-minikube.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/test-scripts.yml
  .github/workflows/unit.yml
  .github/workflows/verify.yml
Labels: approved, lgtm

#2345 doc(readme): add chat badge
  README.md
Labels: approved, lgtm

#2348 Bump OLM_VERSION to 0.19.0
  OLM_VERSION
Labels: approved, lgtm

#2347 .github/workflows: Don't run CI checks for markdown-only updates
  .github/workflows/build.yml
  .github/workflows/e2e-kind.yml
  .github/workflows/e2e-minikube.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/unit.yml
  .github/workflows/verify.yml
Labels: approved, lgtm

#2329 [release-4.7] Bug 1969320: remove spec.cleanup from ClusterServiceVersion
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: ok-to-test, approved, lgtm, cherry-pick-approved, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#2314 [release-4.7] Bug 1989780: installplans: retry crd updates on conflicts
  pkg/controller/install/webhook.go
  pkg/controller/operators/catalog/step.go
Labels: approved, lgtm, cherry-pick-approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#2346 Introduce a sanity workflow for checking static linting violations in CI
  .github/workflows/sanity.yaml
  Makefile
  pkg/controller/certs/certs.go
  pkg/controller/operators/catalog/installplan_sync.go
  pkg/controller/operators/openshift/clusteroperator_controller_test.go
  pkg/controller/operators/operatorcondition_controller_test.go
  pkg/controller/operators/operatorconditiongenerator_controller_test.go
  pkg/controller/registry/grpc/source.go
  pkg/controller/registry/resolver/rbac.go
  pkg/controller/registry/resolver/rbac_test.go
  pkg/lib/controller-runtime/client/ssa_test.go
  pkg/lib/crd/storage.go
  pkg/lib/crd/storage_test.go
  pkg/lib/crd/version.go
  pkg/lib/operatorlister/configmap.go
  pkg/lib/operatorlister/operatorgroup.go
  pkg/lib/operatorlister/pod.go
  pkg/package-server/provider/registry.go
  test/e2e/registry.go
Labels: approved, lgtm

#2344 Update the CONTRIBUTING.md guidelines
  CONTRIBUTING.md
Labels: approved, lgtm

#2300 .github/workflows: Bump the docker/build-push-action to the v2 version
  .github/workflows/build.yml
Labels: approved, lgtm

#2356 .github/workflows: Don't run the sanity jobs for markdown-only updates
  .github/workflows/sanity.yaml
Labels: approved, lgtm

#2354 Makefile,test: Remove the test/rh-operators directory
  Makefile
  test/rh-operators/metric_test.go
  test/rh-operators/operator_util.go
Labels: approved, lgtm

#2361 Add summary and description for prometheus alerts
  deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
  pkg/controller/operators/catalog/testdata/prometheusrule.cr.yaml
Labels: approved, lgtm

#2366 test/e2e: Remove the unused e2e.sh and tap.jq files
  test/e2e/e2e.sh
  test/e2e/tap.jq
Labels: approved, lgtm

#2370 Add olm-managed label to configmap-based catalogsource for e2e test
  test/e2e/util_test.go
Labels: approved, lgtm

#2349 pkg/controller: Fix panic when creating cluster-scoped RBAC in OG controller
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm

#2371 Update default catalog namespace
  cmd/catalog/main.go
Labels: approved, lgtm

#2365 Integrate goreleaser to produce draft releases when new tags are pushed
  .github/workflows/goreleaser.yaml
  .gitignore
  .goreleaser.yml
  Dockerfile.goreleaser
  Makefile
Labels: approved, lgtm

#2364 Introduce GRPC_PROXY EnvVar Support
  go.mod
  pkg/controller/registry/grpc/source.go
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/modules.txt
Labels: approved, lgtm

#2369 Remove oudated subscription update logic to improve resolution delay
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/querier.go
  pkg/controller/operators/catalog/querier_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#2382 pkg/controller: Migrate to using a read lock instead of a readwrite lock when checking for any namespace caching errors
  pkg/controller/registry/resolver/cache/cache.go
Labels: approved, lgtm
