Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-07, with the labels that each got.

#2215 (fix)InstallPlan: Do not tranisition IP to failed on OG/SA failure
  doc/design/architecture.md
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm

#2238 Bump OLM to v0.18.3
  OLM_VERSION
Labels: approved, lgtm

#2243 doc/design: Add a version prefix to the release tag in release.md
  doc/design/release.md
Labels: approved, lgtm

#2241 Remove cleanup from startup
  cmd/olm/cleanup.go
  cmd/olm/cleanup_test.go
  cmd/olm/main.go
Labels: approved, lgtm

#2231 doc/design: Fix broken milestone link in the release.md
  doc/design/release.md
Labels: approved, lgtm

#2119 Don't cache secrets not managed by olm
  pkg/controller/install/certresources.go
  pkg/controller/install/certresources_test.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, lgtm, performance

#2222 feat(og): Project OperatorGroup errors to status conditions
  deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-installplans.crd.yaml
  deploy/chart/crds/0000_50_olm_00-operatorconditions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-operatorgroups.crd.yaml
  deploy/chart/crds/0000_50_olm_00-operators.crd.yaml
  deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  go.mod
  go.sum
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/lib/scoped/syncer.go
  vendor/github.com/operator-framework/api/crds/defs.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_catalogsources.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_installplans.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operatorconditions.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operatorgroups.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operators.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_subscriptions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/v2/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/modules.txt
Labels: approved, lgtm

#2248 Filter secrets from Operator reconciler
  cmd/olm/manager.go
Labels: approved, lgtm, performance

#2249 Remove test dependencies on the v1beta1 CRD API.
  .github/workflows/e2e-tests.yml
  test/e2e/bundle_e2e_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/data/catalog.new.yaml
  test/e2e/data/catalog.old.yaml
  test/e2e/data/kiali-image-bundle/manifests/kiali.crd.yaml
  test/e2e/data/kiali-image-bundle/manifests/kiali.monitoringdashboards.crd.yaml
  test/e2e/data/kiali-manifests/0.18.1/kiali.crd.yaml
  test/e2e/data/kiali-manifests/1.1.0/kiali.crd.yaml
  test/e2e/data/kiali-manifests/1.1.0/kiali.monitoringdashboards.crd.yaml
  test/e2e/data/kiali-manifests/1.3.1/kiali.crd.yaml
  test/e2e/data/kiali-manifests/1.3.1/kiali.monitoringdashboards.crd.yaml
  test/e2e/data/kiali-manifests/1.4.2/kiali.crd.yaml
  test/e2e/data/kiali-manifests/1.4.2/kiali.monitoringdashboards.crd.yaml
  test/e2e/deprecated_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/metrics_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/operator_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/testdata/vpa/crd.yaml
  test/e2e/testdata/vpa/vpa_bindata.go
  test/e2e/user_defined_sa_test.go
  test/e2e/util_test.go
  test/e2e/webhook_e2e_test.go
  test/images/busybox-index/busybox-dependency/1.0.0/manifests/foo.crd.yaml
  test/images/busybox-index/busybox-dependency/2.0.0/manifests/foo.crd.yaml
Labels: approved, lgtm

#2254 Translate legacy "bundle dependencies" to properties.
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/operators_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm

#2225 Require valid client certificate for profiling endpoints.
  cmd/catalog/main.go
  cmd/olm/main.go
  deploy/chart/templates/0000_50_olm_02-services.yaml
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  deploy/chart/values.yaml
  pkg/lib/filemonitor/cabundle_updater.go
  pkg/lib/filemonitor/cert_updater.go
  pkg/lib/filemonitor/cert_updater_test.go
  pkg/lib/filemonitor/watcher.go
  pkg/lib/profile/profile.go
  pkg/lib/server/server.go
  test/e2e/installplan_e2e_test.go
  test/e2e/metrics_e2e_test.go
Labels: approved, lgtm

#2256 Remove unused trace log from LegacySyncHandler.
  pkg/lib/queueinformer/queueinformer.go
Labels: approved, lgtm

#2260 Explain unique replaces chain requirement in channel sort errors.
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm

#2261 Correctly omit skipped channel entries during resolution.
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm

#2263 Fix ClusterOperator selector for excluding copied CSVs.
  pkg/controller/operators/openshift/helpers.go
  pkg/controller/operators/openshift/helpers_test.go
Labels: approved, lgtm

#2264 Don't cache copied CSVs in the controller-runtime-based controllers.
  cmd/olm/manager.go
Labels: approved, lgtm

#2262 feat(sub): Include IP failure condition message in sub status condition
  pkg/controller/operators/catalog/subscription/state.go
  pkg/controller/operators/catalog/subscription/state_test.go
Labels: approved, lgtm

#2266 Add a resolver test for completely disjoint graphs within a channel
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm

#2268 Update extractMessage
  pkg/controller/operators/catalog/subscription/state.go
  pkg/controller/operators/catalog/subscription/state_test.go
Labels: approved, lgtm

#2270 fix(openshift): handle unquoted short max versions
  pkg/controller/operators/openshift/clusteroperator_controller_test.go
  pkg/controller/operators/openshift/helpers.go
  pkg/controller/operators/openshift/helpers_test.go
  pkg/controller/registry/resolver/projection/properties_test.go
Labels: approved, lgtm

#2267 Use metadata-only watches when possible for Operator component APIs.
  cmd/olm/manager.go
  go.mod
  go.sum
  pkg/controller/operators/adoption_controller.go
  pkg/controller/operators/components.go
  pkg/controller/operators/decorators/operator.go
  pkg/controller/operators/decorators/operator_test.go
  pkg/controller/operators/operator_controller.go
  pkg/controller/operators/suite_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/metadata_infomer_wrapper.go
Labels: approved, lgtm

#2272 Remove unused scripts
  scripts/k8s_yaml_to_ansible_install.sh
  scripts/k8s_yaml_to_ansible_remove.sh
  scripts/kube_deps.sh
  scripts/pull_or_build_rh.sh
Labels: approved, lgtm

#2275 Update catalog deployment template
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
Labels: approved, lgtm

#2251 check if server resource exists when installing OLM supported resources
  pkg/controller/operators/catalog/not_found.go
  pkg/controller/operators/catalog/operator.go
  test/e2e/deprecated_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm

#2276 Update OLM Deployment template
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
Labels: approved, lgtm

#2278 Add optional opm image argument to chart template
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
Labels: approved, lgtm

#2279 Update getMetricsFromPort to infer port number
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  test/e2e/installplan_e2e_test.go
  test/e2e/metrics_e2e_test.go
Labels: approved, lgtm

#2271 Add filter labels to catalog pod cache
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm

#2269 feat(sub): Indicate resolution conflicts on Subscription statuses
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/modules.txt
Labels: approved, lgtm

#2258 feat(resolver): Indicate dependency class in resolution constraint text
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/cache_test.go
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/predicates.go
  pkg/controller/registry/resolver/predicates_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
Labels: approved, lgtm

#2284 Drop inline manifests from resolver cache.
  pkg/controller/registry/resolver/operators.go
Labels: approved, lgtm

#2277 Hash and prune copied CSVs in olm-operator.
  pkg/controller/operators/internal/pruning/listerwatcher.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/operatorgroup_test.go
Labels: approved, lgtm

#2274 Add managed label to configmap to reduce cache size
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
Labels: approved, lgtm

#2285 Prune unused ClusterServiceVersion fields from catalog's informer.
  pkg/controller/operators/catalog/operator.go
  pkg/lib/index/api.go
Labels: approved, lgtm

#2290 Expose errors generated while retrieving catalog content.
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/cache_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/types.go
Labels: approved, lgtm

#2291 resolver: remove legacy support for fallback parsing of CSVs
  pkg/controller/registry/resolver/operators.go
  pkg/controller/registry/resolver/operators_test.go
Labels: approved, do-not-merge/hold, lgtm

#2298 doc/design: Update the changelog release documentation
  doc/design/release.md
Labels: approved, lgtm

#2299 .github/workflows: Avoid running the e2e-tests workflow on doc-only PRs
  .github/workflows/e2e-tests.yml
Labels: approved, lgtm

#2293 Retry CRD updates on conflicts
  pkg/controller/install/webhook.go
  pkg/controller/operators/catalog/step.go
Labels: approved, lgtm

#2281 Catalog switcher
  cmd/catalog/main.go
  deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalogtemplate/operator.go
  pkg/lib/catalogsource/catalogsource_update.go
  pkg/lib/catalogsource/image_template.go
  pkg/lib/catalogsource/image_template_test.go
  scripts/copy_crds.sh
  test/e2e/catalog_e2e_test.go
  vendor/github.com/distribution/distribution/LICENSE
  vendor/github.com/distribution/distribution/reference/helpers.go
  vendor/github.com/distribution/distribution/reference/normalize.go
  vendor/github.com/distribution/distribution/reference/reference.go
  vendor/github.com/distribution/distribution/reference/regexp.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_catalogsources.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#2309 don't return an error if the singleton rbac doesn't exist
  pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm

#2310 Let net.Listen pick a port for grpc servers generated in tests
  pkg/controller/registry/grpc/source_test.go
Labels: approved, lgtm
