Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-04, with the labels that each got.

#2068 Bug 1945261: Fix inconsistent dependency candidate order.
  pkg/controller/registry/resolver/resolver.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2061 Dockerfile: Avoid hardcoding the kubebuilder version in the build root image
  base.Dockerfile
Labels: approved, lgtm

#2062 set packageserver replicas to 1 for single node
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  deploy/upstream/quickstart/olm.yaml
  deploy/upstream/values.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: approved, lgtm

#1653 Bug 1916624: Add CsvAbnornalReplacing alerts
  deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#2082 update of api dependency to 0.7.1
  go.mod
  go.sum
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#2076 Preserve existing ServiceAccount owner references during installs.
  pkg/controller/operators/catalog/step_ensurer.go
  pkg/controller/operators/catalog/step_ensurer_test.go
  pkg/controller/operators/olm/operator.go
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm

#2083 Do not adopt copied CSVs
  pkg/controller/operators/adoption_controller.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/operatorgroup_test.go
  pkg/controller/operators/operatorcondition_controller_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm

#2073 Bump k8s dependencies to v0.20.4
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#2086 Give more precise reasons for Subscriptions with no candidates.
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/cache_test.go
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
Labels: approved, lgtm

#2077 Indicate invalid OperatorGroup on InstallPlan status
  doc/design/architecture.md
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/lib/scoped/error.go
  pkg/lib/scoped/querier.go
  pkg/lib/scoped/querier_test.go
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm

#2085 Copy all CatalogSource annotations to its Pod
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
Labels: approved, lgtm, ok-to-test

#2090 Add time-limited retries to InstallPlan execution.
  cmd/catalog/main.go
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-installplans.crd.yaml
  deploy/ocp/values.yaml
  deploy/upstream/quickstart/crds.yaml
  deploy/upstream/quickstart/install.sh
  deploy/upstream/values.yaml
  go.mod
  go.sum
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step.go
  test/e2e/crd_e2e_test.go
  test/e2e/installplan_e2e_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_installplans.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/modules.txt
Labels: approved, lgtm

#2095 Revert "set packageserver replicas to 1 for single node"
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  deploy/upstream/quickstart/olm.yaml
  deploy/upstream/values.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: approved, lgtm

#2098 fix environment variable merging from subscription.config
  pkg/controller/operators/olm/overrides/inject/inject.go
  pkg/controller/operators/olm/overrides/inject/inject_test.go
Labels: approved, lgtm

#2099 Add resource requests for bundle unpacker
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#2081 Block OpenShift upgrades while incompatible operators are installed
  cmd/olm/main.go
  cmd/olm/manager.go
  go.mod
  go.sum
  pkg/controller/operators/openshift/clusteroperator.go
  pkg/controller/operators/openshift/clusteroperator_controller.go
  pkg/controller/operators/openshift/clusteroperator_controller_test.go
  pkg/controller/operators/openshift/helpers.go
  pkg/controller/operators/openshift/helpers_test.go
  pkg/controller/operators/openshift/options.go
  pkg/controller/operators/openshift/suite_test.go
  pkg/controller/operators/openshift/synctracker.go
  pkg/controller/operators/openshift/synctracker_test.go
  pkg/controller/operators/suite_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/inject/inject.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
Labels: approved, lgtm

#2103 fix(openshift): prevent race condition in the clusteroperator controller
  pkg/controller/operators/openshift/clusteroperator_controller.go
  pkg/controller/operators/openshift/synctracker.go
  pkg/controller/operators/openshift/synctracker_test.go
Labels: approved, lgtm

#2104 Fix resolution error if inner entry doesn't provide a required API.
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#2105 Fix panic due to empty version in the ClusterOperator controller.
  pkg/controller/operators/openshift/helpers.go
  pkg/controller/operators/openshift/helpers_test.go
Labels: approved, lgtm

#2102 fix(catalog): Reduce namespace resync in resolution failure
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
Labels: approved, lgtm

#2108 bump OLM version to 0.18.0
  OLM_VERSION
Labels: approved, lgtm

#2110 replace dockerhub images in upstream.Dockerfile
  upstream.Dockerfile
Labels: approved, lgtm

#2112 Bug 1952238: Report catalog pod termination logs to catalog operator on exit
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2115 Delete operator-lifecycle-manager.Dockerfile
  operator-lifecycle-manager.Dockerfile
Labels: approved, lgtm

#2117 changelog for v.0.18.0
  CHANGELOG.md
Labels: approved, lgtm

#2106 [release-4.7] Bug 1951232: Fix resolution error if inner entry doesn't provide a required API.
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2094 [release-4.6] Bug 1947916: Don't adopt copied csvs
  pkg/controller/operators/adoption_controller.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/operatorgroup_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2125 Use DeploymentAvailable instead of custom test for CSV status.
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  deploy/upstream/values.yaml
  pkg/controller/install/deployment_test.go
  pkg/controller/install/status_viewer.go
  pkg/controller/install/status_viewer_test.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm
