Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-03, with the labels that each got.

#2010 Bug 1926893: only override deployment resources when explicitly defined in subscription config
  Makefile
  go.mod
  go.sum
  pkg/controller/operators/olm/overrides/config.go
  pkg/controller/operators/olm/overrides/inject/inject.go
  pkg/controller/operators/olm/overrides/inject/inject_test.go
  test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operatorconditions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/errors/error.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/codec.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/client_builder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/process.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/client_builder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/inject/inject.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/response.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2021 Bug 1933779: Support InstallPlan steps upgrading existing ClusterIP Services.
  pkg/lib/operatorclient/service.go
  pkg/lib/operatorclient/service_test.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2029 Bug 1935909: Allow non-CSV-owned ServiceAccounts to satisfy CSV requirements.
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2033 Bug 1929904: Infer package name property for unannotated CSVs, if possible.
  Makefile
  pkg/controller/operators/operator_controller_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  test/e2e/e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2024 Bug 1932626: Gracefully handle service unavailable errors from kube-apiserver
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/requirements.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2026 Bug 1934637: Honor all subscriptions to a package
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/solver/constraints.go
  pkg/controller/registry/resolver/solver/installable.go
  pkg/controller/registry/resolver/solver/lit_mapping.go
  pkg/controller/registry/resolver/solver/search_test.go
  pkg/controller/registry/resolver/solver/solve.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2025 Bug 1932182: Support jittering relatively small resync intervals.
  pkg/lib/queueinformer/jitter.go
  pkg/lib/queueinformer/jitter_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2044 fix: add lifecycle/frozen tag to stalebot exempt list
  .github/stale.yml
Labels: approved, lgtm

#2043 [release-4.6] Bug 1938618: Infer package name property for unannotated CSVs, if possible.
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  test/e2e/e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2048 Bump github.com/operator-framework/api dependency to v0.7.0.
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-operatorconditions.crd.yaml
  go.mod
  go.sum
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/annotations.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorgroup.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/typecheck.go
  vendor/github.com/operator-framework/api/pkg/validation/validation.go
  vendor/modules.txt
Labels: approved, lgtm

#2045 doc: moving channel naming doc to website
  doc/design/channel-naming.md
  doc/design/images/channel-naming1.png
  doc/design/images/channel-naming2.png
Labels: approved, lgtm

#2055 Fix trailing slash in the github.com/go-bindata/go-bindata/v3/go-bindata module tool
  go.sum
  tools.go
  vendor/modules.txt
Labels: approved, lgtm

#2059 test/e2e: Remove duplicate package imports
  test/e2e/csv_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm

#2051 [release-4.6] Bug 1940649: Allow non-CSV-owned ServiceAccounts to satisfy CSV requirements.
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2054 Set labels for the operator Deployment created via the ClusterServiceVersion
  doc/design/building-your-csv.md
  pkg/controller/install/deployment.go
  pkg/controller/install/deployment_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, ok-to-test

#1936 [Doc] Update OperatorGroups Documents
  doc/design/operatorgroups.md
Labels: approved, lgtm, ok-to-test

#2036 [release-4.7] Bug 1937375: only override deployment resources when explicitly defined in subscription config
  Makefile
  go.mod
  go.sum
  pkg/controller/operators/olm/overrides/config.go
  pkg/controller/operators/olm/overrides/inject/inject.go
  pkg/controller/operators/olm/overrides/inject/inject_test.go
  test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_operatorconditions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/errors/error.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2052 [release-4.5] Bug 1940651: Allow non-CSV-owned ServiceAccounts to satisfy CSV requirements.
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1817 test: patch existing CSV for a hotfix
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm, ok-to-test

#2064 Dockerfile: Add a symbolically linked release Dockerfile
  operator-lifecycle-manager.Dockerfile
Labels: approved, lgtm

#2060 Bump the remaining images to Go 1.16
  base.Dockerfile
  go.mod
  go.sum
  upstream.Dockerfile
  vendor/modules.txt
Labels: approved, lgtm

#1937 Minor updates in the template of PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, ok-to-test

#2047 Bug 1939294: Avoid setting metadata.GracePeriodSeconds to zero seconds
  pkg/api/wrappers/deployment_install_client.go
  pkg/controller/operators/suite_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/grpc.go
  test/rh-operators/operator_util.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2070 Allow to override download url in install.sh
  scripts/install.sh
Labels: approved, lgtm, ok-to-test
