Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-12, with the labels that each got.

#2446 Rename CI github workflows
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/goreleaser.yaml
  .github/workflows/run-kind-local.yml
  .github/workflows/run-minikube-local.yml
  .github/workflows/sanity.yaml
  .github/workflows/unit.yml
  .github/workflows/verify.yml
Labels: approved, lgtm

#2501 pkg,test: Remove duplicate package imports
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/labeler.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/resolver/resolver_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm

#2460 test/e2e: Collect CatalogSource testing artifacts
  test/e2e/collect-ci-artifacts.sh
Labels: approved, lgtm

#2508 Fix e2e Subscription - creation with pod config [It] fails intermittently
  pkg/controller/install/deployment.go
Labels: ok-to-test, approved, lgtm

#2462 cmd: Silence warning about logrus.Fatal usage when directive has been supplied
  cmd/catalog/main.go
  cmd/olm/main.go
Labels: approved, lgtm

#2511 .github/workflows: Avoid specifying the paths-ignore keyword
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/run-kind-local.yml
  .github/workflows/run-minikube-local.yml
  .github/workflows/sanity.yaml
  .github/workflows/unit.yml
  .github/workflows/verify.yml
Labels: approved, lgtm

#2504 Add instructions for setting up envtest
  DEVELOPMENT.md
Labels: ok-to-test, approved, lgtm

#2456 Introduce Maintainers File
  MAINTAINERS.md
Labels: approved, lgtm

#2506 feat(resolver): support generic constraint using CEL
  pkg/controller/registry/resolver/cache/predicates.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/source_registry.go
Labels: kind/feature, approved, lgtm

#2512 feat: catalog source pod scheduling config overrides
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
  test/e2e/catsrc_pod_config_e2e_test.go
  test/e2e/ctx/provisioner_kind.go
Labels: approved, lgtm

#2466 Allow users to toggle off csv copying for AllNamespace mode operators
  deploy/chart/templates/0000_50_olm_02-olmconfig.yaml
  pkg/controller/operators/olm/operator.go
  test/e2e/csv_e2e_test.go
Labels: approved, lgtm

#2499 Address Invalid Address in GRPC Catalogs
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
Labels: approved, lgtm

#2523 Add system constraint provider logic to resolver
  pkg/controller/registry/resolver/hooks.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/solver/constraint_provider.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
Labels: approved, lgtm

#2530 fix e2e CSV metric is preserved failure
  test/e2e/metrics_e2e_test.go
Labels: ok-to-test, approved, lgtm

#2533 Fix github alias links in MAINTAINERS.md
  MAINTAINERS.md
Labels: approved, lgtm

#2463 .github/workflows: Update the checkouts action to use the v1 version
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/goreleaser.yaml
  .github/workflows/quickstart.yml
  .github/workflows/run-kind-local.yml
  .github/workflows/run-minikube-local.yml
  .github/workflows/sanity.yaml
  .github/workflows/unit.yml
  .github/workflows/verify.yml
Labels: approved, lgtm

#2464 .github/workflows: Enable workflow_dispatch event triggers
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/goreleaser.yaml
  .github/workflows/quickstart.yml
  .github/workflows/run-kind-local.yml
  .github/workflows/run-minikube-local.yml
  .github/workflows/sanity.yaml
  .github/workflows/unit.yml
  .github/workflows/verify.yml
Labels: approved, lgtm

#2525 chore(api): vendor the new version of api repo
  go.mod
  go.sum
  vendor/github.com/operator-framework/api/pkg/validation/doc.go
  vendor/modules.txt
Labels: approved, lgtm

#2528 chore(github): run e2e workflow against master periodically
  .github/workflows/e2e-tests.yml
Labels: approved, lgtm

#2535 Remove bill-of-materials.json
  bill-of-materials.json
Labels: approved, lgtm
