Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-06, with the labels that each got.

#2178 Add polling interval for default catalogsource
  deploy/chart/templates/0000_50_olm_17-upstream-operators.catalogsource.yaml
Labels: approved, lgtm

#2149 [release-4.7] Bug 1945702: Fix inconsistent dependency candidate order.
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2183 Fix nil pointer dereference while reporting bundle unpack status.
  pkg/controller/bundle/bundle_unpacker.go
Labels: approved, lgtm

#2182 Fix verify target
  Makefile
Labels: approved, lgtm

#2180 Surface API server warnings when applying plan steps.
  deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
  go.mod
  go.sum
  pkg/controller/operators/catalog/client_factory_stub_test.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/olm/client_factory_stub_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/lib/clients/factory.go
  pkg/lib/clients/transformers.go
  pkg/lib/scoped/attenuator.go
  pkg/lib/scoped/token_retriever.go
  pkg/metrics/metrics.go
  test/e2e/installplan_e2e_test.go
  test/e2e/scoped_client_test.go
  vendor/github.com/alessio/shellescape/.gitignore
  vendor/github.com/alessio/shellescape/.golangci.yml
  vendor/github.com/alessio/shellescape/.goreleaser.yml
  vendor/github.com/alessio/shellescape/.travis.yml
  vendor/github.com/alessio/shellescape/CODE_OF_CONDUCT.md
  vendor/github.com/alessio/shellescape/README.md
  vendor/github.com/alessio/shellescape/shellescape.go
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/default.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/types.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/installcni/cni.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit/init.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/create.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeadm/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/patch/mergepatch.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/common/logs.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/network.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/util.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/util.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/provider.go
  vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
  vendor/sigs.k8s.io/kind/pkg/errors/errors.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/convert_v1alpha4.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/default.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/types.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/validate.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/zz_generated.deepcopy.go
Labels: approved, lgtm

#2190 Check for conflicting install
  scripts/install.sh
Labels: approved, lgtm

#2195 [Release-0.18] Check for conflicting install
  scripts/install.sh
Labels: approved, lgtm

#2188 Fix annotations for webhooks/apiservices
  pkg/controller/install/certresources.go
  pkg/controller/install/certresources_test.go
  pkg/controller/operators/olm/apiservices.go
Labels: approved, lgtm

#2205 Resurrect deleted metrics Service templates.
  deploy/chart/templates/0000_50_olm_02-services.yaml
Labels: approved, lgtm

#2181 Registry ensure methods error out if resource is not found
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/grpc.go
Labels: approved, lgtm

#2211 install.sh should not abort if openshift olm is not installed
  scripts/install.sh
Labels: approved, lgtm, ok-to-test

#2214 Resolve InstallPlanStepAppliedWithWarnings alert after some time.
  deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
Labels: approved, lgtm

#2209 [release-4.6] Bug 1975456: Handle invalid label during resource cleanup
  pkg/controller/install/webhook.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/configmap_test.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/lib/ownerutil/util.go
  pkg/lib/ownerutil/util_test.go
  test/e2e/catalog_e2e_test.go
  test/e2e/webhook_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2224 (fix)registry: fix configmap registry server liveness probe timeouts
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm

#2198 Fixed CSV deployments label field doc
  doc/design/building-your-csv.md
Labels: approved, lgtm, ok-to-test
