Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-02, with the labels that each got.

#1982 Bug 1920526: Fix zero-delay resyncs for certain registry update policies.
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/reconciler/grpc_polling.go
  pkg/controller/registry/reconciler/grpc_polling_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1974 Bug 1917537: Fix time comparison in CSV reconcile loop
  pkg/controller/operators/olm/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1938 Bug 1899588: Only re-create operator resource if it has existing components
  pkg/controller/operators/operator_controller.go
  pkg/controller/operators/operator_controller_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1991 [release-4.6] Bug 1924257: Fix time comparison in CSV reconcile loop
  pkg/controller/operators/olm/operator.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1990 Bug 1921954: Clarify subscription constraint strings in resolution failures.
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/solver/constraints.go
  pkg/controller/registry/resolver/solver/lit_mapping.go
  pkg/controller/registry/resolver/solver/search_test.go
  pkg/controller/registry/resolver/solver/solve.go
  pkg/controller/registry/resolver/step_resolver_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1989 [release-4.6] Bug 1922919: Fix zero-delay resyncs for certain registry update policies.
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/reconciler/grpc_polling.go
  pkg/controller/registry/reconciler/grpc_polling_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1958 Bug 1913525: bump k8s.io/apiserver for webhook authorizer panic fix
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/quota/v1/resources.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authorization.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/OWNERS
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1995 Fix OperatorGroup Documentation Example
  doc/design/operatorgroups.md
Labels: approved, lgtm

#1985 [release-4.5] Bug 1921484: use OLM client when installing CRDs
  .github/workflows/test-scripts.yml
  pkg/controller/operators/catalog/operator.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1857 [release-4.5] Bug 1896079: Services should not have duplicate ownerrefs
  pkg/controller/certs/certs.go
  pkg/controller/install/certresources.go
  pkg/controller/install/certresources_test.go
  pkg/fakes/client-go/listers/fake_rbac_v1_clusterrolebinding_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_role_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_role_namespace_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_rolebinding_lister.go
  pkg/fakes/client-go/listers/fake_rbac_v1_rolebinding_namespace_lister.go
  pkg/fakes/client-go/listers/fake_v1_secret_lister.go
  pkg/fakes/client-go/listers/fake_v1_secret_namespace_lister.go
  pkg/fakes/client-go/listers/fake_v1_service_lister.go
  pkg/fakes/client-go/listers/fake_v1_service_namespace_lister.go
  pkg/lib/operatorlister/lister.go
  scripts/update_mockgen.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1909 Bug 1904584: Check sa owner 4.5
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1986 Update OWNERS file
  OWNERS
Labels: approved, lgtm

#2005 Add meaningful string representations for resolution invariants
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/solver/installable.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
Labels: approved, lgtm

#1965 Fix typo in docs
  doc/design/channel-naming.md
Labels: lgtm, ok-to-test

#1951 Bug1906056: fix(resolver): Allow skipped versions to be installed initially
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm

#2011 Bug 1925614: chore(adoption): use debug level to log missing components
  cmd/olm/manager.go
  pkg/controller/operators/adoption_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1882 add e2e environment information into DEVELOPMENT.md
  DEVELOPMENT.md
  test/e2e/README.md
Labels: ok-to-test

#1846 Update release.md with milestone step
  doc/design/release.md
Labels: approved, lgtm

#2012 Bump to go 1.15
  base.Dockerfile
  go.mod
  upstream.Dockerfile
  vendor/modules.txt
Labels: approved, lgtm

#1863 Don't create default ServiceAccounts
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/steps.go
Labels: approved, lgtm, ok-to-test

#1886 Bug 1915473: Annotate manifests for single-node-developer cluster profile
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_13-operatorgroup-default.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  scripts/add_release_annotation.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#1834 Enable debug messgaes via klog
  cmd/olm/main.go
Labels: approved, lgtm, ok-to-test

#1828 Specify cluster name when there is only one cluster in kind
  scripts/build_local.sh
Labels: approved, lgtm, ok-to-test

#2016 pkg/controller/operators/operator_controller_test.go: fix flaky test
  Makefile
  pkg/controller/operators/operator_controller_test.go
Labels: approved, lgtm

#1972 update makefile, workflow, and docs
  .github/workflows/e2e-tests.yml
  .gitignore
  Makefile
  scripts/package_release.sh
  test/e2e/README.md
  x.mk
Labels: approved, lgtm, ok-to-test

#1993 Bug 1921953: Infer package name property for unannotated CSVs, if possible.
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  test/e2e/e2e_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2008 [release-4.6] Bug 1929335: Only re-create operator resource if it has existing components
  Makefile
  pkg/controller/operators/operator_controller.go
  pkg/controller/operators/operator_controller_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
