Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-08, with the labels that each got.

#2311 Wrap catalog update test with retry logic
  test/e2e/catalog_e2e_test.go
Labels: approved, lgtm

#2305 fix(og): Fix missing MultiOperatorGroups condition in some cases
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm

#2302 fix(openshift): block upgrades on invalid max properties
  pkg/controller/operators/openshift/clusteroperator_controller.go
  pkg/controller/operators/openshift/clusteroperator_controller_test.go
  pkg/controller/operators/openshift/helpers.go
  pkg/controller/operators/openshift/helpers_test.go
Labels: approved, lgtm

#2304 Add PriorityClass setting to registry pods for CatalogSource via annotations
  pkg/controller/registry/reconciler/configmap_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm

#2312 Use GitVersion to parse version from discovery
  pkg/lib/catalogsource/image_template.go
  pkg/lib/catalogsource/image_template_test.go
Labels: approved, lgtm

#2316 Move operator caching from resolver into a new package.
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/cache/cache.go
  pkg/controller/registry/resolver/cache/cache_test.go
  pkg/controller/registry/resolver/cache/operators.go
  pkg/controller/registry/resolver/cache/operators_test.go
  pkg/controller/registry/resolver/cache/predicates.go
  pkg/controller/registry/resolver/cache/predicates_test.go
  pkg/controller/registry/resolver/groups.go
  pkg/controller/registry/resolver/groups_test.go
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/labeler.go
  pkg/controller/registry/resolver/labeler_test.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/steps.go
  pkg/controller/registry/resolver/util_test.go
  pkg/fakes/fake_api_intersection_reconciler.go
Labels: approved, lgtm

#2313 Bug 1989712: Fix for resolution error on channels with deprecated inner entries.
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm, cherry-pick-approved, bugzilla/valid-bug, bugzilla/severity-high

#2192 [release-4.7] Bug 1969320: packageserver CSV: add missing properties
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
Labels: ok-to-test, approved, lgtm, cherry-pick-approved, bugzilla/valid-bug, bugzilla/severity-low

#2323 feat: bump k8s dependencies to v0.22.0
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/apiserver/pkg/admission/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/server/options/audit.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#2319 add further console customization types
  pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm

#2324 fix(openshift): drop z from next calculated y-stream
  pkg/controller/operators/openshift/helpers.go
  pkg/controller/operators/openshift/helpers_test.go
Labels: approved, lgtm

#2326 clarify maxOpenShiftVersion upgrade error message
  pkg/controller/operators/openshift/clusteroperator_controller_test.go
  pkg/controller/operators/openshift/helpers.go
  pkg/controller/operators/openshift/helpers_test.go
Labels: approved, lgtm

#2330 Prune API of the resolver package.
  pkg/controller/operators/catalog/fakes/fake_registry_client.go
  pkg/controller/operators/catalog/fakes/fake_registry_interface.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/querier.go
  pkg/controller/operators/catalog/querier_test.go
  pkg/controller/operators/catalog/subscriptions_test.go
  pkg/controller/operators/olm/config.go
  pkg/controller/operators/olm/groups.go
  pkg/controller/operators/olm/groups_test.go
  pkg/controller/operators/olm/labeler.go
  pkg/controller/operators/olm/labeler_test.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/registry/resolver/cache/operators.go
  pkg/controller/registry/resolver/cache/operators_test.go
  pkg/controller/registry/resolver/cache/predicates.go
  pkg/controller/registry/resolver/fakes/fake_registry_interface.go
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/instrumented_resolver.go
  pkg/controller/registry/resolver/instrumented_resolver_test.go
  pkg/controller/registry/resolver/querier.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
  pkg/fakes/fake_api_intersection_reconciler.go
  pkg/fakes/fake_resolver.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#2332 Add vu dinh to OLM approvers
  OWNERS
Labels: approved, lgtm

#2335 fix broken URL in unit.yaml GH action
  .github/workflows/unit.yml
Labels: approved, lgtm

#2296 fix(sub): Reset ResolutionFailed cond when error is resolved
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/subscriptions_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#2334 Fix 2327: Detecting OLM existence before start to install
  scripts/install.sh
Labels: ok-to-test, approved, lgtm
