Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-05, with the labels that each got.

#2133 fix(bundles): symlink cp at expected path
  upstream.Dockerfile
Labels: approved, lgtm

#2137 v0.18.1 version bump
  OLM_VERSION
Labels: approved, lgtm

#2136 Fix CR validation bug on go 1.16
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/testdata/hivebug/cr.yaml
  pkg/controller/operators/catalog/testdata/hivebug/crd.yaml
  pkg/controller/operators/catalog/testdata/hivebug/fail.yaml
  vendor/k8s.io/kube-openapi/pkg/schemaconv/smd.go
  vendor/k8s.io/kube-openapi/pkg/util/util.go
  vendor/k8s.io/kube-openapi/pkg/validation/validate/type.go
  vendor/modules.txt
Labels: approved, lgtm

#2135 .github/workflows: Enable GH action that retests failed workflows
  .github/workflows/retest.yml
Labels: approved, lgtm

#2141 Fix mishandling of log format strings in Kind test provisioner.
  test/e2e/ctx/provisioner_kind.go
Labels: approved, lgtm

#2142 Add -kind.verbosity provisioner option and reduce default verbosity.
  test/e2e/ctx/provisioner_kind.go
Labels: approved, lgtm

#2096 .github/workflows: Add the unit and verify workflows
  .github/workflows/unit.yml
  .github/workflows/verify.yml
Labels: approved, lgtm

#2140 Set reason/message for Available condition in packageserver co
  pkg/lib/operatorstatus/builder.go
  pkg/lib/operatorstatus/csv_reporter.go
  pkg/lib/operatorstatus/csv_reporter_test.go
  pkg/lib/operatorstatus/monitor.go
Labels: approved, lgtm

#2134 Remove OpenShift-specific Dockerfiles.
  .github/workflows/test-scripts.yml
  Dockerfile
  base.Dockerfile
  upstream.Dockerfile
Labels: approved, lgtm

#2071 [release-4.6] Bug 1945149: only override deployment resources when explicitly defined in subscription config
  Makefile
  go.mod
  go.sum
  pkg/controller/operators/olm/overrides/config.go
  pkg/controller/operators/olm/overrides/inject.go
  pkg/controller/operators/olm/overrides/inject_test.go
  test/e2e/subscription_e2e_test.go
  vendor/github.com/operator-framework/api/LICENSE
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/manifests/bundle.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/validation/errors/error.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/object.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/operatorhub.go
  vendor/github.com/operator-framework/api/pkg/validation/validation.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2114 Annotate CRDs that are installed alongside CSVs.
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/step.go
  pkg/controller/operators/catalog/step_test.go
  pkg/controller/operators/internal/alongside/alongside.go
  pkg/controller/operators/internal/alongside/alongside_test.go
  pkg/controller/operators/olm/requirements.go
  pkg/controller/operators/olm/requirements_test.go
  pkg/lib/operatorlister/lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_clusterserviceversion_v1alpha1_lister.go
  pkg/lib/operatorlister/operatorlisterfakes/fake_clusterserviceversion_v1alpha1_namespace_lister.go
  test/e2e/csv_e2e_test.go
  test/e2e/e2e_test.go
  test/e2e/installplan_e2e_test.go
  vendor/github.com/onsi/gomega/gstruct/elements.go
  vendor/github.com/onsi/gomega/gstruct/fields.go
  vendor/github.com/onsi/gomega/gstruct/ignore.go
  vendor/github.com/onsi/gomega/gstruct/keys.go
  vendor/github.com/onsi/gomega/gstruct/pointer.go
  vendor/github.com/onsi/gomega/gstruct/types.go
  vendor/modules.txt
Labels: approved, lgtm

#2148 fix(packageserver): add tolerant delegating auth config
  pkg/package-server/server/server.go
Labels: approved, lgtm

#2153 Remove the root list of YAML manifests stored in the manifests directory
  Makefile
  doc/design/release.md
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_13-operatorgroup-default.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  manifests/image-references
Labels: approved, lgtm

#2147 Simplify deployment status check to reduce flapping.
  pkg/controller/install/status_viewer.go
  pkg/controller/install/status_viewer_test.go
Labels: approved, lgtm

#2154 Deprecated inner channel entries cause resolution error.
  pkg/controller/registry/resolver/cache.go
  pkg/controller/registry/resolver/installabletypes.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm

#2046 doc: readme add info over olm website and docs
  README.md
Labels: approved, lgtm

#2093 Fail InstallPlan on bundle unpack timeout
  cmd/catalog/main.go
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
  pkg/controller/bundle/bundlefakes/fake_unpacker.go
  pkg/controller/operators/catalog/operator.go
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm

#2151 [release-4.7] Bug 1959009: Use DeploymentAvailable instead of custom test for CSV status.
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  deploy/upstream/values.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  pkg/controller/install/deployment_test.go
  pkg/controller/install/status_viewer.go
  pkg/controller/install/status_viewer_test.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2128 [release-4.6] Bug 1955112: Preserve existing ServiceAccount owner references during installs.
  pkg/controller/operators/catalog/step_ensurer.go
  pkg/controller/operators/catalog/step_ensurer_test.go
  pkg/controller/operators/olm/operator.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2152 feat(metrics): Emit metrics for CatalogSource state
  pkg/controller/operators/catalog/operator.go
  pkg/metrics/metrics.go
  test/e2e/like_metric_matcher_test.go
  test/e2e/metrics_e2e_test.go
  test/e2e/util_test.go
Labels: approved, lgtm

#2162 Make ClusterOperator Available condition sticky.
  pkg/lib/operatorstatus/csv_reporter.go
  pkg/lib/operatorstatus/csv_reporter_test.go
Labels: approved, lgtm

#2165 Filter secret names for registry pod's sa
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
Labels: approved, lgtm

#2167 Explicitly set `readOnlyRootFilesystem: false` on created registry pods.
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
Labels: approved, lgtm

#2164 Remove component adoption labels before initial CSV copy.
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/operatorgroup_test.go
Labels: approved, lgtm

#2169 [release-4.6] Bug 1962310: Use DeploymentAvailable instead of custom test for CSV status.
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  deploy/chart/values.yaml
  deploy/ocp/values.yaml
  deploy/upstream/values.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  pkg/controller/install/deployment_test.go
  pkg/controller/install/status_viewer.go
  pkg/controller/install/status_viewer_test.go
  pkg/controller/operators/olm/operator_test.go
  test/e2e/csv_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#2171 [release-4.7] Bug 1962314: Explicitly set `readOnlyRootFilesystem: false` on created registry pods.
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
