Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2021-01, with the labels that each got.

#1887 Bug 1907329: Update /manifests with default cluster profile annotation
  manifests/0000_50_olm_00-catalogsources.crd.yaml
  manifests/0000_50_olm_00-clusterserviceversions.crd.yaml
  manifests/0000_50_olm_00-installplans.crd.yaml
  manifests/0000_50_olm_00-namespace.yaml
  manifests/0000_50_olm_00-operatorconditions.crd.yaml
  manifests/0000_50_olm_00-operatorgroups.crd.yaml
  manifests/0000_50_olm_00-operators.crd.yaml
  manifests/0000_50_olm_00-subscriptions.crd.yaml
  manifests/0000_50_olm_01-olm-operator.serviceaccount.yaml
  manifests/0000_50_olm_02-services.yaml
  manifests/0000_50_olm_07-olm-operator.deployment.yaml
  manifests/0000_50_olm_08-catalog-operator.deployment.yaml
  manifests/0000_50_olm_09-aggregated.clusterrole.yaml
  manifests/0000_50_olm_13-operatorgroup-default.yaml
  manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml
  manifests/0000_50_olm_99-operatorstatus.yaml
  manifests/0000_90_olm_00-service-monitor.yaml
  manifests/0000_90_olm_01-prometheus-rule.yaml
  scripts/add_release_annotation.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#1933 Bug 1908596: Use correct caBundle for 'olmcahash' annotation
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, ok-to-test

#1918 Bug 1912565: update moby/term dependency
  go.mod
  go.sum
  vendor/github.com/moby/term/.gitignore
  vendor/github.com/moby/term/README.md
  vendor/github.com/moby/term/ascii.go
  vendor/github.com/moby/term/go.mod
  vendor/github.com/moby/term/go.sum
  vendor/github.com/moby/term/proxy.go
  vendor/github.com/moby/term/tc.go
  vendor/github.com/moby/term/term.go
  vendor/github.com/moby/term/term_windows.go
  vendor/github.com/moby/term/termios.go
  vendor/github.com/moby/term/termios_bsd.go
  vendor/github.com/moby/term/termios_nonbsd.go
  vendor/github.com/moby/term/windows/ansi_reader.go
  vendor/github.com/moby/term/windows/ansi_writer.go
  vendor/github.com/moby/term/windows/console.go
  vendor/github.com/moby/term/windows/doc.go
  vendor/github.com/moby/term/windows/windows.go
  vendor/github.com/moby/term/winsize.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1939 Bug 1905850: Fix operatorcondition role verbs
  pkg/controller/operators/operatorcondition_controller.go
  pkg/controller/operators/operatorcondition_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1943 Bug 1913132: Create CSV Deployments with OpCond EnvVar
  pkg/controller/install/deployment.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/overrides/initializer.go
  pkg/controller/operators/olm/overrides/inject/inject.go
  pkg/controller/operators/olm/overrides/inject/inject_test.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1930 Bug 1910401: Preserve original .status.lastUpdateTime in copied CSVs.
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/operatorgroup_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/ctx/ctx.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1948 Add joelanford to OWNERS as reviewer
  OWNERS
Labels: approved, kind/documentation, lgtm

#1888 Bug 1913085: use OLM client when installing CRDs
  pkg/controller/operators/catalog/operator.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1942 Bug 1910160: Update OperatorCondition controller to watch deps
  pkg/controller/operators/operatorcondition_controller.go
  pkg/controller/operators/operatorcondition_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1941 Bug 1909992: Allow private bundle images within private indexes
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1966 Bug 1916021: Fix infinite loop when a CSV replacement chain contains a cycle.
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1975 fix: improve stalebot configuration for github issue tracking
  .github/stale.yml
Labels: approved, lgtm

#1967 Bug 1917498: use OLM client when installing CRDs
  pkg/controller/operators/catalog/operator.go
  test/e2e/installplan_e2e_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1983 Use docker driver for minikube installation test.
  .github/workflows/test-scripts.yml
Labels: approved, lgtm
