Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2022-05, with the labels that each got.

#2765 Fix currentServiceAccount debug message
  pkg/controller/registry/reconciler/grpc.go
Labels: approved, lgtm

#2752 Fix csv.status.RotatedAt update
  pkg/controller/install/certresources.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
Labels: approved, lgtm

#2673 Fixes difficult to understand error message when CSV is missing APIVersion
  pkg/controller/errors/errors.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/steps.go
  test/e2e/catalog_e2e_test.go
  test/e2e/testdata/bad-csv/bad-csv.yaml
Labels: ok-to-test, approved, lgtm

#2771 Update install.sh to use kubectl create
  scripts/install.sh
Labels: approved, lgtm

#2768 Bug 2081483: Emit csv_succeeded metrics on startup
  cmd/olm/main.go
  pkg/controller/operators/olm/operator.go
  test/e2e/metrics_e2e_test.go
Labels: approved, lgtm, cherry-pick-approved, bugzilla/valid-bug, bugzilla/severity-high, backport-risk-assessed

#2775 Refactor installer to surface certificate rotation
  pkg/controller/install/certresources.go
  pkg/controller/install/deployment.go
  pkg/controller/install/resolver.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/fakes/fake_strategy_installer.go
Labels: approved, lgtm

#2783 Delete unused registry client fake and remove go:generate.
  pkg/controller/registry/registry_client.go
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
Labels: approved, lgtm

#2784 Update installation/uninstallation docs
  doc/design/building-your-csv.md
  doc/install/install.md
Labels: lgtm
