Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2022-12, with the labels that each got.

#2903 Bump github.com/containerd/containerd to 1.6.10
  go.mod
  go.sum
  vendor/github.com/Microsoft/go-winio/backuptar/tar.go
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/hvsock.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_nonwindows.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_windows.go
  vendor/github.com/Microsoft/go-winio/pkg/security/grantvmgroupaccess.go
  vendor/github.com/Microsoft/go-winio/vhd/vhd.go
  vendor/github.com/Microsoft/go-winio/vhd/zvhd_windows.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
  vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go
  vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go
  vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
  vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go
  vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/iocp.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/system.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
  vendor/github.com/containerd/containerd/archive/tar.go
  vendor/github.com/containerd/containerd/archive/tar_unix.go
  vendor/github.com/containerd/containerd/content/helpers.go
  vendor/github.com/containerd/containerd/content/local/store.go
  vendor/github.com/containerd/containerd/filters/filter.go
  vendor/github.com/containerd/containerd/filters/parser.go
  vendor/github.com/containerd/containerd/filters/quote.go
  vendor/github.com/containerd/containerd/metadata/buckets.go
  vendor/github.com/containerd/containerd/namespaces/store.go
  vendor/github.com/containerd/containerd/platforms/platforms.go
  vendor/github.com/containerd/containerd/remotes/docker/auth/parse.go
  vendor/github.com/containerd/containerd/remotes/docker/pusher.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
  vendor/github.com/containerd/containerd/remotes/handlers.go
  vendor/github.com/containerd/containerd/snapshots/snapshotter.go
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/containerd/continuity/AUTHORS
  vendor/github.com/containerd/continuity/fs/copy.go
  vendor/github.com/containerd/continuity/fs/copy_device_unix.go
  vendor/github.com/containerd/continuity/fs/copy_irregular_freebsd.go
  vendor/github.com/containerd/continuity/fs/copy_irregular_unix.go
  vendor/github.com/containerd/continuity/fs/copy_linux.go
  vendor/github.com/containerd/continuity/fs/copy_windows.go
  vendor/github.com/containerd/continuity/fs/diff.go
  vendor/github.com/containerd/continuity/fs/dtype_linux.go
  vendor/github.com/containerd/continuity/sysx/generate.sh
  vendor/modules.txt
Labels: ok-to-test, approved, lgtm

#2904 Fix flaky unit tests
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/registry/resolver/step_resolver_test.go
Labels: ok-to-test, approved, lgtm

#2909 Update e2e catalogSources to run in restricted mode
  test/e2e/bundle_e2e_test.go
  test/e2e/catalog_e2e_test.go
  test/e2e/catalog_exclusion_test.go
  test/e2e/catsrc_pod_config_e2e_test.go
  test/e2e/dynamic_resource_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/magic_catalog.go
  test/e2e/operator_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm

#2908 OCPBUGS-4955: Set ImagePullPolicy of bundle unpacker to "IfNotPresent" for image digests
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/lib/image/image.go
  pkg/lib/image/image_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug
