Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2022-01, with the labels that each got.

#2527 Magic catalog
  test/e2e/csv_e2e_test.go
  test/e2e/fbc_provider.go
  test/e2e/magic_catalog.go
  test/e2e/magic_catalog_test.go
  test/e2e/testdata/fbc_catalog.json
  test/e2e/util.go
Labels: approved, lgtm

#2521 fix registry grpc unit test intermittent failure
  pkg/controller/registry/grpc/source_test.go
Labels: approved, lgtm

#2380 Remove NamespaceSourceQuerier API that is no longer in use
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/querier.go
  pkg/controller/operators/catalog/querier_test.go
Labels: approved, lgtm

#2548 Fix the image repository goreleaser configuration
  .github/workflows/goreleaser.yaml
  .goreleaser.yml
Labels: approved, lgtm

#2551 Update OWNERS file
  OWNERS
Labels: approved, lgtm

#2549 doc/design: Update the release documentation
  doc/design/release.md
Labels: approved, lgtm

#2543 fix disable copied csv e2e test failure
  test/e2e/csv_e2e_test.go
  test/e2e/util.go
Labels: ok-to-test, approved, lgtm

#2555 Remove the unused 'lint' Makefile target
  Makefile
Labels: approved, lgtm

#2557 Update goreleaser go version to 1.17
  .github/workflows/goreleaser.yaml
Labels: approved, lgtm

#2554 CSV e2e - wait for 2 pods ready before delete one pod
  test/e2e/csv_e2e_test.go
Labels: ok-to-test, approved, lgtm

#2562 Do not modify object from the lister cache
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/install/apiservice.go
  pkg/controller/install/webhook.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operatorgroup.go
Labels: approved, lgtm

#2547 e2e - add Eventually for config injection check
  test/e2e/subscription_e2e_test.go
Labels: ok-to-test, approved, lgtm

#2565 UT - add possible error message patterns for resolve failure
  pkg/controller/registry/resolver/resolver_test.go
Labels: ok-to-test, approved, lgtm

#2532 fix e2e config map update triggers registry pod rollout failure
  test/e2e/catalog_e2e_test.go
Labels: ok-to-test, approved, lgtm

#2510 InstallPlan wait for condition update
  test/e2e/installplan_e2e_test.go
Labels: ok-to-test, approved, lgtm

#2444 wait for catalogsource pod deletion
  test/e2e/util.go
Labels: ok-to-test, approved, lgtm

#2572 chore(constraint): Correct message to failureMessage in olm.constraint schema
  go.mod
  go.sum
  pkg/controller/registry/resolver/cache/predicates.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  vendor/github.com/operator-framework/api/pkg/constraints/constraint.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/good_practices.go
  vendor/modules.txt
Labels: approved, lgtm

#2561 recover nil GRPCConnectionState by update failure
  pkg/controller/operators/catalog/operator.go
Labels: ok-to-test, approved, lgtm, runtime

#2520 chore(e2e): naively parallelize CI jobs by chunking alphabetically
  .github/workflows/e2e-tests.yml
  Makefile
  test/e2e/split/integration_test.sh
  test/e2e/split/main.go
  test/e2e/split/main_test.go
Labels: approved, lgtm

#2541 e2e CSV test - use unique name resources for each test
  test/e2e/csv_e2e_test.go
Labels: ok-to-test, approved, lgtm

#2435 Add experimental metrics to e2e runs
  Makefile
  pkg/controller/operators/adoption_controller.go
  pkg/controller/operators/operator_controller.go
  pkg/controller/operators/operatorcondition_controller.go
  pkg/controller/operators/operatorconditiongenerator_controller.go
  pkg/metrics/experimental_declarations.go
  pkg/metrics/experimental_register.go
Labels: approved, lgtm

#2579 ci: Support configuring the logging level for the splitter package
  test/e2e/split/main.go
Labels: approved, lgtm

#2545 put mutex around installplan creation
  pkg/controller/operators/catalog/operator.go
Labels: ok-to-test, approved, lgtm, runtime

#2587 Remove unused ipLister field from OperatorStepResolver.
  pkg/controller/registry/resolver/step_resolver.go
Labels: approved, lgtm

#2601 wait for catalogsource status ready before creating subscription
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#2602 OWNERS: Add akihikokuroda as a reviewer
  OWNERS
Labels: approved, lgtm

#2603 feat: update api version to be 0.12.0 in order to use new Not constraint
  go.mod
  go.sum
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  vendor/github.com/operator-framework/api/pkg/constraints/constraint.go
  vendor/modules.txt
Labels: approved, lgtm

#2567 Makefile: Remove unused targets/variables
  Makefile
Labels: approved, lgtm

#2604 Stop corrupting resolver cache.
  pkg/controller/registry/resolver/resolver.go
Labels: approved, lgtm
