Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2022-02, with the labels that each got.

#2607 fix: remove hardcoded minikube version from build_local.sh
  scripts/build_local.sh
Labels: approved, lgtm

#2612 Add workflow for automatically rebasing open PRs
  .github/workflows/rebase.yaml
Labels: approved, lgtm

#2608 Remove the out-of-date CHANGELOG.md
  CHANGELOG.md
Labels: approved, lgtm

#2616 change Lister to DynamicClient for subscription clean up in Teardown
  test/e2e/util.go
Labels: approved, lgtm

#2606 Fix a bug in deletion of webhook service for replacement
  pkg/controller/install/certresources.go
Labels: ok-to-test, approved, lgtm

#2303 cmd/catalog: Default to the $KUBECONFIG environment variable when building client configs
  cmd/catalog/main.go
Labels: approved, lgtm

#2301 README: Remove reference to subscribing to channels through the tectonic UI
  README.md
Labels: approved, lgtm

#2622 add logo for github dark theme
  README.md
  logo-dark-mode.svg
Labels: approved, lgtm, kind/documentation

#2239 Fix cpb traverses unneeded paths
  util/cpb/main.go
Labels: ok-to-test, approved, lgtm

#2625 Initial flaky test mitigation
  .github/ISSUE_TEMPLATE/flaky-test.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/e2e-tests.yml
  .github/workflows/flaky-e2e.yml
  Makefile
  README.md
  doc/dev/reporting_flakes.md
  test/e2e/catalog_e2e_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/operator_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm

#2648 Remove CatalogSourceLister usage from resolver/cache.
  pkg/controller/registry/resolver/cache/cache.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/step_resolver.go
Labels: approved, lgtm

#2649 Remove generated and unused resolver/fakes subpackage.
  pkg/controller/registry/resolver/fakes/fake_registry_client_interface.go
Labels: approved, lgtm

#2650 Remove unused GHA workflows
  .github/workflows/flake-analyzer-periodics.yml
Labels: approved, lgtm

#2632 Replace hardcoded resolver cache mutation with CSV cache.Source.
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/cache/cache.go
  pkg/controller/registry/resolver/cache/operators.go
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/source_csvs.go
  pkg/controller/registry/resolver/source_csvs_test.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/controller/registry/resolver/step_resolver_test.go
  pkg/controller/registry/resolver/util_test.go
Labels: approved, lgtm

#2651 Give Sources control of invalidation for Snapshots they produce.
  pkg/controller/operators/catalog/operator.go
  pkg/controller/registry/resolver/cache/cache.go
  pkg/controller/registry/resolver/cache/cache_test.go
  pkg/controller/registry/resolver/instrumented_resolver.go
  pkg/controller/registry/resolver/instrumented_resolver_test.go
  pkg/controller/registry/resolver/source_csvs.go
  pkg/controller/registry/resolver/source_registry.go
  pkg/controller/registry/resolver/step_resolver.go
  pkg/fakes/fake_resolver.go
Labels: approved, lgtm

#2362 cmd/catalog: Migrate to using cobra for CLI flag management
  cmd/catalog/main.go
  cmd/catalog/start.go
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
  deploy/chart/values.yaml
Labels: approved, lgtm

#2658 Remove unused ttl field from cache.Cache.
  pkg/controller/registry/resolver/cache/cache.go
Labels: approved, lgtm

#2660 .github: Avoid disabling the go mod pkg cache for the golangci-lint action
  .github/workflows/sanity.yaml
Labels: approved, lgtm

#2661 Remove import of operators.coreos.com lister package from resolver.
  pkg/controller/registry/resolver/resolver_test.go
Labels: approved, lgtm

#2668 Mitigate flaky install plan e2e test
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#2631 fix: lower logging level to reduce noisiness
  cmd/catalog/main.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalogtemplate/operator.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/lib/csv/replace_finder.go
  pkg/lib/operatorstatus/status.go
Labels: approved, lgtm

#2675 Remove ConstraintProvider from the exported solver package API.
  pkg/controller/registry/resolver/resolver.go
  pkg/controller/registry/resolver/resolver_test.go
  pkg/controller/registry/resolver/solver/constraint_provider.go
Labels: approved, lgtm
