Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2023-10, with the labels that each got.

#3046 Change packageserver default sync to 12 hours
  pkg/package-server/server/server.go
Labels: approved

#3048 Fix Rename ClusterRoles created by OperatorGroups issues.
  pkg/controller/operators/olm/operatorgroup.go
  pkg/lib/ownerutil/util.go
Labels: approved, lgtm

#3026 README: fix broken links
  README.md
Labels: ok-to-test, approved, lgtm

#3042 Use generated namespaces in e2e tests
  test/e2e/catalog_e2e_test.go
  test/e2e/catalog_exclusion_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/deprecated_e2e_test.go
  test/e2e/disabling_copied_csv_e2e_test.go
  test/e2e/dynamic_resource_e2e_test.go
  test/e2e/fail_forward_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
Labels: approved

#3051 Fix default sync interval
  deploy/chart/templates/_packageserver.deployment-spec.yaml
  pkg/package-server/server/server.go
  test/e2e/e2e-bare-values.yaml
  test/e2e/e2e-values.yaml
Labels: approved, lgtm

#3057 test/e2e: retry a mutating call
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#3054 Don't sync namespaces that have no subscriptions
  pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm

#3043 CRD Compatibility Check Fix
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.fail.v2.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.valid.v1.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.cr.valid.v2.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.old.unserved.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.old.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.unserved.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/crontabs.crd.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-cr.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-crd.old.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1/single-version-crd.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/cr.v2.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/cr.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.no-versions-list.old.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.no-versions-list.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.old.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.unserved.yaml
  pkg/controller/operators/catalog/testdata/apiextensionsv1beta1/crd.yaml
Labels: approved, lgtm

#3064 Update Owners File
  OWNERS
Labels: approved, lgtm

#3066 test/e2e/fail-forward: use internal catalogs, change failure mode
  test/e2e/fail_forward_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/testdata/fail-forward/multiple-bad-versions/example-operator.v0.2.1-non-existent-tag.yaml
  test/e2e/testdata/fail-forward/multiple-bad-versions/example-operator.v0.3.0.yaml
  test/e2e/testdata/fail-forward/replaces/example-operator.v0.3.0.yaml
  test/e2e/testdata/fail-forward/skip-range/example-operator.v0.3.0.yaml
  test/e2e/testdata/fail-forward/skips/example-operator.v0.3.0.yaml
  test/e2e/testdata/fail-forward/v0.1.0/clusterserviceversion.yaml
  test/e2e/testdata/fail-forward/v0.1.0/packagemanifest.yaml
  test/e2e/testdata/fail-forward/v0.2.0-invalid-csv/clusterserviceversion.yaml
  test/e2e/testdata/fail-forward/v0.2.0-invalid-csv/packagemanifest.yaml
  test/e2e/testdata/fail-forward/v0.2.0-invalid-deployment/clusterserviceversion.yaml
  test/e2e/testdata/fail-forward/v0.2.0-invalid-deployment/packagemanifest.yaml
  test/e2e/testdata/fail-forward/v0.2.1-invalid-csv/clusterserviceversion.yaml
  test/e2e/testdata/fail-forward/v0.2.1-invalid-csv/packagemanifest.yaml
  test/e2e/testdata/fail-forward/v0.3.0-replaces-invalid-csv/clusterserviceversion.yaml
  test/e2e/testdata/fail-forward/v0.3.0-replaces-invalid-csv/packagemanifest.yaml
  test/e2e/testdata/fail-forward/v0.3.0-replaces-invalid-deployment/clusterserviceversion.yaml
  test/e2e/testdata/fail-forward/v0.3.0-replaces-invalid-deployment/packagemanifest.yaml
  test/e2e/testdata/fail-forward/v0.3.0-skip-range/clusterserviceversion.yaml
  test/e2e/testdata/fail-forward/v0.3.0-skip-range/packagemanifest.yaml
  test/e2e/testdata/fail-forward/v0.3.0-skips/clusterserviceversion.yaml
  test/e2e/testdata/fail-forward/v0.3.0-skips/packagemanifest.yaml
  test/e2e/testdata/subscription/example-operator.v0.1.0.yaml
  test/e2e/testdata/subscription/example-operator.v0.2.0-invalid-csv.yaml
  test/e2e/testdata/subscription/example-operator.v0.2.0-non-existent-tag.yaml
  test/e2e/testdata/subscription/example-operator.v0.2.0.yaml
  test/e2e/testdata/subscription/example-operator.v0.3.0.yaml
  test/e2e/util.go
Labels: approved, lgtm

#3069 Do not derive installplan.spec.clusterServiceNames from bundle IDs
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
Labels: approved, lgtm

#3070 flaky-e2e-tests fix
  test/e2e/installplan_e2e_test.go
Labels: approved, lgtm

#3071 controller: add more logging to labelling
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/labeller/labels.go
  pkg/controller/operators/labeller/rbac.go
  pkg/controller/operators/olm/operator.go
Labels: approved, lgtm

#3074 Fix e2e where subscription is updated
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#3078 labellers: use unique field managers
  pkg/controller/operators/labeller/labels.go
  pkg/controller/operators/labeller/rbac.go
Labels: approved, lgtm

#3076 Specify exact verbs that OLM requires
  deploy/chart/templates/0000_50_olm_01-olm-operator.serviceaccount.yaml
Labels: approved, lgtm

#3079 Fix typo in the CsvAbnormalFailedOver2Min alerting rule
  deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
Labels: ok-to-test, approved, lgtm

#3081 registry/reconciler: allow current pods to be not ready
  pkg/controller/registry/reconciler/grpc.go
Labels: approved, lgtm
