Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2023-01, with the labels that each got.

#2915 Run community catalogSource in restricted mode
  deploy/chart/templates/0000_50_olm_17-upstream-operators.catalogsource.yaml
Labels: approved, lgtm

#2913 OCPBUGS-5523: Catalog, fatal error: concurrent map read and map write
  pkg/metrics/metrics.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#2896 Don't use $BUILDPLATFORM image for goreleaser
  Dockerfile.goreleaser
Labels: ok-to-test, approved, lgtm
