Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2023-08, with the labels that each got.

#3003 OCPBUGS-17157: improve watching semantics around CSVs
  cmd/olm/main.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/olm/config.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/olm/operatorgroup_test.go
  vendor/k8s.io/client-go/metadata/fake/simple.go
  vendor/k8s.io/client-go/metadata/metadatainformer/informer.go
  vendor/k8s.io/client-go/metadata/metadatainformer/interface.go
  vendor/k8s.io/client-go/metadata/metadatalister/interface.go
  vendor/k8s.io/client-go/metadata/metadatalister/lister.go
  vendor/k8s.io/client-go/metadata/metadatalister/shim.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3005 OCPBUGS-17157: operators/olm: record and expose informers
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/plugins/operator_plugin.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3007 OCPBUGS-17157: queueinformer: don't double register informers
  pkg/lib/queueinformer/queueinformer_operator.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3008 Add tmshort to reviewers
  OWNERS
Labels: approved, lgtm

#3011 [chore] Update github.com/emicklei/go-restful/v3 to v3.10.2
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/modules.txt
Labels: approved, lgtm

#3012 OCPBUGS-8993: add namespace label to InstallPlanStepAppliedWithWarnings
  deploy/chart/templates/0000_90_olm_01-prometheus-rule.yaml
Labels: ok-to-test, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#3006 reconcile clusteroperator status more frequently
  pkg/lib/operatorstatus/status.go
Labels: ok-to-test, approved, lgtm

#3017 OCPBUGS-17157: label non-OLM resources
  cmd/olm/main.go
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
  pkg/controller/install/certresources.go
  pkg/controller/install/certresources_test.go
  pkg/controller/install/deployment.go
  pkg/controller/install/webhook.go
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/operators/catalog/step.go
  pkg/controller/operators/catalog/step_ensurer.go
  pkg/controller/operators/olm/apiservices.go
  pkg/controller/operators/olm/operatorgroup.go
  pkg/controller/operators/operatorcondition_controller.go
  pkg/controller/operators/validatingroundtripper/validating_round_tripper.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/util.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
