Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2023-12, with the labels that each got.

#3128 Deprecation Snapshot Source Namespace
  pkg/controller/operators/catalog/subscription/reconciler.go
Labels: approved, lgtm

#3133 deploy: use Recreate strategy for Deployments
  deploy/chart/templates/0000_50_olm_07-olm-operator.deployment.yaml
  deploy/chart/templates/0000_50_olm_08-catalog-operator.deployment.yaml
Labels: approved, lgtm

#3137 test/e2e: emit helpful comments as logs
  test/e2e/bundle_e2e_test.go
  test/e2e/catalog_e2e_test.go
  test/e2e/catalog_exclusion_test.go
  test/e2e/catsrc_pod_config_e2e_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/deprecated_e2e_test.go
  test/e2e/disabling_copied_csv_e2e_test.go
  test/e2e/dynamic_resource_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/metrics_e2e_test.go
  test/e2e/operator_condition_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/resource_manager_test.go
  test/e2e/scoped_client_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm

#3138 OCPBUGS-25673: labeller: also consider v2 group in owner refs
  pkg/controller/operators/labeller/labels.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3139 events: filter spammy events for the same object and reason
  pkg/lib/event/event.go
Labels: approved
