Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2023-09, with the labels that each got.

#3020 OCPBUGS-17157: *: label k8s objects we own
  go.mod
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/internal/alongside/alongside.go
  pkg/controller/operators/internal/alongside/alongside_test.go
  pkg/controller/operators/labeller/labels.go
  pkg/controller/operators/olm/operator.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3021 OCPBUGS-17157: *: filter informers when preconditions are met
  go.mod
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/labeller/filters.go
  pkg/controller/operators/labeller/labels.go
  pkg/controller/operators/olm/operator.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3030 Update operator-registry ref to 1.29.0
  go.mod
  go.sum
  vendor/github.com/Azure/go-ansiterm/SECURITY.md
  vendor/github.com/Microsoft/go-winio/.golangci.yml
  vendor/github.com/Microsoft/go-winio/hvsock.go
  vendor/github.com/Microsoft/go-winio/internal/fs/doc.go
  vendor/github.com/Microsoft/go-winio/internal/fs/fs.go
  vendor/github.com/Microsoft/go-winio/internal/fs/security.go
  vendor/github.com/Microsoft/go-winio/internal/fs/zsyscall_windows.go
  vendor/github.com/Microsoft/go-winio/internal/socket/socket.go
  vendor/github.com/Microsoft/go-winio/internal/stringbuffer/wstring.go
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/Microsoft/go-winio/tools/mkwinsyscall/mkwinsyscall.go
  vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
  vendor/github.com/golang-migrate/migrate/v4/source/driver.go
  vendor/github.com/golang-migrate/migrate/v4/source/errors.go
  vendor/github.com/golang-migrate/migrate/v4/source/file/file.go
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/README.md
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/doc.go
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/iofs.go
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/1_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/1_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/3_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/4_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/4_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/5_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/7_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/7_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/migration.go
  vendor/github.com/golang-migrate/migrate/v4/source/parse.go
  vendor/github.com/mattn/go-sqlite3/README.md
  vendor/github.com/mattn/go-sqlite3/sqlite3-binding.h
  vendor/github.com/mattn/go-sqlite3/sqlite3.go
  vendor/github.com/mattn/go-sqlite3/sqlite3_opt_math_functions.go
  vendor/github.com/mattn/go-sqlite3/sqlite3_opt_os_trace.go
  vendor/github.com/mattn/go-sqlite3/sqlite3_windows.go
  vendor/github.com/moby/term/doc.go
  vendor/github.com/moby/term/tc.go
  vendor/github.com/moby/term/term.go
  vendor/github.com/moby/term/term_unix.go
  vendor/github.com/moby/term/term_windows.go
  vendor/github.com/moby/term/termios.go
  vendor/github.com/moby/term/termios_unix.go
  vendor/github.com/moby/term/termios_windows.go
  vendor/github.com/moby/term/windows/ansi_reader.go
  vendor/github.com/moby/term/windows/console.go
  vendor/github.com/moby/term/winsize.go
  vendor/github.com/operator-framework/operator-registry/alpha/property/property.go
  vendor/github.com/operator-framework/operator-registry/alpha/property/scheme.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/api_to_model.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/model_to_api.go
  vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/modules.txt
Labels: approved, lgtm

#3029 controller/registry: implement content extraction for catalog sources
  deploy/chart/crds/0000_50_olm_00-catalogsources.crd.yaml
  go.mod
  go.sum
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/configmap_test.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/grpc_test.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
  test/e2e/catalog_e2e_test.go
  test/e2e/e2e_test.go
  test/e2e/util.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_catalogsources.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#3033 remove dangling unused constant
  pkg/lib/ownerutil/util.go
Labels: approved, lgtm

#3034 OCPBUGS-17157: pkg/controller: label RBAC with content hash
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/labeller/filters.go
  pkg/controller/operators/labeller/rbac.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/registry/resolver/rbac.go
  pkg/package-server/provider/registry_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3037 test/e2e: improve waits, logs, etc
  scripts/build_local.sh
  scripts/lib/olm_util.sh
  test/e2e/bundle_e2e_test.go
  test/e2e/catalog_e2e_test.go
  test/e2e/crd_e2e_test.go
  test/e2e/csv_e2e_test.go
  test/e2e/dynamic_resource_e2e_test.go
  test/e2e/e2e_test.go
  test/e2e/fail_forward_e2e_test.go
  test/e2e/gc_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/metrics_e2e_test.go
  test/e2e/operator_condition_e2e_test.go
  test/e2e/operator_groups_e2e_test.go
  test/e2e/operator_test.go
  test/e2e/packagemanifest_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/user_defined_sa_test.go
  test/e2e/util.go
  test/e2e/webhook_e2e_test.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#3041 controller/registry: use static copy-content binary for copy
  cmd/copy-content/main.go
  e2e.Dockerfile
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  pkg/controller/registry/reconciler/configmap.go
  pkg/controller/registry/reconciler/grpc.go
  pkg/controller/registry/reconciler/reconciler.go
  pkg/controller/registry/reconciler/reconciler_test.go
Labels: approved, lgtm
