Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2023-02, with the labels that each got.

#2918 Introduce Thread Safety test for UpdateSubsSyncCounterStorage
  pkg/metrics/metrics_test.go
Labels: approved, lgtm

#2921 Bump Fedora Version for Builder Image
  Dockerfile
Labels: approved, lgtm

#2919 OCPBUGS-672: Catalog Pod Startup Probe Timeout
  pkg/controller/registry/reconciler/reconciler.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#2920 OCPBUGS-6016: UpdateStrategy RegistryPoll with nil Interval
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#2925 Sort channels in lexicographical order in packagemanifest
  pkg/package-server/provider/registry.go
  pkg/package-server/provider/registry_test.go
Labels: approved, lgtm
