Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2023-04, with the labels that each got.

#2934 Fixes echo of the current cluster name
  scripts/build_local.sh
Labels: approved, lgtm

#2937 Fixes godoc rendering
  pkg/lib/controller-runtime/client/ssa.go
Labels: approved, lgtm

#2951 Remove extra jobLabel
  deploy/chart/templates/0000_90_olm_00-service-monitor.yaml
Labels: approved, lgtm

#2890 Change opm image from `quay.io/operator-framework/upstream-opm-builder` to `quay.io/operator-framework/opm`
  cmd/catalog/main.go
  test/e2e/magic_catalog.go
Labels: approved, lgtm, needs-ok-to-test

#2953 Fix example string for svg icon types
  doc/design/building-your-csv.md
Labels: approved

#2911 Workaround server-side apply not working
  deploy/chart/templates/_packageserver.deployment-spec.yaml
Labels: ok-to-test, approved, lgtm

#2956 GitHub Actions Updates
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/flaky-e2e.yml
  .github/workflows/goreleaser.yaml
  .github/workflows/quickstart.yml
  .github/workflows/run-kind-local.yml
  .github/workflows/run-minikube-local.yml
  .github/workflows/sanity.yaml
  .github/workflows/unit.yml
  .github/workflows/verify.yml
Labels: approved, lgtm

#2685 Add linux node selector to bundleUnpacker job
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
Labels: ok-to-test, approved, lgtm

#2952 Moves bundle unpack timeout into OperatorGroup
  pkg/controller/bundle/bundle_unpacker.go
  pkg/controller/bundle/bundle_unpacker_test.go
  pkg/controller/operators/catalog/operator.go
  test/e2e/fail_forward_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/util.go
Labels: approved, lgtm

#2954 Updates github.com/operator-framework/api
  deploy/chart/crds/0000_50_olm_00-clusterserviceversions.crd.yaml
  deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  go.mod
  go.sum
  pkg/package-server/client/openapi/zz_generated.openapi.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_clusterserviceversions.yaml
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_subscriptions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/multiarch.go
  vendor/github.com/operator-framework/api/pkg/validation/internal/removed_apis.go
  vendor/modules.txt
Labels: approved, lgtm
