Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2024-01, with the labels that each got.

#3129 Fix e2e Install Plan creation with permission
  test/e2e/csv_e2e_test.go
  test/e2e/installplan_e2e_test.go
  test/e2e/subscription_e2e_test.go
  test/e2e/util.go
Labels: approved

#3145 Improve condition check for installplan
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#3149 Snapshot Fix for Deprecation Info
  pkg/controller/operators/catalog/operator.go
Labels: approved, lgtm

#3148 CSV Finalizer
  cmd/olm/manager.go
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/operatorconditiongenerator_controller.go
Labels: approved

#3153 Fix Condition check for Reconcile InstallPlan status
  test/e2e/subscription_e2e_test.go
Labels: approved

#3157 OCPBUGS-25989: operators/olm: filter RBAC lists by namespace
  pkg/controller/operators/olm/requirements.go
Labels: approved, jira/valid-bug, jira/valid-reference

#3160 Update golangci-lint to 1.55
  .github/workflows/sanity.yaml
  .golangci.yaml
Labels: approved, lgtm

#3158 OCPBUGS-25989: go.mod: bump golang to 1.21
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
