Repository operator-framework/operator-lifecycle-manager, pull requests merged in 2024-02, with the labels that each got.

#3165 olm,catalog: only validate the resources we label
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/ownerrefs_test.go
  pkg/controller/operators/labeller/filters.go
  pkg/controller/operators/olm/operator.go
  pkg/lib/ownerutil/util.go
  pkg/lib/testobj/runtime.go
Labels: approved

#3166 Clear (existing) error cond from Subscription, once error resolved
  pkg/controller/operators/catalog/operator.go
  pkg/controller/operators/catalog/operator_test.go
  test/e2e/subscription_e2e_test.go
Labels: approved, lgtm

#3168 Remove ncdc from OWNERS
  OWNERS
Labels: approved, lgtm

#3173 Fix crd data loss e2e test
  test/e2e/crd_e2e_test.go
Labels: approved, lgtm

#3169 Apply Subscription.Spec.Config.Annotations to Deployments, Pods, ApiServices
  deploy/chart/crds/0000_50_olm_00-subscriptions.crd.yaml
  go.mod
  go.sum
  pkg/controller/install/apiservice.go
  pkg/controller/install/deployment.go
  pkg/controller/operators/olm/overrides/config.go
  pkg/controller/operators/olm/overrides/initializer.go
  pkg/controller/operators/olm/overrides/inject/inject.go
  pkg/controller/operators/olm/overrides/inject/inject_test.go
  vendor/github.com/operator-framework/api/crds/operators.coreos.com_subscriptions.yaml
  vendor/github.com/operator-framework/api/crds/zz_defs.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: ok-to-test

#3180 Fix finalizer processing
  pkg/controller/operators/olm/operator.go
  pkg/controller/operators/olm/operator_test.go
  pkg/controller/operators/operatorconditiongenerator_controller.go
  test/e2e/installplan_e2e_test.go
Labels: lgtm
